// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5af1700726b89e13 "Cliplab Studio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Open' | 'Closed' // Variant
 * question?: string // Question
 * answer?: string // Answer
}} Props

 */
import { AvoidLayoutJumping, stdin_default } from "./chunks/chunk-ZYZTC6T6.js";
import { className, css, fonts } from "./chunks/chunk-AN6VZTLK.js";
import { routes } from "./chunks/chunk-2NVZ5JSA.js";

// virtual:faq-accordion
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/qwWtwBF7x2IVCooua4rY/Y20BybGKgvd0iwfufnM3/lZaVBJArg.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
	withOptimizedAppearEffect,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var PlusFonts = getFonts(stdin_default);
var MotionDivWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(motion.div),
);
var LayoutJumpPreventerFonts = getFonts(AvoidLayoutJumping);
var cycleOrder = ["C72KvUTTG", "xMMTb1ZOB"];
var serializationHash = "framer-JFEbX";
var variantClassNames = {
	C72KvUTTG: "framer-v-ajwi8d",
	xMMTb1ZOB: "framer-v-11i80fw",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 80,
	delay: 0,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var transition2 = {
	damping: 80,
	delay: 0.1,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 10,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Closed: "xMMTb1ZOB",
	Open: "C72KvUTTG",
};
var getProps = ({ answer, height, id, question, width, ...props }) => {
	return {
		...props,
		ksyW0hYvf:
			answer ??
			props.ksyW0hYvf ??
			"Not at all\u2014our course begins with the basics and gradually builds to advanced techniques.",
		o83AMZeI_:
			question ?? props.o83AMZeI_ ?? "Do I need editing experience to start?",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "C72KvUTTG",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		o83AMZeI_: o83AMZeI_2,
		ksyW0hYvf: ksyW0hYvf2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "C72KvUTTG",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap9u0n23 = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("xMMTb1ZOB");
	});
	const onTapwmyw5o = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("C72KvUTTG");
	});
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "xMMTb1ZOB") return false;
		return true;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-ajwi8d",
							className2,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Open"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"C72KvUTTG"}
						onTap={onTap9u0n23}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-d4c36658-1f4b-41b3-aa0d-cf9b918d88bf, rgb(0, 99, 186))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							background:
								"linear-gradient(180deg, var(--token-efc840ff-64db-4d68-b4f9-ffd23b298cd4, rgba(255, 255, 255, 0.05)) 0%, var(--token-737547ea-dc46-45bd-ae2b-4977e3da045e, rgba(9, 0, 189, 0.05)) 100%)",
							borderBottomLeftRadius: 10,
							borderBottomRightRadius: 10,
							borderTopLeftRadius: 10,
							borderTopRightRadius: 10,
							...style,
						}}
						variants={{
							xMMTb1ZOB: {
								"--border-color":
									"var(--token-cb2206d2-93ba-4bbf-8a99-2fb6eb742230, rgba(255, 255, 255, 0.1))",
							},
						}}
						{...addPropertyOverrides(
							{
								xMMTb1ZOB: {
									"data-framer-name": "Closed",
									onTap: onTapwmyw5o,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-pq07xr"}
							data-framer-name={"Question Container"}
							layoutDependency={layoutDependency}
							layoutId={"xvV67ekLp"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1ycnpg4"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"RUVjqCyZ9"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-9d9c37d5-31f4-4564-b2ab-c0d257f64cbd, rgb(250, 250, 250))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={o83AMZeI_2}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1ozhwx8"}
										data-styles-preset={"BsEnbfNw3"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-9d9c37d5-31f4-4564-b2ab-c0d257f64cbd, rgb(250, 250, 250)))",
										}}
									>
										{"Do I need editing experience to start?"}
									</motion.p>
								</React.Fragment>
							</RichText>
							<motion.div
								className={"framer-aurevv"}
								data-framer-name={"Icon"}
								layoutDependency={layoutDependency}
								layoutId={"sCHJQe0I1"}
								style={{
									background:
										"linear-gradient(41deg, var(--token-d4c36658-1f4b-41b3-aa0d-cf9b918d88bf, rgb(0, 122, 187)) 0%, var(--token-8697dd16-e69c-4ab8-867d-4123683efde7, rgb(255, 255, 255)) 100%)",
									borderBottomLeftRadius: 185,
									borderBottomRightRadius: 185,
									borderTopLeftRadius: 185,
									borderTopRightRadius: 185,
								}}
							>
								{_jsx(stdin_default, {
									animated: true,
									className: "framer-10trrn8",
									layoutDependency,
									layoutId: "J32gKRX22",
									style: {
										"--1m6trwb": 0,
										"--21h8s6": "rgb(0, 0, 0)",
										"--pgex8v": 2.5,
										rotate: 45,
									},
									variants: {
										xMMTb1ZOB: {
											rotate: 0,
										},
									},
								})}
							</motion.div>
						</motion.div>
						{isDisplayed() && (
							<MotionDivWithFXWithOptimizedAppearEffect
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								animate={animation}
								className={"framer-1xiuenr"}
								data-framer-appear-id={"1xiuenr"}
								data-framer-name={"Answer Container"}
								initial={animation1}
								layoutDependency={layoutDependency}
								layoutId={"FNYAT927O"}
								optimized={true}
								style={{
									backgroundColor:
										"var(--token-efc840ff-64db-4d68-b4f9-ffd23b298cd4, rgba(255, 255, 255, 0.05))",
									borderBottomLeftRadius: 8,
									borderBottomRightRadius: 8,
									borderTopLeftRadius: 8,
									borderTopRightRadius: 8,
								}}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1nl58fn"}
									data-framer-name={
										"Not at all\u2014our course begins with the basics and gradually builds to advanced techniques."
									}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"YpVYX2WnE"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-b1f5477e-0c35-4cdc-8900-c9aed722522e, rgb(168, 168, 168))",
										"--framer-paragraph-spacing": "0px",
									}}
									text={ksyW0hYvf2}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1ozhwx8"}
											data-styles-preset={"BsEnbfNw3"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-b1f5477e-0c35-4cdc-8900-c9aed722522e, rgb(168, 168, 168)))",
											}}
										>
											{
												"Not at all\u2014our course begins with the basics and gradually builds to advanced techniques."
											}
										</motion.p>
									</React.Fragment>
								</RichText>
							</MotionDivWithFXWithOptimizedAppearEffect>
						)}
						<ComponentViewportProvider>
							<SmartComponentScopedContainer
								className={"framer-13awjwi-container"}
								isAuthoredByUser={true}
								isModuleExternal={true}
								layoutDependency={layoutDependency}
								layoutId={"ghSyCWx3K-container"}
								nodeId={"ghSyCWx3K"}
								rendersWithMotion={true}
								scopeId={"lZaVBJArg"}
							>
								<AvoidLayoutJumping
									direction={"vertical"}
									height={"100%"}
									id={"ghSyCWx3K"}
									layoutId={"ghSyCWx3K"}
									width={"100%"}
								/>
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-JFEbX.framer-68a8ih, .framer-JFEbX .framer-68a8ih { display: block; }",
	".framer-JFEbX.framer-ajwi8d { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: visible; padding: 24px; position: relative; width: 588px; }",
	".framer-JFEbX .framer-pq07xr { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; }",
	".framer-JFEbX .framer-1ycnpg4 { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-JFEbX .framer-aurevv { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 28px); justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 28px; will-change: var(--framer-will-change-override, transform); }",
	".framer-JFEbX .framer-10trrn8 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 16px); position: relative; width: 16px; }",
	".framer-JFEbX .framer-1xiuenr { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 16px; position: relative; width: 100%; z-index: 1; }",
	".framer-JFEbX .framer-1nl58fn { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-JFEbX .framer-13awjwi-container { bottom: 24px; flex: none; height: auto; left: 24px; position: absolute; width: auto; z-index: 1; }",
	...css,
	'.framer-JFEbX[data-border="true"]::after, .framer-JFEbX [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramerlZaVBJArg = withCSS(Component, css2, "framer-JFEbX");
var stdin_default2 = FramerlZaVBJArg;
FramerlZaVBJArg.displayName = "FAQ Accordion";
FramerlZaVBJArg.defaultProps = {
	height: 177,
	width: 588,
};
addPropertyControls(FramerlZaVBJArg, {
	variant: {
		options: ["C72KvUTTG", "xMMTb1ZOB"],
		optionTitles: ["Open", "Closed"],
		title: "Variant",
		type: ControlType.Enum,
	},
	o83AMZeI_: {
		defaultValue: "Do I need editing experience to start?",
		displayTextArea: false,
		title: "Question",
		type: ControlType.String,
	},
	ksyW0hYvf: {
		defaultValue:
			"Not at all\u2014our course begins with the basics and gradually builds to advanced techniques.",
		displayTextArea: false,
		title: "Answer",
		type: ControlType.String,
	},
});
addFonts(
	FramerlZaVBJArg,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...PlusFonts,
		...LayoutJumpPreventerFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:faq-accordion
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "xMMTb1ZOB",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5af1700726b89e1359bd903da3e469ba956b8fc7e56af575f49bcf468e7d9c62"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FaqAccordionFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5af1700726b89e1359bd903da3e469ba956b8fc7e56af575f49bcf468e7d9c62"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var faq_accordion_default = ComponentWithRoot;
export { faq_accordion_default as default };
