// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5af1700726b89e13 "Cliplab Studio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'L' | 'M/S' // Variant
 * link?: string // Link
 * newTab?: boolean // New Tab
 * title?: string // Title
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-NORUQDUQ.js";
import { routes } from "./chunks/chunk-2NVZ5JSA.js";

// virtual:footer-link
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/mGfSqbOdmU5cyIRoKiyf/DAyMU0ih7eZC7l2cG4Vm/wfU0EgMxC.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Link,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var enabledGestures = {
	zCC0QNAlQ: {
		hover: true,
	},
};
var cycleOrder = ["zCC0QNAlQ", "pfEQ7EjKW"];
var serializationHash = "framer-st0je";
var variantClassNames = {
	pfEQ7EjKW: "framer-v-1iyksqd",
	zCC0QNAlQ: "framer-v-duz9zq",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 80,
	delay: 0,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"M/S": "pfEQ7EjKW",
	L: "zCC0QNAlQ",
};
var getProps = ({ height, id, link, newTab, title, width, ...props }) => {
	return {
		...props,
		o8XtFW7g3: link ?? props.o8XtFW7g3,
		PKluglPX3: title ?? props.PKluglPX3 ?? "Home",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "zCC0QNAlQ",
		vBZrE1HB9: newTab ?? props.vBZrE1HB9,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		o8XtFW7g3: o8XtFW7g32,
		vBZrE1HB9: vBZrE1HB92,
		PKluglPX3: PKluglPX32,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "zCC0QNAlQ",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={o8XtFW7g32}
						motionChild={true}
						nodeId={"zCC0QNAlQ"}
						openInNewTab={vBZrE1HB92}
						scopeId={"wfU0EgMxC"}
						smoothScroll={true}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-duz9zq", className2, classNames)} framer-qdv2pg`}
							data-framer-name={"L"}
							layoutDependency={layoutDependency}
							layoutId={"zCC0QNAlQ"}
							ref={refBinding}
							style={{
								opacity: 1,
								...style,
							}}
							variants={{
								"zCC0QNAlQ-hover": {
									opacity: 0.4,
								},
							}}
							{...addPropertyOverrides(
								{
									"zCC0QNAlQ-hover": {
										"data-framer-name": void 0,
									},
									pfEQ7EjKW: {
										"data-framer-name": "M/S",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1uups7e"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"Xxxli7kfh"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-9d9c37d5-31f4-4564-b2ab-c0d257f64cbd, rgb(250, 250, 250))",
								}}
								text={PKluglPX32}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1ozhwx8"}
										data-styles-preset={"BsEnbfNw3"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-9d9c37d5-31f4-4564-b2ab-c0d257f64cbd, rgb(250, 250, 250)))",
										}}
									>
										{"Home"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-st0je.framer-qdv2pg, .framer-st0je .framer-qdv2pg { display: block; }",
	".framer-st0je.framer-duz9zq { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; text-decoration: none; width: min-content; }",
	".framer-st0je .framer-1uups7e { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-st0je.framer-v-1iyksqd.framer-duz9zq { cursor: unset; }",
	...css,
];
var FramerwfU0EgMxC = withCSS(Component, css2, "framer-st0je");
var stdin_default = FramerwfU0EgMxC;
FramerwfU0EgMxC.displayName = "Footer Link";
FramerwfU0EgMxC.defaultProps = {
	height: 22,
	width: 45,
};
addPropertyControls(FramerwfU0EgMxC, {
	variant: {
		options: ["zCC0QNAlQ", "pfEQ7EjKW"],
		optionTitles: ["L", "M/S"],
		title: "Variant",
		type: ControlType.Enum,
	},
	o8XtFW7g3: {
		title: "Link",
		type: ControlType.Link,
	},
	vBZrE1HB9: {
		defaultValue: false,
		title: "New Tab",
		type: ControlType.Boolean,
	},
	PKluglPX3: {
		defaultValue: "Home",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
});
addFonts(
	FramerwfU0EgMxC,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:footer-link
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "pfEQ7EjKW",
	xl: "zCC0QNAlQ",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5af1700726b89e1359bd903da3e469ba956b8fc7e56af575f49bcf468e7d9c62"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FooterLinkFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5af1700726b89e1359bd903da3e469ba956b8fc7e56af575f49bcf468e7d9c62"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var footer_link_default = ComponentWithRoot;
export { footer_link_default as default };
