// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5af1700726b89e13 "Cliplab Studio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Loading' | 'Disabled' | 'Success' | 'Error' // Variant
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-6HGIPRDC.js";
import { routes } from "./chunks/chunk-2NVZ5JSA.js";

// virtual:form-button
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/viijXFC26Ky9kTtnvwm7/6mcTvlUimntKaMqiNHRv/wnBKlpzlR.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var MotionDivWithFX = withFX(motion.div);
var enabledGestures = {
	bigSzDPVI: {
		hover: true,
		pressed: true,
	},
};
var cycleOrder = [
	"bigSzDPVI",
	"MT1LFcdyy",
	"Zte21atJt",
	"DiAEzRCvm",
	"viRNVuZth",
];
var serializationHash = "framer-0e1zl";
var variantClassNames = {
	bigSzDPVI: "framer-v-1hshbsm",
	DiAEzRCvm: "framer-v-19dga47",
	MT1LFcdyy: "framer-v-ry0bo2",
	viRNVuZth: "framer-v-1e6fem1",
	Zte21atJt: "framer-v-1rok438",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 80,
	delay: 0,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var transition2 = {
	delay: 0,
	duration: 1,
	ease: [0, 0, 1, 1],
	type: "tween",
};
var animation = {
	opacity: 1,
	rotate: 360,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Default: "bigSzDPVI",
	Disabled: "Zte21atJt",
	Error: "viRNVuZth",
	Loading: "MT1LFcdyy",
	Success: "DiAEzRCvm",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "bigSzDPVI",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "bigSzDPVI",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "MT1LFcdyy") return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "MT1LFcdyy") return true;
		return false;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.button
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1hshbsm",
							className2,
							classNames,
						)}
						data-framer-name={"Default"}
						data-reset={"button"}
						layoutDependency={layoutDependency}
						layoutId={"bigSzDPVI"}
						ref={refBinding}
						style={{
							background:
								"linear-gradient(180deg, var(--token-d4c36658-1f4b-41b3-aa0d-cf9b918d88bf, rgb(0, 99, 186)) -50%, var(--token-cd811638-c7a7-467a-a0d6-438332270fd5, rgb(0, 1, 3)) 150%)",
							borderBottomLeftRadius: 8,
							borderBottomRightRadius: 8,
							borderTopLeftRadius: 8,
							borderTopRightRadius: 8,
							opacity: 1,
							...style,
						}}
						variants={{
							"bigSzDPVI-hover": {
								opacity: 1,
							},
							"bigSzDPVI-pressed": {
								opacity: 0.6,
							},
							DiAEzRCvm: {
								opacity: 1,
							},
							viRNVuZth: {
								background:
									"linear-gradient(180deg, var(--token-2a73921c-5481-48e7-b529-9fb2de91ae3d, rgb(255, 34, 68)) -50%, var(--token-cd811638-c7a7-467a-a0d6-438332270fd5, rgb(0, 1, 3)) 150%)",
								opacity: 1,
							},
							Zte21atJt: {
								opacity: 0.5,
							},
						}}
						{...addPropertyOverrides(
							{
								"bigSzDPVI-hover": {
									"data-framer-name": void 0,
								},
								"bigSzDPVI-pressed": {
									"data-framer-name": void 0,
								},
								DiAEzRCvm: {
									"data-framer-name": "Success",
								},
								MT1LFcdyy: {
									"data-framer-name": "Loading",
								},
								viRNVuZth: {
									"data-framer-name": "Error",
								},
								Zte21atJt: {
									"data-framer-name": "Disabled",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						{isDisplayed() && (
							<motion.div
								className={"framer-1fw79lw"}
								data-framer-name={"Text"}
								layoutDependency={layoutDependency}
								layoutId={"PrYnER6xk"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-18dlqsw"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"Td_i5WLpH"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
										filter: "blur(0px)",
										WebkitFilter: "blur(0px)",
									}}
									variants={{
										"bigSzDPVI-hover": {
											filter: "blur(5px)",
											WebkitFilter: "blur(5px)",
										},
										"bigSzDPVI-pressed": {
											filter: "blur(5px)",
											WebkitFilter: "blur(5px)",
										},
										viRNVuZth: {
											"--extracted-r6o4lv":
												"var(--token-9d9c37d5-31f4-4564-b2ab-c0d257f64cbd, rgb(250, 250, 250))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											"bigSzDPVI-hover": {
												transformTemplate: transformTemplate1,
											},
											"bigSzDPVI-pressed": {
												transformTemplate: transformTemplate1,
											},
											DiAEzRCvm: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-5xfrwz"}
															data-styles-preset={"ruLAtCqcd"}
														>
															{"Thank you"}
														</motion.p>
													</React.Fragment>
												),
											},
											viRNVuZth: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-5xfrwz"}
															data-styles-preset={"ruLAtCqcd"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-9d9c37d5-31f4-4564-b2ab-c0d257f64cbd, rgb(250, 250, 250)))",
															}}
														>
															{"Something went wrong"}
														</motion.p>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-5xfrwz"}
											data-styles-preset={"ruLAtCqcd"}
										>
											{"Submit"}
										</motion.p>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1k5chh"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"gcu3jouQf"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
										filter: "blur(5px)",
										WebkitFilter: "blur(5px)",
									}}
									transformTemplate={transformTemplate1}
									variants={{
										"bigSzDPVI-hover": {
											filter: "blur(0px)",
											WebkitFilter: "blur(0px)",
										},
										"bigSzDPVI-pressed": {
											filter: "blur(0px)",
											WebkitFilter: "blur(0px)",
										},
										DiAEzRCvm: {
											"--extracted-r6o4lv": "rgb(255, 255, 255)",
										},
										viRNVuZth: {
											"--extracted-r6o4lv": "rgb(255, 34, 68)",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											"bigSzDPVI-hover": {
												transformTemplate: void 0,
											},
											"bigSzDPVI-pressed": {
												transformTemplate: void 0,
											},
											DiAEzRCvm: {
												children: (
													<React.Fragment>
														<motion.p
															style={{
																"--font-selector": "SW50ZXItU2VtaUJvbGQ=",
																"--framer-font-size": "14px",
																"--framer-font-weight": "600",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, rgb(255, 255, 255))",
															}}
														>
															{"Thank you"}
														</motion.p>
													</React.Fragment>
												),
												fonts: ["Inter-SemiBold"],
											},
											viRNVuZth: {
												children: (
													<React.Fragment>
														<motion.p
															style={{
																"--font-selector": "SW50ZXItU2VtaUJvbGQ=",
																"--framer-font-size": "14px",
																"--framer-font-weight": "600",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, rgb(255, 34, 68))",
															}}
														>
															{"Something went wrong"}
														</motion.p>
													</React.Fragment>
												),
												fonts: ["Inter-SemiBold"],
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-5xfrwz"}
											data-styles-preset={"ruLAtCqcd"}
										>
											{"Submit"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						)}
						{isDisplayed1() && (
							<motion.div
								className={"framer-157j5xw"}
								data-framer-name={"Spinner"}
								layoutDependency={layoutDependency}
								layoutId={"yTU0TwHog"}
								style={{
									mask: "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg?width=20&height=20') alpha no-repeat center / cover add",
									WebkitMask:
										"url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg?width=20&height=20') alpha no-repeat center / cover add",
								}}
							>
								<MotionDivWithFX
									__framer__loop={animation}
									__framer__loopEffectEnabled={true}
									__framer__loopRepeatDelay={0}
									__framer__loopRepeatType={"loop"}
									__framer__loopTransition={transition2}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									className={"framer-enainu"}
									data-framer-name={"Conic"}
									layoutDependency={layoutDependency}
									layoutId={"DNmxYHrLI"}
									style={{
										background:
											"conic-gradient(from 180deg at 50% 50%, rgb(68, 204, 255) 0deg, rgb(68, 204, 255) 360deg)",
										backgroundColor: "rgb(68, 204, 255)",
										mask: "none",
										WebkitMask: "none",
									}}
									variants={{
										MT1LFcdyy: {
											background:
												"conic-gradient(from 0deg at 50% 50%, rgba(255, 255, 255, 0) 7.208614864864882deg, rgb(255, 255, 255) 342deg)",
											backgroundColor: "rgba(0, 0, 0, 0)",
											mask: "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg?width=20&height=20') alpha no-repeat center / cover add",
											WebkitMask:
												"url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg?width=20&height=20') alpha no-repeat center / cover add",
										},
									}}
								>
									<motion.div
										className={"framer-183xvi9"}
										data-framer-name={"Rounding"}
										layoutDependency={layoutDependency}
										layoutId={"RHTpSySD6"}
										style={{
											backgroundColor: "rgb(255, 255, 255)",
											borderBottomLeftRadius: 1,
											borderBottomRightRadius: 1,
											borderTopLeftRadius: 1,
											borderTopRightRadius: 1,
										}}
										transformTemplate={transformTemplate1}
									/>
								</MotionDivWithFX>
							</motion.div>
						)}
					</motion.button>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-0e1zl.framer-1yp7q3k, .framer-0e1zl .framer-1yp7q3k { display: block; }",
	".framer-0e1zl.framer-1hshbsm { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 40px; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 240px; will-change: var(--framer-will-change-override, transform); }",
	".framer-0e1zl .framer-1fw79lw { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-0e1zl .framer-18dlqsw { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }",
	".framer-0e1zl .framer-1k5chh { -webkit-user-select: none; bottom: -39px; flex: none; height: auto; left: 50%; position: absolute; user-select: none; white-space: pre; width: auto; z-index: 1; }",
	".framer-0e1zl .framer-157j5xw { aspect-ratio: 1 / 1; flex: none; gap: 10px; height: var(--framer-aspect-ratio-supported, 20px); overflow: hidden; position: relative; width: 20px; }",
	".framer-0e1zl .framer-enainu { bottom: 0px; flex: none; left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; }",
	".framer-0e1zl .framer-183xvi9 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 2px); left: 50%; overflow: visible; position: absolute; top: 0px; width: 2px; }",
	".framer-0e1zl.framer-v-ry0bo2.framer-1hshbsm, .framer-0e1zl.framer-v-1rok438.framer-1hshbsm, .framer-0e1zl.framer-v-19dga47.framer-1hshbsm, .framer-0e1zl.framer-v-1e6fem1.framer-1hshbsm { cursor: unset; }",
	".framer-0e1zl.framer-v-ry0bo2 .framer-enainu { overflow: hidden; }",
	".framer-0e1zl.framer-v-1hshbsm.hover .framer-18dlqsw, .framer-0e1zl.framer-v-1hshbsm.pressed .framer-18dlqsw { left: 50%; position: absolute; top: -40px; z-index: 1; }",
	".framer-0e1zl.framer-v-1hshbsm.hover .framer-1k5chh, .framer-0e1zl.framer-v-1hshbsm.pressed .framer-1k5chh { bottom: unset; left: unset; position: relative; }",
	...css,
];
var FramerwnBKlpzlR = withCSS(Component, css2, "framer-0e1zl");
var stdin_default = FramerwnBKlpzlR;
FramerwnBKlpzlR.displayName = "Form Button";
FramerwnBKlpzlR.defaultProps = {
	height: 40,
	width: 240,
};
addPropertyControls(FramerwnBKlpzlR, {
	variant: {
		options: ["bigSzDPVI", "MT1LFcdyy", "Zte21atJt", "DiAEzRCvm", "viRNVuZth"],
		optionTitles: ["Default", "Loading", "Disabled", "Success", "Error"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerwnBKlpzlR,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/hyOgCu0Xnghbimh0pE8QTvtt2AU.woff2",
					weight: "600",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/NeGmSOXrPBfEFIy5YZeHq17LEDA.woff2",
					weight: "600",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/oYaAX5himiTPYuN8vLWnqBbfD2s.woff2",
					weight: "600",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/lEJLP4R0yuCaMCjSXYHtJw72M.woff2",
					weight: "600",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/cRJyLNuTJR5jbyKzGi33wU9cqIQ.woff2",
					weight: "600",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/yDtI2UI8XcEg1W2je9XPN3Noo.woff2",
					weight: "600",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/A0Wcc7NgXMjUuFdquHDrIZpzZw0.woff2",
					weight: "600",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:form-button
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "bigSzDPVI",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5af1700726b89e1359bd903da3e469ba956b8fc7e56af575f49bcf468e7d9c62"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FormButtonFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5af1700726b89e1359bd903da3e469ba956b8fc7e56af575f49bcf468e7d9c62"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var form_button_default = ComponentWithRoot;
export { form_button_default as default };
