// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5af1700726b89e13 "Cliplab Studio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | ' Phone - Close' | 'Phone - Open' // Variant
 * padding?: any // Padding
}} Props

 */
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-ZOSDNJUM.js";
import { className, css, fonts } from "./chunks/chunk-NORUQDUQ.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-AAR72SIM.js";
import { routes } from "./chunks/chunk-2NVZ5JSA.js";

// virtual:header
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/d1PDTeMiSjdCUAwFSTzM/FckmDYIzGkSGEcRsTQHH/dLL2yoT7l.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx as cx2,
	getFonts,
	getFontsFromSharedStyle as getFontsFromSharedStyle2,
	Link as Link2,
	ResolveLinks,
	RichText as RichText2,
	SmartComponentScopedContainer,
	useActiveVariantCallback as useActiveVariantCallback2,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useRouter,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
	withFX,
	withOptimizedAppearEffect,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/8UdR0MMZFuJc3G0LuRhx/mWcvfrBOp2hdEBgYtt2G/jhdLS8r4u.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Link,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var enabledGestures = {
	VJ9ToqxFT: {
		hover: true,
	},
};
var cycleOrder = ["VJ9ToqxFT", "RorVuIOAF"];
var serializationHash = "framer-lEaXF";
var variantClassNames = {
	RorVuIOAF: "framer-v-s808wi",
	VJ9ToqxFT: "framer-v-iazkme",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 80,
	delay: 0,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"M/S": "RorVuIOAF",
	L: "VJ9ToqxFT",
};
var getProps = ({ click, height, id, link, title, width, ...props }) => {
	return {
		...props,
		DfBSFdlxJ: link ?? props.DfBSFdlxJ,
		I162RSKBW: title ?? props.I162RSKBW ?? "Cliplab Studio",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "VJ9ToqxFT",
		xydoHK1Ri: click ?? props.xydoHK1Ri,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		I162RSKBW: I162RSKBW2,
		xydoHK1Ri: xydoHK1Ri2,
		DfBSFdlxJ: DfBSFdlxJ2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "VJ9ToqxFT",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap1rwn1pb = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (xydoHK1Ri2) {
			const res = await xydoHK1Ri2(...args);
			if (res === false) return false;
		}
	});
	const sharedStyleClassNames = [className3, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={DfBSFdlxJ2}
						motionChild={true}
						nodeId={"VJ9ToqxFT"}
						openInNewTab={false}
						scopeId={"jhdLS8r4u"}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-iazkme", className4, classNames)} framer-19eg31n`}
							data-framer-name={"L"}
							data-highlight={true}
							layoutDependency={layoutDependency}
							layoutId={"VJ9ToqxFT"}
							onTap={onTap1rwn1pb}
							ref={refBinding}
							style={{
								...style,
							}}
							{...addPropertyOverrides(
								{
									"VJ9ToqxFT-hover": {
										"data-framer-name": void 0,
									},
									RorVuIOAF: {
										"data-framer-name": "M/S",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-jwxhhf"}
								data-framer-name={"Text"}
								layoutDependency={layoutDependency}
								layoutId={"FB4nP6M9p"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-x6eaiy"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"QPt_gsliX"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-9d9c37d5-31f4-4564-b2ab-c0d257f64cbd, rgb(250, 250, 250))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
										filter: "blur(0px)",
										WebkitFilter: "blur(0px)",
									}}
									text={I162RSKBW2}
									variants={{
										"VJ9ToqxFT-hover": {
											filter: "blur(5px)",
											WebkitFilter: "blur(5px)",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											"VJ9ToqxFT-hover": {
												transformTemplate: transformTemplate1,
											},
											RorVuIOAF: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-1ozhwx8"}
															data-styles-preset={"BsEnbfNw3"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-9d9c37d5-31f4-4564-b2ab-c0d257f64cbd, rgb(250, 250, 250)))",
															}}
														>
															{"Cliplab Studio"}
														</motion.p>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1h481q3"}
											data-styles-preset={"uWgmT59JL"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-9d9c37d5-31f4-4564-b2ab-c0d257f64cbd, rgb(250, 250, 250)))",
											}}
										>
											{"Cliplab Studio"}
										</motion.p>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-n9dbff"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"xfa0f27Li"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-9d9c37d5-31f4-4564-b2ab-c0d257f64cbd, rgb(250, 250, 250))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
										filter: "blur(5px)",
										WebkitFilter: "blur(5px)",
									}}
									text={I162RSKBW2}
									variants={{
										"VJ9ToqxFT-hover": {
											filter: "blur(0px)",
											WebkitFilter: "blur(0px)",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											RorVuIOAF: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-1ozhwx8"}
															data-styles-preset={"BsEnbfNw3"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-9d9c37d5-31f4-4564-b2ab-c0d257f64cbd, rgb(250, 250, 250)))",
															}}
														>
															{"Cliplab Studio"}
														</motion.p>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1h481q3"}
											data-styles-preset={"uWgmT59JL"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-9d9c37d5-31f4-4564-b2ab-c0d257f64cbd, rgb(250, 250, 250)))",
											}}
										>
											{"Cliplab Studio"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-lEaXF.framer-19eg31n, .framer-lEaXF .framer-19eg31n { display: block; }",
	".framer-lEaXF.framer-iazkme { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; text-decoration: none; width: min-content; }",
	".framer-lEaXF .framer-jwxhhf { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-lEaXF .framer-x6eaiy { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-lEaXF .framer-n9dbff { bottom: -30px; flex: none; height: auto; left: 0px; position: absolute; white-space: pre; width: auto; z-index: 1; }",
	".framer-lEaXF.framer-v-iazkme.hover .framer-x6eaiy { left: 50%; position: absolute; top: -30px; z-index: 1; }",
	".framer-lEaXF.framer-v-iazkme.hover .framer-n9dbff { bottom: unset; left: unset; position: relative; }",
	...css3,
	...css,
];
var FramerjhdLS8r4u = withCSS(Component, css4, "framer-lEaXF");
var stdin_default = FramerjhdLS8r4u;
FramerjhdLS8r4u.displayName = "Nav link";
FramerjhdLS8r4u.defaultProps = {
	height: 20,
	width: 92,
};
addPropertyControls(FramerjhdLS8r4u, {
	variant: {
		options: ["VJ9ToqxFT", "RorVuIOAF"],
		optionTitles: ["L", "M/S"],
		title: "Variant",
		type: ControlType.Enum,
	},
	I162RSKBW: {
		defaultValue: "Cliplab Studio",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	xydoHK1Ri: {
		title: "Click",
		type: ControlType.EventHandler,
	},
	DfBSFdlxJ: {
		title: "Link",
		type: ControlType.Link,
	},
});
addFonts(
	FramerjhdLS8r4u,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/d1PDTeMiSjdCUAwFSTzM/FckmDYIzGkSGEcRsTQHH/dLL2yoT7l.js
var NavLinkFonts = getFonts(stdin_default);
var MotionDivWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(motion2.div),
);
var cycleOrder2 = ["OQ2l_6did", "Z7SefzVDA", "kpJKbebJv"];
var serializationHash2 = "framer-OWg9o";
var variantClassNames2 = {
	kpJKbebJv: "framer-v-1uo0vsr",
	OQ2l_6did: "framer-v-1814thd",
	Z7SefzVDA: "framer-v-gawdd6",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transition2 = {
	damping: 80,
	delay: 0,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var numberToPixelString = (value) => {
	if (typeof value !== "number") return value;
	if (!Number.isFinite(value)) return void 0;
	return Math.max(0, value) + "px";
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 20,
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap2 = {
	" Phone - Close": "Z7SefzVDA",
	"Phone - Open": "kpJKbebJv",
	Desktop: "OQ2l_6did",
};
var getProps2 = ({ height, id, padding, width, ...props }) => {
	return {
		...props,
		oVdjoVMel: padding ?? props.oVdjoVMel ?? "0px 40px 0px 40px",
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "OQ2l_6did",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		oVdjoVMel: oVdjoVMel2,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "OQ2l_6did",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback2(baseVariant);
	const xydoHK1Rinv061f = activeVariantCallback(async (...args) => {
		setVariant("kpJKbebJv");
	});
	const xydoHK1Ri15xgz1s = activeVariantCallback(async (...args) => {
		setVariant("Z7SefzVDA");
	});
	const onTap15xgz1s = activeVariantCallback(async (...args) => {
		setVariant("Z7SefzVDA");
	});
	const sharedStyleClassNames = [className2];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (["Z7SefzVDA", "kpJKbebJv"].includes(baseVariant)) return true;
		return false;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "Z7SefzVDA") return true;
		return false;
	};
	const isDisplayed2 = () => {
		if (baseVariant === "kpJKbebJv") return true;
		return false;
	};
	const isDisplayed3 = () => {
		if (baseVariant === "Z7SefzVDA") return false;
		return true;
	};
	const router = useRouter();
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2
					value={transition12}
					{...addPropertyOverrides2(
						{
							Z7SefzVDA: {
								value: transition2,
							},
						},
						baseVariant,
						gestureVariant,
					)}
				>
					<motion2.nav
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-1814thd",
							className4,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"OQ2l_6did"}
						ref={refBinding}
						style={{
							backdropFilter: "blur(5px)",
							backgroundColor:
								"var(--token-efc840ff-64db-4d68-b4f9-ffd23b298cd4, rgba(255, 255, 255, 0.05))",
							WebkitBackdropFilter: "blur(5px)",
							...style,
						}}
						{...addPropertyOverrides2(
							{
								kpJKbebJv: {
									"data-framer-name": "Phone - Open",
								},
								Z7SefzVDA: {
									"data-framer-name": " Phone - Close",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							className={"framer-q6ivqc"}
							data-framer-name={"Content"}
							layoutDependency={layoutDependency}
							layoutId={"ki5pYDcVQ"}
							style={{
								"--ilmci2": numberToPixelString(oVdjoVMel2),
							}}
						>
							<motion2.div
								className={"framer-1l2t1jv"}
								data-framer-name={"Name"}
								layoutDependency={layoutDependency}
								layoutId={"fj6LgVLc8"}
							>
								<Link2
									href={{
										webPageId: "augiA20Il",
									}}
									motionChild={true}
									nodeId={"Sq6ne7IBI"}
									openInNewTab={false}
									scopeId={"dLL2yoT7l"}
								>
									<motion2.a
										className={"framer-16o70oc framer-y8ixq0"}
										data-framer-name={"Log Wrapper"}
										layoutDependency={layoutDependency}
										layoutId={"Sq6ne7IBI"}
									>
										<RichText2
											__fromCanvasComponent={true}
											className={"framer-ttb92c"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"rWWvHp5GI"}
											style={{
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React2.Fragment>
												<motion2.h4
													className={"framer-styles-preset-1sn04vz"}
													data-styles-preset={"PIyXyiWAX"}
													dir={"auto"}
												>
													{"Cliplab Studio"}
												</motion2.h4>
											</React2.Fragment>
										</RichText2>
									</motion2.a>
								</Link2>
								{isDisplayed() && (
									<motion2.div
										className={"framer-162t1lm"}
										data-framer-name={"Hamburger"}
										layoutDependency={layoutDependency}
										layoutId={"Hd2d0ZDJV"}
									>
										{isDisplayed1() && (
											<ComponentViewportProvider
												{...addPropertyOverrides2(
													{
														Z7SefzVDA: {
															height: 20,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<SmartComponentScopedContainer
													className={"framer-q9v62c-container"}
													data-framer-name={"Menu"}
													layoutDependency={layoutDependency}
													layoutId={"DgJdr2YOb-container"}
													name={"Menu"}
													nodeId={"DgJdr2YOb"}
													rendersWithMotion={true}
													scopeId={"dLL2yoT7l"}
												>
													{_jsx2(stdin_default, {
														height: "100%",
														I162RSKBW: "Menu",
														id: "DgJdr2YOb",
														layoutId: "DgJdr2YOb",
														name: "Menu",
														variant: matchVariant("VJ9ToqxFT"),
														width: "100%",
														...addPropertyOverrides2(
															{
																Z7SefzVDA: {
																	variant: matchVariant("RorVuIOAF"),
																	xydoHK1Ri: xydoHK1Rinv061f,
																},
															},
															baseVariant,
															gestureVariant,
														),
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
										{isDisplayed2() && (
											<ComponentViewportProvider
												{...addPropertyOverrides2(
													{
														kpJKbebJv: {
															height: 20,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<SmartComponentScopedContainer
													className={"framer-1qr5inq-container"}
													data-framer-name={"Close"}
													layoutDependency={layoutDependency}
													layoutId={"ySjcKh_4f-container"}
													name={"Close"}
													nodeId={"ySjcKh_4f"}
													rendersWithMotion={true}
													scopeId={"dLL2yoT7l"}
												>
													{_jsx2(stdin_default, {
														height: "100%",
														I162RSKBW: "Close",
														id: "ySjcKh_4f",
														layoutId: "ySjcKh_4f",
														name: "Close",
														variant: matchVariant("RorVuIOAF"),
														width: "100%",
														xydoHK1Ri: xydoHK1Ri15xgz1s,
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
									</motion2.div>
								)}
							</motion2.div>
							{isDisplayed3() && (
								<MotionDivWithFXWithOptimizedAppearEffect
									className={"framer-wnsj2z"}
									data-framer-appear-id={"wnsj2z"}
									data-framer-name={"Links"}
									layoutDependency={layoutDependency}
									layoutId={"XWrLMRJzH"}
									style={{
										"--border-bottom-width": "0px",
										"--border-color": "rgba(0, 0, 0, 0)",
										"--border-left-width": "0px",
										"--border-right-width": "0px",
										"--border-style": "solid",
										"--border-top-width": "0px",
										backdropFilter: "none",
										background: "rgba(0, 0, 0, 0)",
										borderBottomLeftRadius: 0,
										borderBottomRightRadius: 0,
										borderTopLeftRadius: 0,
										borderTopRightRadius: 0,
										WebkitBackdropFilter: "none",
									}}
									variants={{
										kpJKbebJv: {
											"--border-bottom-width": "1px",
											"--border-color":
												"var(--token-cb2206d2-93ba-4bbf-8a99-2fb6eb742230, rgba(255, 255, 255, 0.1))",
											"--border-left-width": "1px",
											"--border-right-width": "1px",
											"--border-style": "solid",
											"--border-top-width": "1px",
											backdropFilter: "blur(5px)",
											background:
												"linear-gradient(180deg, rgb(0, 99, 186) 0%, var(--token-cd811638-c7a7-467a-a0d6-438332270fd5, rgb(0, 1, 3)) 100%)",
											borderBottomLeftRadius: 8,
											borderBottomRightRadius: 8,
											borderTopLeftRadius: 8,
											borderTopRightRadius: 8,
											WebkitBackdropFilter: "blur(5px)",
										},
									}}
									{...addPropertyOverrides2(
										{
											kpJKbebJv: {
												__perspectiveFX: false,
												__smartComponentFX: true,
												__targetOpacity: 1,
												"data-border": true,
												animate: animation,
												initial: animation1,
												optimized: true,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<motion2.div
										className={"framer-1o6wvly"}
										data-framer-name={"Why Chose Us"}
										layoutDependency={layoutDependency}
										layoutId={"kZswm2LZN"}
										{...addPropertyOverrides2(
											{
												kpJKbebJv: {
													"data-highlight": true,
													onTap: onTap15xgz1s,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<ResolveLinks
											links={[
												{
													href: {
														hash: ":Zynnh5tjQ",
														webPageId: "augiA20Il",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														hash: ":Zynnh5tjQ",
														webPageId: "augiA20Il",
													},
													implicitPathVariables: void 0,
												},
											]}
										>
											{(resolvedLinks) => (
												<ComponentViewportProvider
													height={20}
													{...addPropertyOverrides2(
														{
															kpJKbebJv: {
																height: 22,
															},
														},
														baseVariant,
														gestureVariant,
													)}
												>
													<SmartComponentScopedContainer
														className={"framer-1od3bkp-container"}
														layoutDependency={layoutDependency}
														layoutId={"Cdyon5Ynu-container"}
														nodeId={"Cdyon5Ynu"}
														rendersWithMotion={true}
														scopeId={"dLL2yoT7l"}
													>
														{_jsx2(stdin_default, {
															DfBSFdlxJ: resolvedLinks[0],
															height: "100%",
															I162RSKBW: "Why Chose Us?",
															id: "Cdyon5Ynu",
															layoutId: "Cdyon5Ynu",
															variant: matchVariant("VJ9ToqxFT"),
															width: "100%",
															...addPropertyOverrides2(
																{
																	kpJKbebJv: {
																		DfBSFdlxJ: resolvedLinks[1],
																		style: {
																			height: "100%",
																		},
																		variant: matchVariant("RorVuIOAF"),
																	},
																},
																baseVariant,
																gestureVariant,
															),
														})}
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>
											)}
										</ResolveLinks>
									</motion2.div>
									<motion2.div
										className={"framer-1d0u1fr"}
										data-framer-name={"Curriculum"}
										layoutDependency={layoutDependency}
										layoutId={"cwwcyODcB"}
										{...addPropertyOverrides2(
											{
												kpJKbebJv: {
													"data-highlight": true,
													onTap: onTap15xgz1s,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<ResolveLinks
											links={[
												{
													href: {
														hash: ":gC25IqaPd",
														webPageId: "augiA20Il",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														hash: ":gC25IqaPd",
														webPageId: "augiA20Il",
													},
													implicitPathVariables: void 0,
												},
											]}
										>
											{(resolvedLinks1) => (
												<ComponentViewportProvider
													height={20}
													{...addPropertyOverrides2(
														{
															kpJKbebJv: {
																height: 23,
															},
														},
														baseVariant,
														gestureVariant,
													)}
												>
													<SmartComponentScopedContainer
														className={"framer-utr5br-container"}
														layoutDependency={layoutDependency}
														layoutId={"VpvtIMxFc-container"}
														nodeId={"VpvtIMxFc"}
														rendersWithMotion={true}
														scopeId={"dLL2yoT7l"}
													>
														{_jsx2(stdin_default, {
															DfBSFdlxJ: resolvedLinks1[0],
															height: "100%",
															I162RSKBW: "Curriculum",
															id: "VpvtIMxFc",
															layoutId: "VpvtIMxFc",
															variant: matchVariant("VJ9ToqxFT"),
															width: "100%",
															...addPropertyOverrides2(
																{
																	kpJKbebJv: {
																		DfBSFdlxJ: resolvedLinks1[1],
																		style: {
																			height: "100%",
																		},
																		variant: matchVariant("RorVuIOAF"),
																	},
																},
																baseVariant,
																gestureVariant,
															),
														})}
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>
											)}
										</ResolveLinks>
									</motion2.div>
									<motion2.div
										className={"framer-ky3g1q"}
										data-framer-name={"Pricing"}
										layoutDependency={layoutDependency}
										layoutId={"VxeDnV_3Z"}
										{...addPropertyOverrides2(
											{
												kpJKbebJv: {
													"data-highlight": true,
													onTap: onTap15xgz1s,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<ResolveLinks
											links={[
												{
													href: {
														hash: ":MbpgP1BCc",
														webPageId: "augiA20Il",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														hash: ":MbpgP1BCc",
														webPageId: "augiA20Il",
													},
													implicitPathVariables: void 0,
												},
											]}
										>
											{(resolvedLinks2) => (
												<ComponentViewportProvider
													height={20}
													{...addPropertyOverrides2(
														{
															kpJKbebJv: {
																height: 22,
															},
														},
														baseVariant,
														gestureVariant,
													)}
												>
													<SmartComponentScopedContainer
														className={"framer-okptnm-container"}
														layoutDependency={layoutDependency}
														layoutId={"WSnz2bY1B-container"}
														nodeId={"WSnz2bY1B"}
														rendersWithMotion={true}
														scopeId={"dLL2yoT7l"}
													>
														{_jsx2(stdin_default, {
															DfBSFdlxJ: resolvedLinks2[0],
															height: "100%",
															I162RSKBW: "Pricing",
															id: "WSnz2bY1B",
															layoutId: "WSnz2bY1B",
															variant: matchVariant("VJ9ToqxFT"),
															width: "100%",
															...addPropertyOverrides2(
																{
																	kpJKbebJv: {
																		DfBSFdlxJ: resolvedLinks2[1],
																		style: {
																			height: "100%",
																		},
																		variant: matchVariant("RorVuIOAF"),
																	},
																},
																baseVariant,
																gestureVariant,
															),
														})}
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>
											)}
										</ResolveLinks>
									</motion2.div>
									<motion2.div
										className={"framer-1t9yv6v"}
										data-framer-name={"Contact"}
										layoutDependency={layoutDependency}
										layoutId={"YOfi4SJfl"}
										{...addPropertyOverrides2(
											{
												kpJKbebJv: {
													"data-highlight": true,
													onTap: onTap15xgz1s,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<ResolveLinks
											links={[
												{
													href: {
														webPageId: "rDs2VehRz",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														webPageId: "rDs2VehRz",
													},
													implicitPathVariables: void 0,
												},
											]}
										>
											{(resolvedLinks3) => (
												<ComponentViewportProvider
													height={20}
													{...addPropertyOverrides2(
														{
															kpJKbebJv: {
																height: 23,
															},
														},
														baseVariant,
														gestureVariant,
													)}
												>
													<SmartComponentScopedContainer
														className={"framer-ek1gxt-container"}
														layoutDependency={layoutDependency}
														layoutId={"dCO_3hl47-container"}
														nodeId={"dCO_3hl47"}
														rendersWithMotion={true}
														scopeId={"dLL2yoT7l"}
													>
														{_jsx2(stdin_default, {
															DfBSFdlxJ: resolvedLinks3[0],
															height: "100%",
															I162RSKBW: "Contact",
															id: "dCO_3hl47",
															layoutId: "dCO_3hl47",
															variant: matchVariant("VJ9ToqxFT"),
															width: "100%",
															...addPropertyOverrides2(
																{
																	kpJKbebJv: {
																		DfBSFdlxJ: resolvedLinks3[1],
																		style: {
																			height: "100%",
																		},
																		variant: matchVariant("RorVuIOAF"),
																	},
																},
																baseVariant,
																gestureVariant,
															),
														})}
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>
											)}
										</ResolveLinks>
									</motion2.div>
								</MotionDivWithFXWithOptimizedAppearEffect>
							)}
						</motion2.div>
					</motion2.nav>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css5 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-OWg9o.framer-y8ixq0, .framer-OWg9o .framer-y8ixq0 { display: block; }",
	".framer-OWg9o.framer-1814thd { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 16px 0px 16px 0px; position: relative; width: 1200px; }",
	".framer-OWg9o .framer-q6ivqc { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; max-width: 1400px; overflow: visible; padding: var(--ilmci2); position: relative; width: 1px; }",
	".framer-OWg9o .framer-1l2t1jv { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-OWg9o .framer-16o70oc { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: 1px; }",
	".framer-OWg9o .framer-ttb92c { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-OWg9o .framer-162t1lm { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; min-height: 22px; min-width: 42px; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-OWg9o .framer-q9v62c-container, .framer-OWg9o .framer-1qr5inq-container, .framer-OWg9o .framer-1od3bkp-container, .framer-OWg9o .framer-utr5br-container, .framer-OWg9o .framer-okptnm-container, .framer-OWg9o .framer-ek1gxt-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-OWg9o .framer-wnsj2z { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 18px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: min-content; }",
	".framer-OWg9o .framer-1o6wvly, .framer-OWg9o .framer-1d0u1fr, .framer-OWg9o .framer-ky3g1q, .framer-OWg9o .framer-1t9yv6v { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-OWg9o.framer-v-gawdd6.framer-1814thd { align-content: flex-start; align-items: flex-start; flex-direction: column; justify-content: flex-start; width: 390px; }",
	".framer-OWg9o.framer-v-gawdd6 .framer-q6ivqc { flex: none; width: 100%; }",
	".framer-OWg9o.framer-v-gawdd6 .framer-162t1lm, .framer-OWg9o.framer-v-1uo0vsr .framer-162t1lm { min-height: unset; min-width: unset; }",
	".framer-OWg9o.framer-v-1uo0vsr.framer-1814thd { align-content: flex-end; align-items: flex-end; flex-direction: column; gap: 50px; justify-content: flex-start; overflow: visible; width: 390px; }",
	".framer-OWg9o.framer-v-1uo0vsr .framer-q6ivqc { align-content: flex-start; align-items: flex-start; flex: none; width: 100%; }",
	".framer-OWg9o.framer-v-1uo0vsr .framer-wnsj2z { align-content: flex-start; align-items: flex-start; bottom: -227px; flex-direction: column; gap: 24px; padding: 16px 24px 16px 24px; position: absolute; right: 20px; will-change: var(--framer-will-change-override, transform); z-index: 3; }",
	".framer-OWg9o.framer-v-1uo0vsr .framer-1o6wvly, .framer-OWg9o.framer-v-1uo0vsr .framer-1d0u1fr, .framer-OWg9o.framer-v-1uo0vsr .framer-ky3g1q, .framer-OWg9o.framer-v-1uo0vsr .framer-1t9yv6v { cursor: pointer; }",
	".framer-OWg9o.framer-v-1uo0vsr .framer-1od3bkp-container, .framer-OWg9o.framer-v-1uo0vsr .framer-okptnm-container { height: 22px; }",
	".framer-OWg9o.framer-v-1uo0vsr .framer-utr5br-container, .framer-OWg9o.framer-v-1uo0vsr .framer-ek1gxt-container { height: 23px; }",
	...css2,
	'.framer-OWg9o[data-border="true"]::after, .framer-OWg9o [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramerdLL2yoT7l = withCSS2(Component2, css5, "framer-OWg9o");
var stdin_default2 = FramerdLL2yoT7l;
FramerdLL2yoT7l.displayName = "Header";
FramerdLL2yoT7l.defaultProps = {
	height: 58,
	width: 1200,
};
addPropertyControls2(FramerdLL2yoT7l, {
	variant: {
		options: ["OQ2l_6did", "Z7SefzVDA", "kpJKbebJv"],
		optionTitles: ["Desktop", " Phone - Close", "Phone - Open"],
		title: "Variant",
		type: ControlType2.Enum,
	},
	oVdjoVMel: {
		defaultValue: "0px 40px 0px 40px",
		title: "Padding",
		type: ControlType2.Padding,
	},
});
addFonts2(
	FramerdLL2yoT7l,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...NavLinkFonts,
		...getFontsFromSharedStyle2(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:header
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "Z7SefzVDA",
	xl: "OQ2l_6did",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5af1700726b89e1359bd903da3e469ba956b8fc7e56af575f49bcf468e7d9c62"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders HeaderFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5af1700726b89e1359bd903da3e469ba956b8fc7e56af575f49bcf468e7d9c62"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var header_default = ComponentWithRoot;
export { header_default as default };
