// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5af1700726b89e13 "Cliplab Studio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'L' | 'M' // Variant
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * name?: string // Name
 * designation?: string // Designation
 * bio?: string // Bio
 * xLink?: string // X Link
 * linkedInLink?: string // LinkedIn Link
 * instagramLink?: string // Instagram Link
}} Props

 */
import {
	stdin_default,
	stdin_default2 as stdin_default3,
	stdin_default3 as stdin_default4,
} from "./chunks/chunk-RTK3BYRW.js";
import { stdin_default as stdin_default2 } from "./chunks/chunk-PQK5NHI5.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-AAR72SIM.js";
import { className, css, fonts } from "./chunks/chunk-AN6VZTLK.js";
import { routes } from "./chunks/chunk-2NVZ5JSA.js";

// virtual:mentor-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/bbt5qCxcEyb2sitzS17t/gxckOjMySGZVGMcAUDjm/s5td2A0yO.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/t6QGWjd9hfWviL7i1ML6/FK2uPQDajtw8c14wyfxI/StrFP5FPP.js
import { fontStore } from "unframer";
fontStore.loadFonts(["GF;La Belle Aurore-regular"]);
var fonts3 = [
	{
		explicitInter: true,
		fonts: [
			{
				cssFamilyName: "La Belle Aurore",
				source: "google",
				style: "normal",
				uiFamilyName: "La Belle Aurore",
				url: "https://fonts.gstatic.com/s/labelleaurore/v23/RrQIbot8-mNYKnGNDkWlocovHeIIHueFNVmULg.woff2",
				weight: "400",
			},
		],
	},
];
var css3 = [
	'.framer-Idji0 .framer-styles-preset-1kvyzj4:not(.rich-text-wrapper), .framer-Idji0 .framer-styles-preset-1kvyzj4.rich-text-wrapper p { --framer-font-family: "La Belle Aurore", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 24px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-letter-spacing: 0em; --framer-line-height: 150%; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-a0b331ef-7085-4a1e-a4b5-0195668a9610, #d5ff00); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
];
var className3 = "framer-Idji0";

// /:https://framerusercontent.com/modules/bbt5qCxcEyb2sitzS17t/gxckOjMySGZVGMcAUDjm/s5td2A0yO.js
var SocialLinkFonts = getFonts(stdin_default4);
var cycleOrder = ["b4Zw4C4Bt", "MntQVnGNM"];
var serializationHash = "framer-eoEnB";
var variantClassNames = {
	b4Zw4C4Bt: "framer-v-1ca0prc",
	MntQVnGNM: "framer-v-ewi5nz",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	L: "b4Zw4C4Bt",
	M: "MntQVnGNM",
};
var getProps = ({
	bio,
	designation,
	height,
	id,
	image,
	instagramLink,
	linkedInLink,
	name1,
	width,
	xLink,
	...props
}) => {
	return {
		...props,
		BxTEWeXzC:
			bio ??
			props.BxTEWeXzC ??
			"Award-winning editor with over a decade of experience crafting commercials, documentaries, and social campaigns. He\u2019s collaborated with top-tier brands and creative teams worldwide, and now he\u2019s sharing every practical skill, workflow, and creative insight he\u2019s gained\u2014without holding anything back.",
		cI6i37jU1: image ??
			props.cI6i37jU1 ?? {
				alt: "Asian man with glasses in a creative workspace, surrounded by colorful abstract art and stationery on a cluttered desk.",
				pixelHeight: 4876,
				pixelWidth: 8668,
				positionX: "52.5%",
				positionY: "35.7%",
				src: "https://framerusercontent.com/images/1srWHUJqUVL8SmTzt5zFucmJWQ.jpg?width=8668&height=4876",
				srcSet:
					"https://framerusercontent.com/images/1srWHUJqUVL8SmTzt5zFucmJWQ.jpg?scale-down-to=512&width=8668&height=4876 512w,https://framerusercontent.com/images/1srWHUJqUVL8SmTzt5zFucmJWQ.jpg?scale-down-to=1024&width=8668&height=4876 1024w,https://framerusercontent.com/images/1srWHUJqUVL8SmTzt5zFucmJWQ.jpg?scale-down-to=2048&width=8668&height=4876 2048w,https://framerusercontent.com/images/1srWHUJqUVL8SmTzt5zFucmJWQ.jpg?scale-down-to=4096&width=8668&height=4876 4096w,https://framerusercontent.com/images/1srWHUJqUVL8SmTzt5zFucmJWQ.jpg?width=8668&height=4876 8668w",
			},
		f6p19kOhb: linkedInLink ?? props.f6p19kOhb,
		KC0kxLqKZ:
			designation ?? props.KC0kxLqKZ ?? "Senior Video Editor at Zenith",
		NIeT2WXix: name1 ?? props.NIeT2WXix ?? "Danial Cruze",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "b4Zw4C4Bt",
		WiAqS5pPk: instagramLink ?? props.WiAqS5pPk,
		YrwevER2x: xLink ?? props.YrwevER2x,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		cI6i37jU1: cI6i37jU12,
		NIeT2WXix: NIeT2WXix2,
		KC0kxLqKZ: KC0kxLqKZ2,
		BxTEWeXzC: BxTEWeXzC2,
		YrwevER2x: YrwevER2x2,
		f6p19kOhb: f6p19kOhb2,
		WiAqS5pPk: WiAqS5pPk2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "b4Zw4C4Bt",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className, className3];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1ca0prc",
							className4,
							classNames,
						)}
						data-border={true}
						data-framer-name={"L"}
						layoutDependency={layoutDependency}
						layoutId={"b4Zw4C4Bt"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-cb2206d2-93ba-4bbf-8a99-2fb6eb742230, rgba(255, 255, 255, 0.1))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							background:
								"linear-gradient(180deg, var(--token-efc840ff-64db-4d68-b4f9-ffd23b298cd4, rgba(255, 255, 255, 0.05)) 0%, var(--token-737547ea-dc46-45bd-ae2b-4977e3da045e, rgba(9, 0, 189, 0.05)) 100%)",
							borderBottomLeftRadius: 20,
							borderBottomRightRadius: 20,
							borderTopLeftRadius: 20,
							borderTopRightRadius: 20,
							...style,
						}}
						{...addPropertyOverrides(
							{
								MntQVnGNM: {
									"data-framer-name": "M",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1aohk02"}
							data-border={true}
							data-framer-name={"Image"}
							layoutDependency={layoutDependency}
							layoutId={"tQUIufcQq"}
							style={{
								"--border-bottom-width": "1px",
								"--border-color":
									"var(--token-efc840ff-64db-4d68-b4f9-ffd23b298cd4, rgba(255, 255, 255, 0.05))",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								borderBottomLeftRadius: 4,
								borderBottomRightRadius: 4,
								borderTopLeftRadius: 4,
								borderTopRightRadius: 4,
							}}
							variants={{
								MntQVnGNM: {
									borderBottomLeftRadius: 10,
									borderBottomRightRadius: 10,
									borderTopLeftRadius: 10,
									borderTopRightRadius: 10,
								},
							}}
						>
							<Image
								background={{
									alt: "Asian man with glasses in a creative workspace, surrounded by colorful abstract art and stationery on a cluttered desk.",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) + 16 + 0 + 8 + 0,
									),
									pixelHeight: 4876,
									pixelWidth: 8668,
									sizes: `calc(${componentViewport?.width || "100vw"} - 48px)`,
									...toResponsiveImage(cI6i37jU12),
								}}
								className={"framer-blyw7w"}
								data-framer-name={"Image"}
								layoutDependency={layoutDependency}
								layoutId={"KYiaDZbdL"}
								style={{
									borderBottomLeftRadius: 1,
									borderBottomRightRadius: 1,
									borderTopLeftRadius: 1,
									borderTopRightRadius: 1,
								}}
								variants={{
									MntQVnGNM: {
										borderBottomLeftRadius: 3,
										borderBottomRightRadius: 3,
										borderTopLeftRadius: 3,
										borderTopRightRadius: 3,
									},
								}}
								{...addPropertyOverrides(
									{
										MntQVnGNM: {
											background: {
												alt: "Asian man with glasses in a creative workspace, surrounded by colorful abstract art and stationery on a cluttered desk.",
												fit: "fill",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) + 8 + 0 + 8 + 0,
												),
												pixelHeight: 4876,
												pixelWidth: 8668,
												sizes: `calc(${componentViewport?.width || "100vw"} - 32px)`,
												...toResponsiveImage(cI6i37jU12),
											},
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
						</motion.div>
						<motion.div
							className={"framer-at3m90"}
							data-framer-name={"Text"}
							layoutDependency={layoutDependency}
							layoutId={"w0Zt8AR0a"}
						>
							<motion.div
								className={"framer-1a6ni0c"}
								data-framer-name={"Name Text"}
								layoutDependency={layoutDependency}
								layoutId={"zOKRbviep"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-5mo5so"}
									data-framer-name={"Danial Cruze"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"Jd0f47X2E"}
									style={{
										"--framer-paragraph-spacing": "0px",
									}}
									text={NIeT2WXix2}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h3
											className={"framer-styles-preset-1sn04vz"}
											data-styles-preset={"PIyXyiWAX"}
										>
											{"Danial Cruze"}
										</motion.h3>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-113ukxw"}
									data-framer-name={"Senior video Editor at Zenith"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"fU9gI2LFG"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-9d9c37d5-31f4-4564-b2ab-c0d257f64cbd, rgb(250, 250, 250))",
										"--framer-paragraph-spacing": "0px",
									}}
									text={KC0kxLqKZ2}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1ozhwx8"}
											data-styles-preset={"BsEnbfNw3"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-9d9c37d5-31f4-4564-b2ab-c0d257f64cbd, rgb(250, 250, 250)))",
											}}
										>
											{"Senior video Editor at Zenith"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1ympz40"}
								data-framer-name={
									"Award-winning editor with over a decade of experience creating commercials, documentaries, and social campaigns. He has collaborated with leading brands like Nike, Adobe, and Meta, and now he\u2019s sharing every practical skill, workflow, and creative insight he\u2019s gained\u2014without holding anything back."
								}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"RXQxjnqe1"}
								style={{
									"--framer-paragraph-spacing": "0px",
								}}
								text={BxTEWeXzC2}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1ozhwx8"}
										data-styles-preset={"BsEnbfNw3"}
									>
										{
											"Award-winning editor with over a decade of experience creating commercials, documentaries, and social campaigns. He has collaborated with leading brands like Nike, Adobe, and Meta, and now he\u2019s sharing every practical skill, workflow, and creative insight he\u2019s gained without holding anything back."
										}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
						<motion.div
							className={"framer-1kgo82v"}
							data-framer-name={"Devider"}
							layoutDependency={layoutDependency}
							layoutId={"zgbEQWfgT"}
							style={{
								backgroundColor:
									"var(--token-cb2206d2-93ba-4bbf-8a99-2fb6eb742230, rgba(255, 255, 255, 0.1))",
								borderBottomLeftRadius: 143,
								borderBottomRightRadius: 143,
								borderTopLeftRadius: 143,
								borderTopRightRadius: 143,
							}}
						/>
						<motion.div
							className={"framer-3emb9"}
							data-framer-name={"Socials"}
							layoutDependency={layoutDependency}
							layoutId={"cEiUrNNp6"}
						>
							<ComponentViewportProvider
								height={32}
								width={"32px"}
								y={(componentViewport?.y || 0) + 16 + 855 + 0}
								{...addPropertyOverrides(
									{
										MntQVnGNM: {
											y: (componentViewport?.y || 0) + 8 + 799 + 0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer
									className={"framer-1da3kcr-container"}
									layoutDependency={layoutDependency}
									layoutId={"PS4ya3le9-container"}
									nodeId={"PS4ya3le9"}
									rendersWithMotion={true}
									scopeId={"s5td2A0yO"}
								>
									{_jsx(stdin_default4, {
										height: "100%",
										HNjNxwYxi: YrwevER2x2,
										id: "PS4ya3le9",
										layoutId: "PS4ya3le9",
										style: {
											height: "100%",
											width: "100%",
										},
										variant: "NYa5mqssh",
										width: "100%",
										Y9NktqVWj: stdin_default2,
										...addPropertyOverrides(
											{
												MntQVnGNM: {
													variant: "vmA_D6XNE",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							<ComponentViewportProvider
								height={32}
								width={"32px"}
								y={(componentViewport?.y || 0) + 16 + 855 + 0}
								{...addPropertyOverrides(
									{
										MntQVnGNM: {
											y: (componentViewport?.y || 0) + 8 + 799 + 0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer
									className={"framer-6irx0q-container"}
									layoutDependency={layoutDependency}
									layoutId={"B1cVvqMTX-container"}
									nodeId={"B1cVvqMTX"}
									rendersWithMotion={true}
									scopeId={"s5td2A0yO"}
								>
									{_jsx(stdin_default4, {
										height: "100%",
										HNjNxwYxi: f6p19kOhb2,
										id: "B1cVvqMTX",
										layoutId: "B1cVvqMTX",
										style: {
											height: "100%",
											width: "100%",
										},
										variant: "NYa5mqssh",
										width: "100%",
										Y9NktqVWj: stdin_default,
										...addPropertyOverrides(
											{
												MntQVnGNM: {
													variant: "vmA_D6XNE",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							<ComponentViewportProvider
								height={32}
								width={"32px"}
								y={(componentViewport?.y || 0) + 16 + 855 + 0}
								{...addPropertyOverrides(
									{
										MntQVnGNM: {
											y: (componentViewport?.y || 0) + 8 + 799 + 0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer
									className={"framer-1qjg4i8-container"}
									layoutDependency={layoutDependency}
									layoutId={"TRcb2_DPB-container"}
									nodeId={"TRcb2_DPB"}
									rendersWithMotion={true}
									scopeId={"s5td2A0yO"}
								>
									{_jsx(stdin_default4, {
										height: "100%",
										HNjNxwYxi: WiAqS5pPk2,
										id: "TRcb2_DPB",
										layoutId: "TRcb2_DPB",
										style: {
											height: "100%",
											width: "100%",
										},
										variant: "NYa5mqssh",
										width: "100%",
										Y9NktqVWj: stdin_default3,
										...addPropertyOverrides(
											{
												MntQVnGNM: {
													variant: "vmA_D6XNE",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						</motion.div>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1k6lvcf"}
							data-framer-name={"Danial Cruze"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"zg_Kw3cTB"}
							style={{
								"--framer-paragraph-spacing": "0px",
								rotate: -11,
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-1kvyzj4"}
									data-styles-preset={"StrFP5FPP"}
								>
									{"Danial Cruze"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<motion.div
							className={"framer-194bxam"}
							data-framer-name={"Ellipse 39"}
							layoutDependency={layoutDependency}
							layoutId={"LiqXyrjLr"}
							style={{
								backgroundColor: "rgba(0, 121, 187, 0.3)",
								borderBottomLeftRadius: "100%",
								borderBottomRightRadius: "100%",
								borderTopLeftRadius: "100%",
								borderTopRightRadius: "100%",
								filter: "blur(50px)",
								WebkitFilter: "blur(50px)",
							}}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-eoEnB.framer-10ka8x9, .framer-eoEnB .framer-10ka8x9 { display: block; }",
	".framer-eoEnB.framer-1ca0prc { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 16px 16px 40px 16px; position: relative; width: 560px; will-change: var(--framer-will-change-override, transform); }",
	".framer-eoEnB .framer-1aohk02 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 8px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-eoEnB .framer-blyw7w { aspect-ratio: 1.103448275862069 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 464px); position: relative; width: 100%; }",
	".framer-eoEnB .framer-at3m90 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px 8px 0px 8px; position: relative; width: 100%; }",
	".framer-eoEnB .framer-1a6ni0c { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-eoEnB .framer-5mo5so, .framer-eoEnB .framer-113ukxw, .framer-eoEnB .framer-1ympz40 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-eoEnB .framer-1kgo82v { flex: none; height: 1px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-eoEnB .framer-3emb9 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px 8px 0px 8px; position: relative; width: min-content; }",
	".framer-eoEnB .framer-1da3kcr-container, .framer-eoEnB .framer-6irx0q-container, .framer-eoEnB .framer-1qjg4i8-container { flex: none; height: 32px; position: relative; width: 32px; }",
	".framer-eoEnB .framer-1k6lvcf { bottom: 38px; flex: none; height: auto; position: absolute; right: 37px; white-space: pre; width: auto; z-index: 1; }",
	".framer-eoEnB .framer-194bxam { bottom: -20px; flex: none; height: 31px; left: -12px; position: absolute; right: -12px; z-index: 1; }",
	".framer-eoEnB.framer-v-ewi5nz.framer-1ca0prc { gap: 16px; padding: 8px 8px 30px 8px; }",
	".framer-eoEnB.framer-v-ewi5nz .framer-blyw7w { height: var(--framer-aspect-ratio-supported, 479px); }",
	".framer-eoEnB.framer-v-ewi5nz .framer-at3m90 { gap: 16px; }",
	".framer-eoEnB.framer-v-ewi5nz .framer-1k6lvcf { bottom: 21px; }",
	...css2,
	...css,
	...css3,
	'.framer-eoEnB[data-border="true"]::after, .framer-eoEnB [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var Framers5td2A0yO = withCSS(Component, css4, "framer-eoEnB");
var stdin_default5 = Framers5td2A0yO;
Framers5td2A0yO.displayName = "Mentor Card";
Framers5td2A0yO.defaultProps = {
	height: 853,
	width: 560,
};
addPropertyControls(Framers5td2A0yO, {
	variant: {
		options: ["b4Zw4C4Bt", "MntQVnGNM"],
		optionTitles: ["L", "M"],
		title: "Variant",
		type: ControlType.Enum,
	},
	cI6i37jU1: {
		__defaultAssetReference:
			"data:framer/asset-reference,1srWHUJqUVL8SmTzt5zFucmJWQ.jpg?originalFilename=Video+cover.jpg&width=8668&height=4876",
		__vekterDefault: {
			alt: "Asian man with glasses in a creative workspace, surrounded by colorful abstract art and stationery on a cluttered desk.",
			assetReference:
				"data:framer/asset-reference,1srWHUJqUVL8SmTzt5zFucmJWQ.jpg?originalFilename=Video+cover.jpg&width=8668&height=4876",
			positionX: "52.5%",
			positionY: "35.7%",
		},
		description: "",
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	NIeT2WXix: {
		defaultValue: "Danial Cruze",
		displayTextArea: false,
		title: "Name",
		type: ControlType.String,
	},
	KC0kxLqKZ: {
		defaultValue: "Senior Video Editor at Zenith",
		displayTextArea: false,
		title: "Designation",
		type: ControlType.String,
	},
	BxTEWeXzC: {
		defaultValue:
			"Award-winning editor with over a decade of experience crafting commercials, documentaries, and social campaigns. He\u2019s collaborated with top-tier brands and creative teams worldwide, and now he\u2019s sharing every practical skill, workflow, and creative insight he\u2019s gained\u2014without holding anything back.",
		displayTextArea: false,
		title: "Bio",
		type: ControlType.String,
	},
	YrwevER2x: {
		title: "X Link",
		type: ControlType.Link,
	},
	f6p19kOhb: {
		title: "LinkedIn Link",
		type: ControlType.Link,
	},
	WiAqS5pPk: {
		title: "Instagram Link",
		type: ControlType.Link,
	},
});
addFonts(
	Framers5td2A0yO,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...SocialLinkFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts3),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:mentor-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "MntQVnGNM",
	xl: "b4Zw4C4Bt",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5af1700726b89e1359bd903da3e469ba956b8fc7e56af575f49bcf468e7d9c62"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default5, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders MentorCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5af1700726b89e1359bd903da3e469ba956b8fc7e56af575f49bcf468e7d9c62"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default5}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default5);
var mentor_card_default = ComponentWithRoot;
export { mentor_card_default as default };
