// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5af1700726b89e13 "Cliplab Studio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'L' | 'M/S' // Variant
 * title?: string // Title
 * click?: Function // Click
 * link?: string // Link
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-ZOSDNJUM.js";
import { className, css, fonts } from "./chunks/chunk-NORUQDUQ.js";
import { routes } from "./chunks/chunk-2NVZ5JSA.js";

// virtual:nav-link
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/8Dp6bHz6oYUS3SlVA9uJ/14h11qBSSfwya5pj62iV/jhdLS8r4u.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Link,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var enabledGestures = {
	VJ9ToqxFT: {
		hover: true,
	},
};
var cycleOrder = ["VJ9ToqxFT", "RorVuIOAF"];
var serializationHash = "framer-lEaXF";
var variantClassNames = {
	RorVuIOAF: "framer-v-s808wi",
	VJ9ToqxFT: "framer-v-iazkme",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 80,
	delay: 0,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"M/S": "RorVuIOAF",
	L: "VJ9ToqxFT",
};
var getProps = ({ click, height, id, link, title, width, ...props }) => {
	return {
		...props,
		DfBSFdlxJ: link ?? props.DfBSFdlxJ,
		I162RSKBW: title ?? props.I162RSKBW ?? "Cliplab Studio",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "VJ9ToqxFT",
		xydoHK1Ri: click ?? props.xydoHK1Ri,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		I162RSKBW: I162RSKBW2,
		xydoHK1Ri: xydoHK1Ri2,
		DfBSFdlxJ: DfBSFdlxJ2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "VJ9ToqxFT",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap1rwn1pb = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (xydoHK1Ri2) {
			const res = await xydoHK1Ri2(...args);
			if (res === false) return false;
		}
	});
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={DfBSFdlxJ2}
						motionChild={true}
						nodeId={"VJ9ToqxFT"}
						openInNewTab={false}
						scopeId={"jhdLS8r4u"}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-iazkme", className3, classNames)} framer-19eg31n`}
							data-framer-name={"L"}
							data-highlight={true}
							layoutDependency={layoutDependency}
							layoutId={"VJ9ToqxFT"}
							onTap={onTap1rwn1pb}
							ref={refBinding}
							style={{
								...style,
							}}
							{...addPropertyOverrides(
								{
									"VJ9ToqxFT-hover": {
										"data-framer-name": void 0,
									},
									RorVuIOAF: {
										"data-framer-name": "M/S",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-jwxhhf"}
								data-framer-name={"Text"}
								layoutDependency={layoutDependency}
								layoutId={"FB4nP6M9p"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-x6eaiy"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"QPt_gsliX"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-9d9c37d5-31f4-4564-b2ab-c0d257f64cbd, rgb(250, 250, 250))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
										filter: "blur(0px)",
										WebkitFilter: "blur(0px)",
									}}
									text={I162RSKBW2}
									variants={{
										"VJ9ToqxFT-hover": {
											filter: "blur(5px)",
											WebkitFilter: "blur(5px)",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											"VJ9ToqxFT-hover": {
												transformTemplate: transformTemplate1,
											},
											RorVuIOAF: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-1ozhwx8"}
															data-styles-preset={"BsEnbfNw3"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-9d9c37d5-31f4-4564-b2ab-c0d257f64cbd, rgb(250, 250, 250)))",
															}}
														>
															{"Cliplab Studio"}
														</motion.p>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1h481q3"}
											data-styles-preset={"uWgmT59JL"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-9d9c37d5-31f4-4564-b2ab-c0d257f64cbd, rgb(250, 250, 250)))",
											}}
										>
											{"Cliplab Studio"}
										</motion.p>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-n9dbff"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"xfa0f27Li"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-9d9c37d5-31f4-4564-b2ab-c0d257f64cbd, rgb(250, 250, 250))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
										filter: "blur(5px)",
										WebkitFilter: "blur(5px)",
									}}
									text={I162RSKBW2}
									variants={{
										"VJ9ToqxFT-hover": {
											filter: "blur(0px)",
											WebkitFilter: "blur(0px)",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											RorVuIOAF: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-1ozhwx8"}
															data-styles-preset={"BsEnbfNw3"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-9d9c37d5-31f4-4564-b2ab-c0d257f64cbd, rgb(250, 250, 250)))",
															}}
														>
															{"Cliplab Studio"}
														</motion.p>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1h481q3"}
											data-styles-preset={"uWgmT59JL"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-9d9c37d5-31f4-4564-b2ab-c0d257f64cbd, rgb(250, 250, 250)))",
											}}
										>
											{"Cliplab Studio"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-lEaXF.framer-19eg31n, .framer-lEaXF .framer-19eg31n { display: block; }",
	".framer-lEaXF.framer-iazkme { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; text-decoration: none; width: min-content; }",
	".framer-lEaXF .framer-jwxhhf { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-lEaXF .framer-x6eaiy { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-lEaXF .framer-n9dbff { bottom: -30px; flex: none; height: auto; left: 0px; position: absolute; white-space: pre; width: auto; z-index: 1; }",
	".framer-lEaXF.framer-v-iazkme.hover .framer-x6eaiy { left: 50%; position: absolute; top: -30px; z-index: 1; }",
	".framer-lEaXF.framer-v-iazkme.hover .framer-n9dbff { bottom: unset; left: unset; position: relative; }",
	...css2,
	...css,
];
var FramerjhdLS8r4u = withCSS(Component, css3, "framer-lEaXF");
var stdin_default = FramerjhdLS8r4u;
FramerjhdLS8r4u.displayName = "Nav link";
FramerjhdLS8r4u.defaultProps = {
	height: 20,
	width: 92,
};
addPropertyControls(FramerjhdLS8r4u, {
	variant: {
		options: ["VJ9ToqxFT", "RorVuIOAF"],
		optionTitles: ["L", "M/S"],
		title: "Variant",
		type: ControlType.Enum,
	},
	I162RSKBW: {
		defaultValue: "Cliplab Studio",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	xydoHK1Ri: {
		title: "Click",
		type: ControlType.EventHandler,
	},
	DfBSFdlxJ: {
		title: "Link",
		type: ControlType.Link,
	},
});
addFonts(
	FramerjhdLS8r4u,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:nav-link
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "RorVuIOAF",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5af1700726b89e1359bd903da3e469ba956b8fc7e56af575f49bcf468e7d9c62"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders NavLinkFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5af1700726b89e1359bd903da3e469ba956b8fc7e56af575f49bcf468e7d9c62"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var nav_link_default = ComponentWithRoot;
export { nav_link_default as default };
