// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5af1700726b89e13 "Cliplab Studio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Play' | 'M/S Play' | 'Pause' | 'M/S Pause' // Variant
 * click?: Function // Click
}} Props

 */
import { stdin_default, stdin_default2 } from "./chunks/chunk-L2OIHFDR.js";
import { routes } from "./chunks/chunk-2NVZ5JSA.js";

// virtual:play-button
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/rvZMoY2BcqEED082XJaG/tIoRQXIWA7AXwwDc8Aj7/eYY017pCH.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	Instance,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var enabledGestures = {
	kFrpjnyB_: {
		pressed: true,
	},
	r1TCcAoDi: {
		hover: true,
		pressed: true,
	},
	sELt6iCMD: {
		hover: true,
		pressed: true,
	},
	uIhzbfwFf: {
		pressed: true,
	},
};
var cycleOrder = ["r1TCcAoDi", "uIhzbfwFf", "sELt6iCMD", "kFrpjnyB_"];
var serializationHash = "framer-P0wjA";
var variantClassNames = {
	kFrpjnyB_: "framer-v-1ws16i",
	r1TCcAoDi: "framer-v-1d60vjd",
	sELt6iCMD: "framer-v-3aeer7",
	uIhzbfwFf: "framer-v-ec8md2",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 80,
	delay: 0,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"M/S Pause": "kFrpjnyB_",
	"M/S Play": "uIhzbfwFf",
	Pause: "sELt6iCMD",
	Play: "r1TCcAoDi",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ click, height, id, width, ...props }) => {
	return {
		...props,
		fMl4WdK65: click ?? props.fMl4WdK65,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "r1TCcAoDi",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		fMl4WdK65: fMl4WdK652,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "r1TCcAoDi",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap1239eh7 = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (fMl4WdK652) {
			const res = await fMl4WdK652(...args);
			if (res === false) return false;
		}
		setVariant("sELt6iCMD");
	});
	const onTap143bpek = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (fMl4WdK652) {
			const res = await fMl4WdK652(...args);
			if (res === false) return false;
		}
		setVariant("kFrpjnyB_");
	});
	const onTapqxcaht = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (fMl4WdK652) {
			const res = await fMl4WdK652(...args);
			if (res === false) return false;
		}
		setVariant("r1TCcAoDi");
	});
	const onTap158sprh = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (fMl4WdK652) {
			const res = await fMl4WdK652(...args);
			if (res === false) return false;
		}
		setVariant("uIhzbfwFf");
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1d60vjd",
							className,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Play"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"r1TCcAoDi"}
						onTap={onTap1239eh7}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-cb2206d2-93ba-4bbf-8a99-2fb6eb742230, rgba(255, 255, 255, 0.1))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backdropFilter: "blur(10px)",
							backgroundColor:
								"var(--token-1f303d20-0e84-477f-a136-1b59867d6be1, rgba(255, 255, 255, 0.5))",
							borderBottomLeftRadius: 20,
							borderBottomRightRadius: 20,
							borderTopLeftRadius: 20,
							borderTopRightRadius: 20,
							WebkitBackdropFilter: "blur(10px)",
							...style,
						}}
						variants={{
							"kFrpjnyB_-pressed": {
								"--border-bottom-width": "0.72px",
								"--border-left-width": "0.72px",
								"--border-right-width": "0.72px",
								"--border-top-width": "0.72px",
								backdropFilter: "blur(7px)",
								borderBottomLeftRadius: 14.45,
								borderBottomRightRadius: 14.45,
								borderTopLeftRadius: 14.45,
								borderTopRightRadius: 14.45,
								WebkitBackdropFilter: "blur(7px)",
							},
							"r1TCcAoDi-hover": {
								backgroundColor:
									"var(--token-925ba54a-9b0f-4497-8ea4-2af5dd48b8e6, rgba(255, 255, 255, 0.3))",
							},
							"r1TCcAoDi-pressed": {
								"--border-bottom-width": "0.83px",
								"--border-left-width": "0.83px",
								"--border-right-width": "0.83px",
								"--border-top-width": "0.83px",
								backdropFilter: "blur(8px)",
								borderBottomLeftRadius: 16.67,
								borderBottomRightRadius: 16.67,
								borderTopLeftRadius: 16.67,
								borderTopRightRadius: 16.67,
								WebkitBackdropFilter: "blur(8px)",
							},
							"sELt6iCMD-hover": {
								backgroundColor:
									"var(--token-925ba54a-9b0f-4497-8ea4-2af5dd48b8e6, rgba(255, 255, 255, 0.3))",
							},
							"sELt6iCMD-pressed": {
								"--border-bottom-width": "0.83px",
								"--border-left-width": "0.83px",
								"--border-right-width": "0.83px",
								"--border-top-width": "0.83px",
								backdropFilter: "blur(8px)",
								borderBottomLeftRadius: 16.67,
								borderBottomRightRadius: 16.67,
								borderTopLeftRadius: 16.67,
								borderTopRightRadius: 16.67,
								WebkitBackdropFilter: "blur(8px)",
							},
							kFrpjnyB_: {
								"--border-bottom-width": "0.78px",
								"--border-left-width": "0.78px",
								"--border-right-width": "0.78px",
								"--border-top-width": "0.78px",
								backdropFilter: "blur(8px)",
								backgroundColor:
									"var(--token-cb2206d2-93ba-4bbf-8a99-2fb6eb742230, rgba(255, 255, 255, 0.1))",
								borderBottomLeftRadius: 12,
								borderBottomRightRadius: 12,
								borderTopLeftRadius: 12,
								borderTopRightRadius: 12,
								WebkitBackdropFilter: "blur(8px)",
							},
							sELt6iCMD: {
								backgroundColor:
									"var(--token-cb2206d2-93ba-4bbf-8a99-2fb6eb742230, rgba(255, 255, 255, 0.1))",
							},
							uIhzbfwFf: {
								borderBottomLeftRadius: 12,
								borderBottomRightRadius: 12,
								borderTopLeftRadius: 12,
								borderTopRightRadius: 12,
							},
						}}
						{...addPropertyOverrides(
							{
								"kFrpjnyB_-pressed": {
									"data-framer-name": void 0,
								},
								"r1TCcAoDi-hover": {
									"data-framer-name": void 0,
								},
								"r1TCcAoDi-pressed": {
									"data-framer-name": void 0,
								},
								"sELt6iCMD-hover": {
									"data-framer-name": void 0,
								},
								"sELt6iCMD-pressed": {
									"data-framer-name": void 0,
								},
								"uIhzbfwFf-pressed": {
									"data-framer-name": void 0,
								},
								kFrpjnyB_: {
									"data-framer-name": "M/S Pause",
									onTap: onTap158sprh,
								},
								sELt6iCMD: {
									"data-framer-name": "Pause",
									onTap: onTapqxcaht,
								},
								uIhzbfwFf: {
									"data-framer-name": "M/S Play",
									onTap: onTap143bpek,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<Instance
							animated={true}
							className={"framer-61r7re"}
							Component={stdin_default2}
							layoutDependency={layoutDependency}
							layoutId={"KrvREcHUv"}
							style={{
								"--1m6trwb": 0,
								"--21h8s6":
									"var(--token-9d9c37d5-31f4-4564-b2ab-c0d257f64cbd, rgb(255, 255, 255))",
								"--pgex8v": 1.5,
							}}
							variants={{
								"kFrpjnyB_-pressed": {
									"--1m6trwb": 1,
								},
								"r1TCcAoDi-hover": {
									"--1m6trwb": 0.8,
								},
								"r1TCcAoDi-pressed": {
									"--1m6trwb": 1,
								},
								"sELt6iCMD-hover": {
									"--1m6trwb": 1,
								},
								"uIhzbfwFf-pressed": {
									"--1m6trwb": 0.8,
								},
							}}
							{...addPropertyOverrides(
								{
									kFrpjnyB_: {
										Component: stdin_default,
									},
									sELt6iCMD: {
										Component: stdin_default,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-P0wjA.framer-1xbtt1r, .framer-P0wjA .framer-1xbtt1r { display: block; }",
	".framer-P0wjA.framer-1d60vjd { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 20px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-P0wjA .framer-61r7re { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 32px); position: relative; width: 32px; }",
	".framer-P0wjA.framer-v-ec8md2.framer-1d60vjd { padding: 12px; }",
	".framer-P0wjA.framer-v-ec8md2 .framer-61r7re, .framer-P0wjA.framer-v-1ws16i .framer-61r7re { height: var(--framer-aspect-ratio-supported, 22px); width: 22px; }",
	".framer-P0wjA.framer-v-1ws16i.framer-1d60vjd { gap: 7.78px; padding: 12px; }",
	".framer-P0wjA.framer-v-1d60vjd.pressed.framer-1d60vjd { gap: 8.33px; height: 60px; width: 60px; }",
	".framer-P0wjA.framer-v-1d60vjd.pressed .framer-61r7re, .framer-P0wjA.framer-v-3aeer7.pressed .framer-61r7re { height: var(--framer-aspect-ratio-supported, 26px); width: 27px; }",
	".framer-P0wjA.framer-v-ec8md2.pressed .framer-61r7re, .framer-P0wjA.framer-v-1ws16i.pressed .framer-61r7re { height: var(--framer-aspect-ratio-supported, 20px); width: 20px; }",
	".framer-P0wjA.framer-v-3aeer7.pressed.framer-1d60vjd { gap: 8.33px; padding: 16.67px; }",
	".framer-P0wjA.framer-v-1ws16i.pressed.framer-1d60vjd { gap: 7.22px; }",
	'.framer-P0wjA[data-border="true"]::after, .framer-P0wjA [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramereYY017pCH = withCSS(Component, css, "framer-P0wjA");
var stdin_default3 = FramereYY017pCH;
FramereYY017pCH.displayName = "Play Button";
FramereYY017pCH.defaultProps = {
	height: 72,
	width: 72,
};
addPropertyControls(FramereYY017pCH, {
	variant: {
		options: ["r1TCcAoDi", "uIhzbfwFf", "sELt6iCMD", "kFrpjnyB_"],
		optionTitles: ["Play", "M/S Play", "Pause", "M/S Pause"],
		title: "Variant",
		type: ControlType.Enum,
	},
	fMl4WdK65: {
		title: "Click",
		type: ControlType.EventHandler,
	},
});
addFonts(
	FramereYY017pCH,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:play-button
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "r1TCcAoDi",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5af1700726b89e1359bd903da3e469ba956b8fc7e56af575f49bcf468e7d9c62"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders PlayButtonFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5af1700726b89e1359bd903da3e469ba956b8fc7e56af575f49bcf468e7d9c62"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var play_button_default = ComponentWithRoot;
export { play_button_default as default };
