// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5af1700726b89e13 "Cliplab Studio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Active' | 'Deactive' // Variant
 * text?: string // Text
}} Props

 */
import { stdin_default } from "./chunks/chunk-UWDAN3I7.js";
import { className, css, fonts } from "./chunks/chunk-NORUQDUQ.js";
import { routes } from "./chunks/chunk-2NVZ5JSA.js";

// virtual:point
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/rbdOqvNs5Al18DAepOqS/DieNS2Zl2Nh26pE2UgNE/fWz38XmR2.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var CheckFonts = getFonts(stdin_default);
var cycleOrder = ["CuwHe5C5P", "S49JJMjML"];
var serializationHash = "framer-3XJwq";
var variantClassNames = {
	CuwHe5C5P: "framer-v-124tgg6",
	S49JJMjML: "framer-v-15rk8yw",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Active: "CuwHe5C5P",
	Deactive: "S49JJMjML",
};
var getProps = ({ height, id, text, width, ...props }) => {
	return {
		...props,
		ualVz9QLA: text ?? props.ualVz9QLA ?? "Full Course access",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "CuwHe5C5P",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		ualVz9QLA: ualVz9QLA2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "CuwHe5C5P",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-124tgg6",
							className2,
							classNames,
						)}
						data-framer-name={"Active"}
						layoutDependency={layoutDependency}
						layoutId={"CuwHe5C5P"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								S49JJMjML: {
									"data-framer-name": "Deactive",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1d2fk0x"}
							data-framer-name={"Icon"}
							layoutDependency={layoutDependency}
							layoutId={"faTuCs6he"}
							style={{
								backgroundColor:
									"var(--token-d4c36658-1f4b-41b3-aa0d-cf9b918d88bf, rgb(0, 122, 187))",
								borderBottomLeftRadius: 190,
								borderBottomRightRadius: 190,
								borderTopLeftRadius: 190,
								borderTopRightRadius: 190,
							}}
							variants={{
								S49JJMjML: {
									backgroundColor:
										"var(--token-925ba54a-9b0f-4497-8ea4-2af5dd48b8e6, rgba(255, 255, 255, 0.3))",
								},
							}}
						>
							{_jsx(stdin_default, {
								animated: true,
								className: "framer-vw39e6",
								layoutDependency,
								layoutId: "qUS7cWhoI",
								style: {
									"--1m6trwb": 0,
									"--21h8s6":
										"var(--token-9d9c37d5-31f4-4564-b2ab-c0d257f64cbd, rgb(250, 250, 250))",
									"--pgex8v": 2,
								},
								variants: {
									S49JJMjML: {
										"--21h8s6":
											"var(--token-925ba54a-9b0f-4497-8ea4-2af5dd48b8e6, rgba(255, 255, 255, 0.3))",
									},
								},
							})}
						</motion.div>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-190jhbj"}
							data-framer-name={"Full Course access"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"G01N4H_0K"}
							style={{
								"--extracted-r6o4lv":
									"var(--token-9d9c37d5-31f4-4564-b2ab-c0d257f64cbd, rgb(250, 250, 250))",
								"--framer-paragraph-spacing": "0px",
							}}
							text={ualVz9QLA2}
							variants={{
								S49JJMjML: {
									"--extracted-r6o4lv":
										"var(--token-925ba54a-9b0f-4497-8ea4-2af5dd48b8e6, rgba(255, 255, 255, 0.3))",
								},
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
							{...addPropertyOverrides(
								{
									S49JJMjML: {
										children: (
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-1ozhwx8"}
													data-styles-preset={"BsEnbfNw3"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-925ba54a-9b0f-4497-8ea4-2af5dd48b8e6, rgba(255, 255, 255, 0.3)))",
													}}
												>
													{"Full Course access"}
												</motion.p>
											</React.Fragment>
										),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-1ozhwx8"}
									data-styles-preset={"BsEnbfNw3"}
									style={{
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--token-9d9c37d5-31f4-4564-b2ab-c0d257f64cbd, rgb(250, 250, 250)))",
									}}
								>
									{"Full Course access"}
								</motion.p>
							</React.Fragment>
						</RichText>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-3XJwq.framer-j2bp8m, .framer-3XJwq .framer-j2bp8m { display: block; }",
	".framer-3XJwq.framer-124tgg6 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-3XJwq .framer-1d2fk0x { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 2px; position: relative; width: min-content; }",
	".framer-3XJwq .framer-vw39e6 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 20px); position: relative; width: 18px; }",
	".framer-3XJwq .framer-190jhbj { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	...css,
];
var FramerfWz38XmR2 = withCSS(Component, css2, "framer-3XJwq");
var stdin_default2 = FramerfWz38XmR2;
FramerfWz38XmR2.displayName = "Point";
FramerfWz38XmR2.defaultProps = {
	height: 22,
	width: 173,
};
addPropertyControls(FramerfWz38XmR2, {
	variant: {
		options: ["CuwHe5C5P", "S49JJMjML"],
		optionTitles: ["Active", "Deactive"],
		title: "Variant",
		type: ControlType.Enum,
	},
	ualVz9QLA: {
		defaultValue: "Full Course access",
		displayTextArea: false,
		title: "Text",
		type: ControlType.String,
	},
});
addFonts(
	FramerfWz38XmR2,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...CheckFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:point
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "CuwHe5C5P",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5af1700726b89e1359bd903da3e469ba956b8fc7e56af575f49bcf468e7d9c62"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders PointFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5af1700726b89e1359bd903da3e469ba956b8fc7e56af575f49bcf468e7d9c62"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var point_default = ComponentWithRoot;
export { point_default as default };
