// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5af1700726b89e13 "Cliplab Studio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Pro Plan- L' | 'Basic Plan - L' | 'Pro Plan - M/S' | 'Basic Plan - M/S' // Variant
 * link?: string // Link
 * newTab?: boolean // New Tab
}} Props

 */
import { stdin_default as stdin_default2 } from "./chunks/chunk-UWDAN3I7.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-ZKKHZKR5.js";
import {
	className,
	css,
	fonts,
	stdin_default,
} from "./chunks/chunk-UARBEP46.js";
import "./chunks/chunk-6HGIPRDC.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-NORUQDUQ.js";
import { routes } from "./chunks/chunk-2NVZ5JSA.js";

// virtual:price-card
import { Fragment as Fragment4 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/jx7y10PKBg5FTLDCaLuS/mxtP067NCuWluDBtMT2B/vT6twQNZ5.js
import { jsx as _jsx3, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts3,
	addPropertyControls as addPropertyControls3,
	ComponentViewportProvider,
	ControlType as ControlType3,
	cx as cx3,
	getFonts as getFonts2,
	getFontsFromSharedStyle as getFontsFromSharedStyle3,
	RichText as RichText3,
	SmartComponentScopedContainer,
	useComponentViewport as useComponentViewport3,
	useLocaleInfo as useLocaleInfo3,
	useVariantState as useVariantState3,
	withCSS as withCSS3,
} from "unframer";
import {
	LayoutGroup as LayoutGroup3,
	motion as motion3,
	MotionConfigContext as MotionConfigContext3,
} from "unframer";
import * as React3 from "react";
import { useRef as useRef3 } from "react";

// /:https://framerusercontent.com/modules/fD7Je1V3sEDyYTM28pr3/w12Jd29SJibF7lnkDGjt/fWz38XmR2.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var CheckFonts = getFonts(stdin_default2);
var cycleOrder = ["CuwHe5C5P", "S49JJMjML"];
var serializationHash = "framer-3XJwq";
var variantClassNames = {
	CuwHe5C5P: "framer-v-124tgg6",
	S49JJMjML: "framer-v-15rk8yw",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Active: "CuwHe5C5P",
	Deactive: "S49JJMjML",
};
var getProps = ({ height, id, text, width, ...props }) => {
	return {
		...props,
		ualVz9QLA: text ?? props.ualVz9QLA ?? "Full Course access",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "CuwHe5C5P",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		ualVz9QLA: ualVz9QLA2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "CuwHe5C5P",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-124tgg6",
							className4,
							classNames,
						)}
						data-framer-name={"Active"}
						layoutDependency={layoutDependency}
						layoutId={"CuwHe5C5P"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								S49JJMjML: {
									"data-framer-name": "Deactive",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1d2fk0x"}
							data-framer-name={"Icon"}
							layoutDependency={layoutDependency}
							layoutId={"faTuCs6he"}
							style={{
								backgroundColor:
									"var(--token-d4c36658-1f4b-41b3-aa0d-cf9b918d88bf, rgb(0, 122, 187))",
								borderBottomLeftRadius: 190,
								borderBottomRightRadius: 190,
								borderTopLeftRadius: 190,
								borderTopRightRadius: 190,
							}}
							variants={{
								S49JJMjML: {
									backgroundColor:
										"var(--token-925ba54a-9b0f-4497-8ea4-2af5dd48b8e6, rgba(255, 255, 255, 0.3))",
								},
							}}
						>
							{_jsx(stdin_default2, {
								animated: true,
								className: "framer-vw39e6",
								layoutDependency,
								layoutId: "qUS7cWhoI",
								style: {
									"--1m6trwb": 0,
									"--21h8s6":
										"var(--token-9d9c37d5-31f4-4564-b2ab-c0d257f64cbd, rgb(250, 250, 250))",
									"--pgex8v": 2,
								},
								variants: {
									S49JJMjML: {
										"--21h8s6":
											"var(--token-925ba54a-9b0f-4497-8ea4-2af5dd48b8e6, rgba(255, 255, 255, 0.3))",
									},
								},
							})}
						</motion.div>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-190jhbj"}
							data-framer-name={"Full Course access"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"G01N4H_0K"}
							style={{
								"--extracted-r6o4lv":
									"var(--token-9d9c37d5-31f4-4564-b2ab-c0d257f64cbd, rgb(250, 250, 250))",
								"--framer-paragraph-spacing": "0px",
							}}
							text={ualVz9QLA2}
							variants={{
								S49JJMjML: {
									"--extracted-r6o4lv":
										"var(--token-925ba54a-9b0f-4497-8ea4-2af5dd48b8e6, rgba(255, 255, 255, 0.3))",
								},
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
							{...addPropertyOverrides(
								{
									S49JJMjML: {
										children: (
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-1ozhwx8"}
													data-styles-preset={"BsEnbfNw3"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-925ba54a-9b0f-4497-8ea4-2af5dd48b8e6, rgba(255, 255, 255, 0.3)))",
													}}
												>
													{"Full Course access"}
												</motion.p>
											</React.Fragment>
										),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-1ozhwx8"}
									data-styles-preset={"BsEnbfNw3"}
									style={{
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--token-9d9c37d5-31f4-4564-b2ab-c0d257f64cbd, rgb(250, 250, 250)))",
									}}
								>
									{"Full Course access"}
								</motion.p>
							</React.Fragment>
						</RichText>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-3XJwq.framer-j2bp8m, .framer-3XJwq .framer-j2bp8m { display: block; }",
	".framer-3XJwq.framer-124tgg6 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-3XJwq .framer-1d2fk0x { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 2px; position: relative; width: min-content; }",
	".framer-3XJwq .framer-vw39e6 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 20px); position: relative; width: 18px; }",
	".framer-3XJwq .framer-190jhbj { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	...css2,
];
var FramerfWz38XmR2 = withCSS(Component, css4, "framer-3XJwq");
var stdin_default3 = FramerfWz38XmR2;
FramerfWz38XmR2.displayName = "Point";
FramerfWz38XmR2.defaultProps = {
	height: 22,
	width: 173,
};
addPropertyControls(FramerfWz38XmR2, {
	variant: {
		options: ["CuwHe5C5P", "S49JJMjML"],
		optionTitles: ["Active", "Deactive"],
		title: "Variant",
		type: ControlType.Enum,
	},
	ualVz9QLA: {
		defaultValue: "Full Course access",
		displayTextArea: false,
		title: "Text",
		type: ControlType.String,
	},
});
addFonts(
	FramerfWz38XmR2,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...CheckFonts,
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/yLCT8x6D6ry6XLhinfCE/NfUES6b2a7xjK0pb45dV/iv_9rqEW4.js
import { jsx as _jsx2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType2,
	cx as cx2,
	getFontsFromSharedStyle as getFontsFromSharedStyle2,
	RichText as RichText2,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";
var cycleOrder2 = ["hVatJzmXK", "MzviDL_ZH"];
var serializationHash2 = "framer-sBSoA";
var variantClassNames2 = {
	hVatJzmXK: "framer-v-646z76",
	MzviDL_ZH: "framer-v-1dz4sma",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap2 = {
	"Variant 2": "MzviDL_ZH",
	Variant: "hVatJzmXK",
};
var getProps2 = ({ height, id, title, width, ...props }) => {
	return {
		...props,
		JWhXhovmV: title ?? props.JWhXhovmV ?? "Pro Plan",
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "hVatJzmXK",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		JWhXhovmV: JWhXhovmV2,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "hVatJzmXK",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [className3];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-646z76",
							className4,
							classNames,
						)}
						layoutDependency={layoutDependency}
						layoutId={"hVatJzmXK"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "0px",
							"--border-color": "rgba(0, 0, 0, 0)",
							"--border-left-width": "0px",
							"--border-right-width": "0px",
							"--border-style": "solid",
							"--border-top-width": "0px",
							backgroundColor:
								"var(--token-a0b331ef-7085-4a1e-a4b5-0195668a9610, rgb(213, 255, 0))",
							borderBottomLeftRadius: 6,
							borderBottomRightRadius: 6,
							borderTopLeftRadius: 6,
							borderTopRightRadius: 6,
							...style,
						}}
						variants={{
							MzviDL_ZH: {
								"--border-bottom-width": "1px",
								"--border-color":
									"var(--token-cb2206d2-93ba-4bbf-8a99-2fb6eb742230, rgba(255, 255, 255, 0.1))",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								backgroundColor:
									"var(--token-efc840ff-64db-4d68-b4f9-ffd23b298cd4, rgba(255, 255, 255, 0.05))",
							},
						}}
						{...addPropertyOverrides2(
							{
								MzviDL_ZH: {
									"data-border": true,
									"data-framer-name": "Variant 2",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<RichText2
							__fromCanvasComponent={true}
							className={"framer-1rxxr4x"}
							data-framer-name={"Pro Plan"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"ymGZshJkD"}
							style={{
								"--extracted-r6o4lv":
									"var(--token-cd811638-c7a7-467a-a0d6-438332270fd5, rgb(0, 1, 3))",
								"--framer-paragraph-spacing": "0px",
							}}
							text={JWhXhovmV2}
							variants={{
								MzviDL_ZH: {
									"--extracted-r6o4lv":
										"var(--token-9d9c37d5-31f4-4564-b2ab-c0d257f64cbd, rgb(250, 250, 250))",
								},
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
							{...addPropertyOverrides2(
								{
									MzviDL_ZH: {
										children: (
											<React2.Fragment>
												<motion2.p
													className={"framer-styles-preset-5xfrwz"}
													data-styles-preset={"ruLAtCqcd"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-9d9c37d5-31f4-4564-b2ab-c0d257f64cbd, rgb(250, 250, 250)))",
													}}
												>
													{"Pro Plan"}
												</motion2.p>
											</React2.Fragment>
										),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<React2.Fragment>
								<motion2.p
									className={"framer-styles-preset-5xfrwz"}
									data-styles-preset={"ruLAtCqcd"}
									style={{
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--token-cd811638-c7a7-467a-a0d6-438332270fd5, rgb(0, 1, 3)))",
									}}
								>
									{"Pro Plan"}
								</motion2.p>
							</React2.Fragment>
						</RichText2>
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css5 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-sBSoA.framer-552746, .framer-sBSoA .framer-552746 { display: block; }",
	".framer-sBSoA.framer-646z76 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; overflow: visible; padding: 4px 8px 4px 8px; position: relative; width: min-content; }",
	".framer-sBSoA .framer-1rxxr4x { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	...css3,
	'.framer-sBSoA[data-border="true"]::after, .framer-sBSoA [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var Frameriv_9rqEW4 = withCSS2(Component2, css5, "framer-sBSoA");
var stdin_default4 = Frameriv_9rqEW4;
Frameriv_9rqEW4.displayName = "Tag S";
Frameriv_9rqEW4.defaultProps = {
	height: 34,
	width: 80,
};
addPropertyControls2(Frameriv_9rqEW4, {
	variant: {
		options: ["hVatJzmXK", "MzviDL_ZH"],
		optionTitles: ["Variant", "Variant 2"],
		title: "Variant",
		type: ControlType2.Enum,
	},
	JWhXhovmV: {
		defaultValue: "Pro Plan",
		displayTextArea: false,
		title: "Title",
		type: ControlType2.String,
	},
});
addFonts2(
	Frameriv_9rqEW4,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle2(fonts3),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/jx7y10PKBg5FTLDCaLuS/mxtP067NCuWluDBtMT2B/vT6twQNZ5.js
var TagSFonts = getFonts2(stdin_default4);
var PrimaryButtonFonts = getFonts2(stdin_default);
var PointFonts = getFonts2(stdin_default3);
var cycleOrder3 = ["BqP4oPxA0", "wE074X52U", "n4cc0Kdzs", "TGNT2vw2f"];
var serializationHash3 = "framer-fEGsO";
var variantClassNames3 = {
	BqP4oPxA0: "framer-v-didhff",
	n4cc0Kdzs: "framer-v-1dnzprl",
	TGNT2vw2f: "framer-v-1atks9o",
	wE074X52U: "framer-v-17vqyr",
};
function addPropertyOverrides3(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition13 = {
	damping: 80,
	delay: 0,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var Transition3 = ({ value, children }) => {
	const config = React3.useContext(MotionConfigContext3);
	const transition = value ?? config.transition;
	const contextValue = React3.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext3.Provider value={contextValue}>
			{children}
		</MotionConfigContext3.Provider>
	);
};
var Variants3 = motion3.create(React3.Fragment);
var humanReadableVariantMap3 = {
	"Basic Plan - L": "wE074X52U",
	"Basic Plan - M/S": "TGNT2vw2f",
	"Pro Plan - M/S": "n4cc0Kdzs",
	"Pro Plan- L": "BqP4oPxA0",
};
var getProps3 = ({ height, id, link, newTab, width, ...props }) => {
	return {
		...props,
		AWI2viap7: link ?? props.AWI2viap7,
		dmF22hZf1: newTab ?? props.dmF22hZf1,
		variant:
			humanReadableVariantMap3[props.variant] ?? props.variant ?? "BqP4oPxA0",
	};
};
var createLayoutDependency3 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component3 = /* @__PURE__ */ React3.forwardRef(function (props, ref) {
	const fallbackRef = useRef3(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React3.useId();
	const { activeLocale, setLocale } = useLocaleInfo3();
	const componentViewport = useComponentViewport3();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		AWI2viap7: AWI2viap72,
		dmF22hZf1: dmF22hZf12,
		...restProps
	} = getProps3(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState3({
		cycleOrder: cycleOrder3,
		defaultVariant: "BqP4oPxA0",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames3,
	});
	const layoutDependency = createLayoutDependency3(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx3(serializationHash3, ...sharedStyleClassNames);
	return (
		<LayoutGroup3 id={layoutId ?? defaultLayoutId}>
			<Variants3 animate={variants} initial={false}>
				<Transition3 value={transition13}>
					<motion3.div
						{...restProps}
						{...gestureHandlers}
						className={cx3(
							scopingClassNames,
							"framer-didhff",
							className4,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Pro Plan- L"}
						layoutDependency={layoutDependency}
						layoutId={"BqP4oPxA0"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-d4c36658-1f4b-41b3-aa0d-cf9b918d88bf, rgb(0, 122, 187))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							borderBottomLeftRadius: 15,
							borderBottomRightRadius: 15,
							borderTopLeftRadius: 15,
							borderTopRightRadius: 15,
							...style,
						}}
						variants={{
							TGNT2vw2f: {
								"--border-color":
									"var(--token-cb2206d2-93ba-4bbf-8a99-2fb6eb742230, rgba(255, 255, 255, 0.1))",
							},
							wE074X52U: {
								"--border-color":
									"var(--token-cb2206d2-93ba-4bbf-8a99-2fb6eb742230, rgba(255, 255, 255, 0.1))",
							},
						}}
						{...addPropertyOverrides3(
							{
								n4cc0Kdzs: {
									"data-framer-name": "Pro Plan - M/S",
								},
								TGNT2vw2f: {
									"data-framer-name": "Basic Plan - M/S",
								},
								wE074X52U: {
									"data-framer-name": "Basic Plan - L",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion3.div
							className={"framer-pymyhn"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"l8WKHRHy1"}
							style={{
								background:
									"linear-gradient(180deg, var(--token-efc840ff-64db-4d68-b4f9-ffd23b298cd4, rgba(255, 255, 255, 0.05)) 0%, var(--token-737547ea-dc46-45bd-ae2b-4977e3da045e, rgba(9, 0, 189, 0.05)) 100%)",
								borderBottomLeftRadius: 7,
								borderBottomRightRadius: 7,
								borderTopLeftRadius: 7,
								borderTopRightRadius: 7,
							}}
						>
							<motion3.div
								className={"framer-qfdejo"}
								data-framer-name={"Content"}
								layoutDependency={layoutDependency}
								layoutId={"Yqu54OTp6"}
							>
								<motion3.div
									className={"framer-gaujbj"}
									data-framer-name={"Top"}
									layoutDependency={layoutDependency}
									layoutId={"qT8rgGvmn"}
								>
									<ComponentViewportProvider
										height={34}
										y={
											(componentViewport?.y || 0) +
											(10 +
												((componentViewport?.height || 538) - 20 - 516.4) / 2) +
											32 +
											0 +
											0 +
											0 +
											0
										}
									>
										<SmartComponentScopedContainer
											className={"framer-ep9c6q-container"}
											layoutDependency={layoutDependency}
											layoutId={"GgmEUEsHL-container"}
											nodeId={"GgmEUEsHL"}
											rendersWithMotion={true}
											scopeId={"vT6twQNZ5"}
										>
											{_jsx3(stdin_default4, {
												height: "100%",
												id: "GgmEUEsHL",
												JWhXhovmV: "Pro Plan",
												layoutId: "GgmEUEsHL",
												variant: "hVatJzmXK",
												width: "100%",
												...addPropertyOverrides3(
													{
														TGNT2vw2f: {
															JWhXhovmV: "Basic Plan",
															variant: "MzviDL_ZH",
														},
														wE074X52U: {
															JWhXhovmV: "Basic Plan",
															variant: "MzviDL_ZH",
														},
													},
													baseVariant,
													gestureVariant,
												),
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
									<RichText3
										__fromCanvasComponent={true}
										className={"framer-1crut6l"}
										data-framer-name={"$499"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"orr8NL0pI"}
										style={{
											"--extracted-a0htzi":
												"var(--token-9d9c37d5-31f4-4564-b2ab-c0d257f64cbd, rgb(250, 250, 250))",
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
										{...addPropertyOverrides3(
											{
												TGNT2vw2f: {
													children: (
														<React3.Fragment>
															<motion3.h3
																className={"framer-styles-preset-1cpiubp"}
																data-styles-preset={"pBZIe2bTg"}
																style={{
																	"--framer-text-color":
																		"var(--extracted-a0htzi, var(--token-9d9c37d5-31f4-4564-b2ab-c0d257f64cbd, rgb(250, 250, 250)))",
																}}
															>
																{"$299/m"}
															</motion3.h3>
														</React3.Fragment>
													),
												},
												wE074X52U: {
													children: (
														<React3.Fragment>
															<motion3.h3
																className={"framer-styles-preset-1cpiubp"}
																data-styles-preset={"pBZIe2bTg"}
																style={{
																	"--framer-text-color":
																		"var(--extracted-a0htzi, var(--token-9d9c37d5-31f4-4564-b2ab-c0d257f64cbd, rgb(250, 250, 250)))",
																}}
															>
																{"$299/m"}
															</motion3.h3>
														</React3.Fragment>
													),
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React3.Fragment>
											<motion3.h3
												className={"framer-styles-preset-1cpiubp"}
												data-styles-preset={"pBZIe2bTg"}
												style={{
													"--framer-text-color":
														"var(--extracted-a0htzi, var(--token-9d9c37d5-31f4-4564-b2ab-c0d257f64cbd, rgb(250, 250, 250)))",
												}}
											>
												{"$499/m"}
											</motion3.h3>
										</React3.Fragment>
									</RichText3>
									<ComponentViewportProvider
										height={50}
										width={`max(max(${componentViewport?.width || "100vw"} - 20px, 1px) - 48px, 1px)`}
										y={
											(componentViewport?.y || 0) +
											(10 +
												((componentViewport?.height || 538) - 20 - 516.4) / 2) +
											32 +
											0 +
											0 +
											0 +
											120.4
										}
									>
										<SmartComponentScopedContainer
											className={"framer-12bun4g-container"}
											layoutDependency={layoutDependency}
											layoutId={"yuBkeUQhx-container"}
											nodeId={"yuBkeUQhx"}
											rendersWithMotion={true}
											scopeId={"vT6twQNZ5"}
										>
											{_jsx3(stdin_default, {
												height: "100%",
												i8ZiYu6Ux: "Get Started",
												id: "yuBkeUQhx",
												layoutId: "yuBkeUQhx",
												N0JqvxlHe: dmF22hZf12,
												QmLq7qL0a: AWI2viap72,
												style: {
													width: "100%",
												},
												variant: "rRNOwUIqZ",
												width: "100%",
												...addPropertyOverrides3(
													{
														n4cc0Kdzs: {
															variant: "f3juxeP0X",
														},
														TGNT2vw2f: {
															variant: "kThEC4yoW",
														},
														wE074X52U: {
															variant: "HGRAy6hKU",
														},
													},
													baseVariant,
													gestureVariant,
												),
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion3.div>
								<motion3.div
									className={"framer-1swz943"}
									data-framer-name={"Bottom"}
									layoutDependency={layoutDependency}
									layoutId={"oLzyhorOR"}
								>
									<ComponentViewportProvider
										height={22}
										y={
											(componentViewport?.y || 0) +
											(10 +
												((componentViewport?.height || 538) - 20 - 516.4) / 2) +
											32 +
											0 +
											202.4 +
											0 +
											0
										}
									>
										<SmartComponentScopedContainer
											className={"framer-n66g7g-container"}
											layoutDependency={layoutDependency}
											layoutId={"OgIGrA0Ml-container"}
											nodeId={"OgIGrA0Ml"}
											rendersWithMotion={true}
											scopeId={"vT6twQNZ5"}
										>
											{_jsx3(stdin_default3, {
												height: "100%",
												id: "OgIGrA0Ml",
												layoutId: "OgIGrA0Ml",
												ualVz9QLA: "Full course access",
												variant: "CuwHe5C5P",
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
									<ComponentViewportProvider
										height={22}
										y={
											(componentViewport?.y || 0) +
											(10 +
												((componentViewport?.height || 538) - 20 - 516.4) / 2) +
											32 +
											0 +
											202.4 +
											0 +
											38
										}
									>
										<SmartComponentScopedContainer
											className={"framer-1ulqir8-container"}
											layoutDependency={layoutDependency}
											layoutId={"z_iTte52s-container"}
											nodeId={"z_iTte52s"}
											rendersWithMotion={true}
											scopeId={"vT6twQNZ5"}
										>
											{_jsx3(stdin_default3, {
												height: "100%",
												id: "z_iTte52s",
												layoutId: "z_iTte52s",
												ualVz9QLA: "Video tutorials",
												variant: "CuwHe5C5P",
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
									<ComponentViewportProvider
										height={22}
										y={
											(componentViewport?.y || 0) +
											(10 +
												((componentViewport?.height || 538) - 20 - 516.4) / 2) +
											32 +
											0 +
											202.4 +
											0 +
											76
										}
									>
										<SmartComponentScopedContainer
											className={"framer-h4u1c7-container"}
											layoutDependency={layoutDependency}
											layoutId={"yEofLzowX-container"}
											nodeId={"yEofLzowX"}
											rendersWithMotion={true}
											scopeId={"vT6twQNZ5"}
										>
											{_jsx3(stdin_default3, {
												height: "100%",
												id: "yEofLzowX",
												layoutId: "yEofLzowX",
												ualVz9QLA: "Mentor support",
												variant: "CuwHe5C5P",
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
									<ComponentViewportProvider
										height={22}
										y={
											(componentViewport?.y || 0) +
											(10 +
												((componentViewport?.height || 538) - 20 - 516.4) / 2) +
											32 +
											0 +
											202.4 +
											0 +
											114
										}
									>
										<SmartComponentScopedContainer
											className={"framer-y142m5-container"}
											layoutDependency={layoutDependency}
											layoutId={"JO2wICXRm-container"}
											nodeId={"JO2wICXRm"}
											rendersWithMotion={true}
											scopeId={"vT6twQNZ5"}
										>
											{_jsx3(stdin_default3, {
												height: "100%",
												id: "JO2wICXRm",
												layoutId: "JO2wICXRm",
												ualVz9QLA: "Community access",
												variant: "CuwHe5C5P",
												width: "100%",
												...addPropertyOverrides3(
													{
														TGNT2vw2f: {
															variant: "S49JJMjML",
														},
														wE074X52U: {
															variant: "S49JJMjML",
														},
													},
													baseVariant,
													gestureVariant,
												),
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
									<ComponentViewportProvider
										height={22}
										y={
											(componentViewport?.y || 0) +
											(10 +
												((componentViewport?.height || 538) - 20 - 516.4) / 2) +
											32 +
											0 +
											202.4 +
											0 +
											152
										}
									>
										<SmartComponentScopedContainer
											className={"framer-3uiwq2-container"}
											layoutDependency={layoutDependency}
											layoutId={"LvAIoSX4X-container"}
											nodeId={"LvAIoSX4X"}
											rendersWithMotion={true}
											scopeId={"vT6twQNZ5"}
										>
											{_jsx3(stdin_default3, {
												height: "100%",
												id: "LvAIoSX4X",
												layoutId: "LvAIoSX4X",
												ualVz9QLA: "Downloadable resources",
												variant: "CuwHe5C5P",
												width: "100%",
												...addPropertyOverrides3(
													{
														TGNT2vw2f: {
															variant: "S49JJMjML",
														},
														wE074X52U: {
															variant: "S49JJMjML",
														},
													},
													baseVariant,
													gestureVariant,
												),
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
									<ComponentViewportProvider
										height={22}
										y={
											(componentViewport?.y || 0) +
											(10 +
												((componentViewport?.height || 538) - 20 - 516.4) / 2) +
											32 +
											0 +
											202.4 +
											0 +
											190
										}
									>
										<SmartComponentScopedContainer
											className={"framer-pv4lmj-container"}
											layoutDependency={layoutDependency}
											layoutId={"b4G29pZos-container"}
											nodeId={"b4G29pZos"}
											rendersWithMotion={true}
											scopeId={"vT6twQNZ5"}
										>
											{_jsx3(stdin_default3, {
												height: "100%",
												id: "b4G29pZos",
												layoutId: "b4G29pZos",
												ualVz9QLA: "Course completion certificate",
												variant: "CuwHe5C5P",
												width: "100%",
												...addPropertyOverrides3(
													{
														TGNT2vw2f: {
															variant: "S49JJMjML",
														},
														wE074X52U: {
															variant: "S49JJMjML",
														},
													},
													baseVariant,
													gestureVariant,
												),
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
									<ComponentViewportProvider
										height={22}
										y={
											(componentViewport?.y || 0) +
											(10 +
												((componentViewport?.height || 538) - 20 - 516.4) / 2) +
											32 +
											0 +
											202.4 +
											0 +
											228
										}
									>
										<SmartComponentScopedContainer
											className={"framer-1ptdrcz-container"}
											layoutDependency={layoutDependency}
											layoutId={"YQBJNi4Qz-container"}
											nodeId={"YQBJNi4Qz"}
											rendersWithMotion={true}
											scopeId={"vT6twQNZ5"}
										>
											{_jsx3(stdin_default3, {
												height: "100%",
												id: "YQBJNi4Qz",
												layoutId: "YQBJNi4Qz",
												ualVz9QLA: "Job and client support",
												variant: "CuwHe5C5P",
												width: "100%",
												...addPropertyOverrides3(
													{
														TGNT2vw2f: {
															variant: "S49JJMjML",
														},
														wE074X52U: {
															variant: "S49JJMjML",
														},
													},
													baseVariant,
													gestureVariant,
												),
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion3.div>
							</motion3.div>
						</motion3.div>
						<motion3.div
							className={"framer-1k9mgh0"}
							data-framer-name={"Glow"}
							layoutDependency={layoutDependency}
							layoutId={"HeOh8u9sY"}
							style={{
								background:
									"linear-gradient(180deg, var(--token-d4c36658-1f4b-41b3-aa0d-cf9b918d88bf, rgb(0, 122, 187)) -79%, var(--token-efc840ff-64db-4d68-b4f9-ffd23b298cd4, rgba(255, 255, 255, 0.05)) 438%)",
								borderBottomLeftRadius: "100%",
								borderBottomRightRadius: "100%",
								borderTopLeftRadius: "100%",
								borderTopRightRadius: "100%",
								filter: "blur(51px)",
								opacity: 0.23,
								WebkitFilter: "blur(51px)",
							}}
						/>
					</motion3.div>
				</Transition3>
			</Variants3>
		</LayoutGroup3>
	);
});
var css6 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-fEGsO.framer-1x7qazi, .framer-fEGsO .framer-1x7qazi { display: block; }",
	".framer-fEGsO.framer-didhff { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 10px; position: relative; width: 466px; will-change: var(--framer-will-change-override, transform); }",
	".framer-fEGsO .framer-pymyhn { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; padding: 32px 24px 32px 24px; position: relative; width: 1px; }",
	".framer-fEGsO .framer-qfdejo { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-fEGsO .framer-gaujbj { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-fEGsO .framer-ep9c6q-container, .framer-fEGsO .framer-n66g7g-container, .framer-fEGsO .framer-1ulqir8-container, .framer-fEGsO .framer-h4u1c7-container, .framer-fEGsO .framer-y142m5-container, .framer-fEGsO .framer-3uiwq2-container, .framer-fEGsO .framer-pv4lmj-container, .framer-fEGsO .framer-1ptdrcz-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-fEGsO .framer-1crut6l { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-fEGsO .framer-12bun4g-container { flex: none; height: auto; position: relative; width: 100%; }",
	".framer-fEGsO .framer-1swz943 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 262px; }",
	".framer-fEGsO .framer-1k9mgh0 { bottom: 0px; flex: none; height: 48px; left: calc(50.21459227467814% - 93.99141630901288% / 2); mix-blend-mode: lighten; position: absolute; width: 94%; z-index: 1; }",
	...css,
	'.framer-fEGsO[data-border="true"]::after, .framer-fEGsO [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramervT6twQNZ5 = withCSS3(Component3, css6, "framer-fEGsO");
var stdin_default5 = FramervT6twQNZ5;
FramervT6twQNZ5.displayName = "Price card";
FramervT6twQNZ5.defaultProps = {
	height: 538,
	width: 466,
};
addPropertyControls3(FramervT6twQNZ5, {
	variant: {
		options: ["BqP4oPxA0", "wE074X52U", "n4cc0Kdzs", "TGNT2vw2f"],
		optionTitles: [
			"Pro Plan- L",
			"Basic Plan - L",
			"Pro Plan - M/S",
			"Basic Plan - M/S",
		],
		title: "Variant",
		type: ControlType3.Enum,
	},
	AWI2viap7: {
		title: "Link",
		type: ControlType3.Link,
	},
	dmF22hZf1: {
		defaultValue: false,
		title: "New Tab",
		type: ControlType3.Boolean,
	},
});
addFonts3(
	FramervT6twQNZ5,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...TagSFonts,
		...PrimaryButtonFonts,
		...PointFonts,
		...getFontsFromSharedStyle3(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:price-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "TGNT2vw2f",
	xl: "BqP4oPxA0",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5af1700726b89e1359bd903da3e469ba956b8fc7e56af575f49bcf468e7d9c62"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default5, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders PriceCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5af1700726b89e1359bd903da3e469ba956b8fc7e56af575f49bcf468e7d9c62"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default5}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default5);
var price_card_default = ComponentWithRoot;
export { price_card_default as default };
