// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5af1700726b89e13 "Cliplab Studio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Variant 2' // Variant
}} Props

 */
import { routes } from "./chunks/chunk-2NVZ5JSA.js";

// virtual:pulse
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/bopSEgpKVmfRfl6TNFd2/0I8RJRsyINPKdZu0shhM/TPNcOVgXV.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	CycleVariantState,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useOnVariantChange,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["RdhBPZ1br", "hR7mTTiVF"];
var serializationHash = "framer-Wvij9";
var variantClassNames = {
	hR7mTTiVF: "framer-v-1nl0mri",
	RdhBPZ1br: "framer-v-byrenq",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 2,
	ease: [0, 0, 1, 1],
	type: "tween",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Variant 1": "RdhBPZ1br",
	"Variant 2": "hR7mTTiVF",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "RdhBPZ1br",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "RdhBPZ1br",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onAppear1exxk5q = activeVariantCallback(async (...args) => {
		await delay(() => setVariant(CycleVariantState, true), 2e3);
	});
	useOnVariantChange(baseVariant, {
		default: onAppear1exxk5q,
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-byrenq",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"RdhBPZ1br"}
						ref={refBinding}
						style={{
							opacity: 1,
							...style,
						}}
						variants={{
							hR7mTTiVF: {
								opacity: 0.29,
							},
						}}
						{...addPropertyOverrides(
							{
								hR7mTTiVF: {
									"data-framer-name": "Variant 2",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-15c53ft"}
							data-framer-name={"Indicator"}
							layoutDependency={layoutDependency}
							layoutId={"fZCkHQmuX"}
							style={{
								backgroundColor:
									"var(--token-d4c36658-1f4b-41b3-aa0d-cf9b918d88bf, rgb(0, 122, 187))",
								borderBottomLeftRadius: 141,
								borderBottomRightRadius: 141,
								borderTopLeftRadius: 141,
								borderTopRightRadius: 141,
								boxShadow:
									"0px 0px 10px 0px rgb(0, 122, 187), 0px 0px 20px 0px var(--token-d4c36658-1f4b-41b3-aa0d-cf9b918d88bf, rgb(0, 122, 187))",
							}}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-Wvij9.framer-4ag176, .framer-Wvij9 .framer-4ag176 { display: block; }",
	".framer-Wvij9.framer-byrenq { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 12px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 12px; }",
	".framer-Wvij9 .framer-15c53ft { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 8px); overflow: var(--overflow-clip-fallback, clip); position: relative; width: 8px; will-change: var(--framer-will-change-override, transform); }",
	".framer-Wvij9.framer-v-1nl0mri .framer-15c53ft { width: 6px; }",
];
var FramerTPNcOVgXV = withCSS(Component, css, "framer-Wvij9");
var stdin_default = FramerTPNcOVgXV;
FramerTPNcOVgXV.displayName = "Pulse";
FramerTPNcOVgXV.defaultProps = {
	height: 12,
	width: 12,
};
addPropertyControls(FramerTPNcOVgXV, {
	variant: {
		options: ["RdhBPZ1br", "hR7mTTiVF"],
		optionTitles: ["Variant 1", "Variant 2"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerTPNcOVgXV,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:pulse
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "RdhBPZ1br",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5af1700726b89e1359bd903da3e469ba956b8fc7e56af575f49bcf468e7d9c62"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders PulseFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5af1700726b89e1359bd903da3e469ba956b8fc7e56af575f49bcf468e7d9c62"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var pulse_default = ComponentWithRoot;
export { pulse_default as default };
