// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5af1700726b89e13 "Cliplab Studio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'L' | 'M/S' // Variant
 * link?: string // Link
 * icon?: any // Icon
}} Props

 */
import { stdin_default } from "./chunks/chunk-PQK5NHI5.js";
import { routes } from "./chunks/chunk-2NVZ5JSA.js";

// virtual:social-link
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/1DldDr944SVJgZfckMaB/3V2r0v0GXUSM1ZgyrK1K/hgFp856mu.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	Instance,
	Link,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var enabledGestures = {
	NYa5mqssh: {
		hover: true,
	},
};
var cycleOrder = ["NYa5mqssh", "vmA_D6XNE"];
var serializationHash = "framer-40AoQ";
var variantClassNames = {
	NYa5mqssh: "framer-v-6ztg49",
	vmA_D6XNE: "framer-v-lfk1yt",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 80,
	delay: 0,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"M/S": "vmA_D6XNE",
	L: "NYa5mqssh",
};
var getProps = ({ height, icon, id, link, width, ...props }) => {
	return {
		...props,
		HNjNxwYxi: link ?? props.HNjNxwYxi,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "NYa5mqssh",
		Y9NktqVWj: icon ?? props.Y9NktqVWj ?? stdin_default,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		HNjNxwYxi: HNjNxwYxi2,
		Y9NktqVWj: Y9NktqVWj2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "NYa5mqssh",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={HNjNxwYxi2}
						motionChild={true}
						nodeId={"NYa5mqssh"}
						openInNewTab={false}
						scopeId={"hgFp856mu"}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							aria-label={"Social button"}
							className={`${cx(scopingClassNames, "framer-6ztg49", className, classNames)} framer-aag9xi`}
							data-border={true}
							data-framer-name={"L"}
							layoutDependency={layoutDependency}
							layoutId={"NYa5mqssh"}
							ref={refBinding}
							style={{
								"--border-bottom-width": "1px",
								"--border-color":
									"var(--token-cb2206d2-93ba-4bbf-8a99-2fb6eb742230, rgba(255, 255, 255, 0.1))",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								backgroundColor:
									"var(--token-efc840ff-64db-4d68-b4f9-ffd23b298cd4, rgba(255, 255, 255, 0.05))",
								borderBottomLeftRadius: 211,
								borderBottomRightRadius: 211,
								borderTopLeftRadius: 211,
								borderTopRightRadius: 211,
								...style,
							}}
							{...addPropertyOverrides(
								{
									"NYa5mqssh-hover": {
										"data-framer-name": void 0,
									},
									vmA_D6XNE: {
										"data-framer-name": "M/S",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-x32lbb"}
								data-framer-name={"Icon"}
								layoutDependency={layoutDependency}
								layoutId={"NDxFf26sP"}
							>
								<Instance
									animated={true}
									className={"framer-z87lts"}
									Component={Y9NktqVWj2}
									layoutDependency={layoutDependency}
									layoutId={"jZNkEnGKf"}
									style={{
										"--1m6trwb": 0.1,
										"--21h8s6":
											"var(--token-b1f5477e-0c35-4cdc-8900-c9aed722522e, rgb(168, 168, 168))",
										"--pgex8v": 1.5,
										filter: "blur(0px)",
										WebkitFilter: "blur(0px)",
									}}
									variants={{
										"NYa5mqssh-hover": {
											filter: "blur(5px)",
											WebkitFilter: "blur(5px)",
										},
									}}
									{...addPropertyOverrides(
										{
											"NYa5mqssh-hover": {
												transformTemplate: transformTemplate1,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
								<Instance
									animated={true}
									className={"framer-tzrq83"}
									Component={Y9NktqVWj2}
									layoutDependency={layoutDependency}
									layoutId={"ADSFyuDxe"}
									style={{
										"--1m6trwb": 0.1,
										"--21h8s6":
											"var(--token-b1f5477e-0c35-4cdc-8900-c9aed722522e, rgb(168, 168, 168))",
										"--pgex8v": 1.5,
										filter: "blur(5px)",
										WebkitFilter: "blur(5px)",
									}}
									transformTemplate={transformTemplate1}
									variants={{
										"NYa5mqssh-hover": {
											filter: "blur(0px)",
											WebkitFilter: "blur(0px)",
										},
									}}
									{...addPropertyOverrides(
										{
											"NYa5mqssh-hover": {
												transformTemplate: void 0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							</motion.div>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-40AoQ.framer-aag9xi, .framer-40AoQ .framer-aag9xi { display: block; }",
	".framer-40AoQ.framer-6ztg49 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 34px; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 4px; position: relative; text-decoration: none; width: 34px; will-change: var(--framer-will-change-override, transform); }",
	".framer-40AoQ .framer-x32lbb { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-40AoQ .framer-z87lts { flex: none; height: var(--framer-aspect-ratio-supported, 20px); position: relative; width: 20px; }",
	".framer-40AoQ .framer-tzrq83 { aspect-ratio: 1 / 1; bottom: -30px; flex: none; height: var(--framer-aspect-ratio-supported, 20px); left: 50%; position: absolute; width: 20px; z-index: 1; }",
	".framer-40AoQ.framer-v-lfk1yt.framer-6ztg49 { aspect-ratio: 1 / 1; cursor: unset; height: var(--framer-aspect-ratio-supported, 34px); }",
	".framer-40AoQ.framer-v-6ztg49.hover.framer-6ztg49 { aspect-ratio: 1 / 1; height: var(--framer-aspect-ratio-supported, 34px); }",
	".framer-40AoQ.framer-v-6ztg49.hover .framer-z87lts { aspect-ratio: 1 / 1; left: 50%; position: absolute; top: -30px; z-index: 1; }",
	".framer-40AoQ.framer-v-6ztg49.hover .framer-tzrq83 { bottom: unset; left: unset; position: relative; }",
	'.framer-40AoQ[data-border="true"]::after, .framer-40AoQ [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramerhgFp856mu = withCSS(Component, css, "framer-40AoQ");
var stdin_default2 = FramerhgFp856mu;
FramerhgFp856mu.displayName = "Social  Link";
FramerhgFp856mu.defaultProps = {
	height: 34,
	width: 34,
};
addPropertyControls(FramerhgFp856mu, {
	variant: {
		options: ["NYa5mqssh", "vmA_D6XNE"],
		optionTitles: ["L", "M/S"],
		title: "Variant",
		type: ControlType.Enum,
	},
	HNjNxwYxi: {
		title: "Link",
		type: ControlType.Link,
	},
	Y9NktqVWj: {
		defaultValue: {
			identifier:
				"module:oMiuMYAdxzz5yk7pBqrm/j2eV5wGWikO42mvtQ2hM/Xx_sbLkzD.js:default",
			moduleId: "oMiuMYAdxzz5yk7pBqrm",
		},
		setModuleId: "omX0gWFPqDwhaiWwf6ab",
		title: "Icon",
		type: ControlType.VectorSetItem,
	},
});
addFonts(
	FramerhgFp856mu,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:social-link
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "NYa5mqssh",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5af1700726b89e1359bd903da3e469ba956b8fc7e56af575f49bcf468e7d9c62"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders SocialLinkFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5af1700726b89e1359bd903da3e469ba956b8fc7e56af575f49bcf468e7d9c62"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var social_link_default = ComponentWithRoot;
export { social_link_default as default };
