// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5af1700726b89e13 "Cliplab Studio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * image1?: {src: string, srcSet?: string, alt?: string} // Image 1
 * image2?: {src: string, srcSet?: string, alt?: string} // Image 2
 * image3?: {src: string, srcSet?: string, alt?: string} // Image 3
 * text?: string // Text
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-ZOSDNJUM.js";
import { routes } from "./chunks/chunk-2NVZ5JSA.js";

// virtual:social-proof
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/8yD46ZSIjKRpb7K12Fcz/i7XWPTgudvX8kTmQdJ17/gp0kzCXaX.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var serializationHash = "framer-kyVs5";
var variantClassNames = {
	afXW92sbm: "framer-v-1efkcfz",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({
	height,
	id,
	image1,
	image2,
	image3,
	text,
	width,
	...props
}) => {
	return {
		...props,
		eQNsDD0um: image3 ??
			props.eQNsDD0um ?? {
				alt: "",
				pixelHeight: 1200,
				pixelWidth: 1200,
				src: "https://framerusercontent.com/images/aa6F4I64EHJQymlFqeyPDtoPshM.png?width=1200&height=1200",
				srcSet:
					"https://framerusercontent.com/images/aa6F4I64EHJQymlFqeyPDtoPshM.png?scale-down-to=512&width=1200&height=1200 512w,https://framerusercontent.com/images/aa6F4I64EHJQymlFqeyPDtoPshM.png?scale-down-to=1024&width=1200&height=1200 1024w,https://framerusercontent.com/images/aa6F4I64EHJQymlFqeyPDtoPshM.png?width=1200&height=1200 1200w",
			},
		ETJt__o2i: text ?? props.ETJt__o2i ?? "Trusted by 1000+Creators",
		JjX56dYhA: image1 ??
			props.JjX56dYhA ?? {
				alt: "",
				pixelHeight: 1200,
				pixelWidth: 800,
				positionX: "53.4%",
				positionY: "28.2%",
				src: "https://framerusercontent.com/images/C6DsKyUobYmm4QkeIkaKbGn9Lw.png?width=800&height=1200",
				srcSet:
					"https://framerusercontent.com/images/C6DsKyUobYmm4QkeIkaKbGn9Lw.png?scale-down-to=1024&width=800&height=1200 682w,https://framerusercontent.com/images/C6DsKyUobYmm4QkeIkaKbGn9Lw.png?width=800&height=1200 800w",
			},
		kY09Azv1n: image2 ??
			props.kY09Azv1n ?? {
				alt: "",
				pixelHeight: 1200,
				pixelWidth: 900,
				positionX: "38.4%",
				positionY: "12.9%",
				src: "https://framerusercontent.com/images/XphQxYk0C9EiQhruJTxLJF2hSM.png?width=900&height=1200",
				srcSet:
					"https://framerusercontent.com/images/XphQxYk0C9EiQhruJTxLJF2hSM.png?scale-down-to=1024&width=900&height=1200 768w,https://framerusercontent.com/images/XphQxYk0C9EiQhruJTxLJF2hSM.png?width=900&height=1200 900w",
			},
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		JjX56dYhA: JjX56dYhA2,
		kY09Azv1n: kY09Azv1n2,
		eQNsDD0um: eQNsDD0um2,
		ETJt__o2i: ETJt__o2i2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "afXW92sbm",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1efkcfz",
							className2,
							classNames,
						)}
						data-framer-name={"Large"}
						layoutDependency={layoutDependency}
						layoutId={"afXW92sbm"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<motion.div
							className={"framer-ej8mxv"}
							data-framer-name={"Images"}
							layoutDependency={layoutDependency}
							layoutId={"cnCMgDtio"}
						>
							<Image
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											(0 + ((componentViewport?.height || 30) - 0 - 0) / 2) +
											0,
									),
									pixelHeight: 1200,
									pixelWidth: 800,
									sizes: "0px",
									...toResponsiveImage(JjX56dYhA2),
								}}
								className={"framer-vfyrkm"}
								data-border={true}
								data-framer-name={"Image 1"}
								layoutDependency={layoutDependency}
								layoutId={"C10j5Paqt"}
								style={{
									"--border-bottom-width": "2px",
									"--border-color":
										"var(--token-cd811638-c7a7-467a-a0d6-438332270fd5, rgb(0, 1, 3))",
									"--border-left-width": "2px",
									"--border-right-width": "2px",
									"--border-style": "solid",
									"--border-top-width": "2px",
									borderBottomLeftRadius: "100%",
									borderBottomRightRadius: "100%",
									borderTopLeftRadius: "100%",
									borderTopRightRadius: "100%",
								}}
							/>
							<Image
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											(0 + ((componentViewport?.height || 30) - 0 - 0) / 2) +
											0,
									),
									pixelHeight: 1200,
									pixelWidth: 900,
									sizes: "0px",
									...toResponsiveImage(kY09Azv1n2),
								}}
								className={"framer-vgmvhp"}
								data-border={true}
								data-framer-name={"Image 2"}
								layoutDependency={layoutDependency}
								layoutId={"yUM4qkC6Y"}
								style={{
									"--border-bottom-width": "2px",
									"--border-color":
										"var(--token-cd811638-c7a7-467a-a0d6-438332270fd5, rgb(0, 1, 3))",
									"--border-left-width": "2px",
									"--border-right-width": "2px",
									"--border-style": "solid",
									"--border-top-width": "2px",
									borderBottomLeftRadius: "100%",
									borderBottomRightRadius: "100%",
									borderTopLeftRadius: "100%",
									borderTopRightRadius: "100%",
								}}
								transformTemplate={transformTemplate1}
							/>
							<Image
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											(0 + ((componentViewport?.height || 30) - 0 - 0) / 2) +
											0,
									),
									pixelHeight: 1200,
									pixelWidth: 1200,
									sizes: "0px",
									...toResponsiveImage(eQNsDD0um2),
								}}
								className={"framer-1shzrpl"}
								data-border={true}
								data-framer-name={"Image 3"}
								layoutDependency={layoutDependency}
								layoutId={"MY7U1PBaT"}
								style={{
									"--border-bottom-width": "2px",
									"--border-color":
										"var(--token-cd811638-c7a7-467a-a0d6-438332270fd5, rgb(0, 1, 3))",
									"--border-left-width": "2px",
									"--border-right-width": "2px",
									"--border-style": "solid",
									"--border-top-width": "2px",
									borderBottomLeftRadius: "100%",
									borderBottomRightRadius: "100%",
									borderTopLeftRadius: "100%",
									borderTopRightRadius: "100%",
								}}
							/>
						</motion.div>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1szs3zy"}
							data-framer-name={"Trusted by 1000+Creators"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"AMYVCcJHT"}
							style={{
								"--framer-paragraph-spacing": "0px",
							}}
							text={ETJt__o2i2}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-1h481q3"}
									data-styles-preset={"uWgmT59JL"}
								>
									{"Trusted by 1000+Creators"}
								</motion.p>
							</React.Fragment>
						</RichText>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-kyVs5.framer-1iw4m8b, .framer-kyVs5 .framer-1iw4m8b { display: block; }",
	".framer-kyVs5.framer-1efkcfz { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: visible; padding: 0px 2px 0px 2px; position: relative; width: min-content; }",
	".framer-kyVs5 .framer-ej8mxv { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; min-height: 30px; min-width: 66px; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-kyVs5 .framer-vfyrkm { aspect-ratio: 1 / 1; bottom: 0px; flex: none; left: 0px; position: absolute; top: 0px; width: var(--framer-aspect-ratio-supported, 30px); z-index: 1; }",
	".framer-kyVs5 .framer-vgmvhp { aspect-ratio: 1 / 1; bottom: 0px; flex: none; left: 50%; position: absolute; top: 0px; width: var(--framer-aspect-ratio-supported, 30px); z-index: 1; }",
	".framer-kyVs5 .framer-1shzrpl { aspect-ratio: 1 / 1; bottom: 0px; flex: none; position: absolute; right: 0px; top: 0px; width: var(--framer-aspect-ratio-supported, 30px); z-index: 1; }",
	".framer-kyVs5 .framer-1szs3zy { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	...css,
	'.framer-kyVs5[data-border="true"]::after, .framer-kyVs5 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var Framergp0kzCXaX = withCSS(Component, css2, "framer-kyVs5");
var stdin_default = Framergp0kzCXaX;
Framergp0kzCXaX.displayName = "Social Proof";
Framergp0kzCXaX.defaultProps = {
	height: 30,
	width: 251,
};
addPropertyControls(Framergp0kzCXaX, {
	JjX56dYhA: {
		__defaultAssetReference:
			"data:framer/asset-reference,C6DsKyUobYmm4QkeIkaKbGn9Lw.png?originalFilename=Portrait+of+a+Young+Woman.png&width=800&height=1200",
		__vekterDefault: {
			alt: "",
			assetReference:
				"data:framer/asset-reference,C6DsKyUobYmm4QkeIkaKbGn9Lw.png?originalFilename=Portrait+of+a+Young+Woman.png&width=800&height=1200",
			positionX: "53.4%",
			positionY: "28.2%",
		},
		title: "Image 1",
		type: ControlType.ResponsiveImage,
	},
	kY09Azv1n: {
		__defaultAssetReference:
			"data:framer/asset-reference,XphQxYk0C9EiQhruJTxLJF2hSM.png?originalFilename=Portrait+of+a+Man.png&width=900&height=1200",
		__vekterDefault: {
			alt: "",
			assetReference:
				"data:framer/asset-reference,XphQxYk0C9EiQhruJTxLJF2hSM.png?originalFilename=Portrait+of+a+Man.png&width=900&height=1200",
			positionX: "38.4%",
			positionY: "12.9%",
		},
		title: "Image 2",
		type: ControlType.ResponsiveImage,
	},
	eQNsDD0um: {
		__defaultAssetReference:
			"data:framer/asset-reference,aa6F4I64EHJQymlFqeyPDtoPshM.png?originalFilename=Young+Man+in+Focus.png&width=1200&height=1200",
		__vekterDefault: {
			alt: "",
			assetReference:
				"data:framer/asset-reference,aa6F4I64EHJQymlFqeyPDtoPshM.png?originalFilename=Young+Man+in+Focus.png&width=1200&height=1200",
		},
		title: "Image 3",
		type: ControlType.ResponsiveImage,
	},
	ETJt__o2i: {
		defaultValue: "Trusted by 1000+Creators",
		displayTextArea: false,
		title: "Text",
		type: ControlType.String,
	},
});
addFonts(
	Framergp0kzCXaX,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:social-proof
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5af1700726b89e1359bd903da3e469ba956b8fc7e56af575f49bcf468e7d9c62"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders SocialProofFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5af1700726b89e1359bd903da3e469ba956b8fc7e56af575f49bcf468e7d9c62"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var social_proof_default = ComponentWithRoot;
export { social_proof_default as default };
