// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5af1700726b89e13 "Cliplab Studio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * startNumber?: number // Start Number
 * endNumber?: number // End Number
 * prefix?: string // Prefix
 * suffix?: string // Suffix
 * title?: string // Title
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-NORUQDUQ.js";
import { routes } from "./chunks/chunk-2NVZ5JSA.js";

// virtual:statistics
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/b1e5WTfxrz8SUeFsT9PY/ttANeVsX7TcVctxMx5Xx/Q6a0915ST.js
import { jsx as _jsx, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion as motion2, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/qpjhCcDm4G1NbFAlpMKV/OnyZiTlIjOBuSKcKQWFv/AnimatedNumberCounter_Prod.js
import { jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { addPropertyControls, ControlType, RenderTarget } from "unframer";
import { useEffect, useState, useRef } from "react";
import { motion, useMotionValue, animate, useInView } from "unframer";
function AnimatedNumberCounter(props) {
	const { mode, start, end, value, decimals, commas, color, animation } = props;
	const isCanvas = RenderTarget.current() === RenderTarget.canvas;
	const Tag = props.tag;
	const MotionTag = motion[props.tag];
	const isDefault = mode == "default";
	const initialValue = isDefault ? start : value;
	const transition = isDefault ? animation.transition : props.transition;
	const formatNumber = (number2) => {
		let numberString = number2.toFixed(decimals);
		if (commas) {
			numberString = numberString.replace(/\B(?=(\d{3})+(?!\d))/g, ",");
		}
		return numberString;
	};
	const [number, setNumber] = useState(initialValue);
	const [finalValue, setFinalValue] = useState(number);
	const [currentAnimation, setCurrentAnimation] = useState(null);
	const ref = useRef(null);
	const isInView = useInView(ref, {
		once: !props.animation.replay,
		amount: "some",
	});
	const motionValue = useMotionValue(value);
	const runAnimation = (from, to) => {
		if (!isCanvas) {
			if (currentAnimation) {
				currentAnimation.stop();
			}
			setFinalValue(to);
			setCurrentAnimation(
				animate(from, to, {
					...transition,
					onUpdate: (latest) => {
						setNumber(latest);
					},
				}),
			);
		}
	};
	useEffect(() => {
		if (isDefault && animation.trigger == "appear") {
			runAnimation(start, end);
		}
	}, []);
	useEffect(() => {
		if (isDefault && animation.trigger == "layerInView") {
			if (isInView) {
				runAnimation(start, end);
			} else {
				if (currentAnimation) {
					currentAnimation.stop();
				}
				setNumber(start);
			}
		}
	}, [isInView]);
	useEffect(() => {
		if (!isDefault) {
			runAnimation(number, value);
		}
	}, [value]);
	return (
		<_Fragment>
			<Tag
				style={{
					...props.style,
					margin: 0,
					opacity: 0,
					pointerEvents: "none",
					userSelect: "none",
					textWrap: props.balance ? "balance" : void 0,
					fontVariantNumeric: props.monospace ? "tabular-nums" : void 0,
					textAlign: "center",
					...props.font,
				}}
			>
				{props.prefix}
				{formatNumber(isCanvas ? initialValue : finalValue)}
				{props.suffix}
			</Tag>
			<MotionTag
				ref={ref}
				style={{
					position: "absolute",
					inset: 0,
					userSelect: props.userSelect ? "auto" : "none",
					fontVariantNumeric: props.monospace ? "tabular-nums" : void 0,
					margin: 0,
					...(color.mode == "solid"
						? {
								color: color.color,
							}
						: {
								WebkitBackgroundClip: "text",
								WebkitTextFillColor: "transparent",
								backgroundImage: `linear-gradient(${color.angle}deg, ${color.startColor}, ${color.endColor})`,
							}),
					textDecoration: props.decoration,
					textWrap: props.balance ? "balance" : void 0,
					textAlign: "center",
					...props.font,
					...props.style,
				}}
			>
				{props.prefix}
				{formatNumber(isCanvas ? initialValue : number)}
				{props.suffix}
			</MotionTag>
		</_Fragment>
	);
}
AnimatedNumberCounter.displayName = "Animated Number Counter";
addPropertyControls(AnimatedNumberCounter, {
	mode: {
		type: ControlType.Enum,
		options: ["default", "variants"],
		optionTitles: ["Default", "Variants"],
		displaySegmentedControl: true,
	},
	value: {
		type: ControlType.Number,
		defaultValue: 0,
		hidden: (props) => props.mode !== "variants",
	},
	start: {
		type: ControlType.Number,
		defaultValue: 0,
		hidden: (props) => props.mode !== "default",
	},
	end: {
		type: ControlType.Number,
		defaultValue: 100,
		hidden: (props) => props.mode !== "default",
	},
	animation: {
		type: ControlType.Object,
		icon: "effect",
		hidden: (props) => props.mode !== "default",
		controls: {
			trigger: {
				type: ControlType.Enum,
				defaultValue: "layerInView",
				options: ["appear", "layerInView"],
				optionTitles: ["Appear", "Layer in View"],
				displaySegmentedControl: true,
				segmentedControlDirection: "vertical",
			},
			replay: {
				type: ControlType.Boolean,
				defaultValue: true,
				hidden(props) {
					return props.trigger !== "layerInView";
				},
			},
			transition: {
				type: ControlType.Transition,
				defaultValue: {
					type: "spring",
					duration: 1,
					bounce: 0,
				},
			},
		},
	},
	transition: {
		type: ControlType.Transition,
		defaultValue: {
			type: "spring",
			duration: 1,
			bounce: 0,
		},
		hidden: (props) => props.mode !== "variants",
	},
	decimals: {
		type: ControlType.Enum,
		defaultValue: 0,
		options: [0, 1, 2, 3],
		optionTitles: ["Off", "1", "2", "3"],
		displaySegmentedControl: true,
	},
	commas: {
		type: ControlType.Boolean,
		defaultValue: true,
	},
	font: {
		type: "font",
		controls: "extended",
		defaultFontType: "sans-serif",
		defaultValue: {
			fontSize: 16,
			lineHeight: 1,
		},
	},
	color: {
		type: ControlType.Object,
		controls: {
			mode: {
				type: ControlType.Enum,
				defaultValue: "solid",
				options: ["solid", "gradient"],
				optionTitles: ["Solid", "Gradient"],
				displaySegmentedControl: true,
			},
			color: {
				type: ControlType.Color,
				defaultValue: "#000",
				hidden: (props) => props.mode !== "solid",
			},
			startColor: {
				type: ControlType.Color,
				defaultValue: "#000",
				hidden: (props) => props.mode !== "gradient",
			},
			endColor: {
				type: ControlType.Color,
				defaultValue: "#FFF",
				hidden: (props) => props.mode !== "gradient",
			},
			angle: {
				type: ControlType.Number,
				defaultValue: 180,
				min: -360,
				max: 360,
				unit: "\xB0",
				hidden: (props) => props.mode !== "gradient",
			},
		},
	},
	prefix: {
		type: ControlType.String,
		placeholder: "Prefix",
	},
	suffix: {
		type: ControlType.String,
		placeholder: "Suffix",
	},
	decoration: {
		type: ControlType.Enum,
		defaultValue: "none",
		options: ["none", "underline", "line-through"],
		optionTitles: ["None", "Underline", "Strikethrough"],
	},
	balance: {
		type: ControlType.Boolean,
		defaultValue: false,
	},
	userSelect: {
		type: ControlType.Boolean,
		defaultValue: true,
	},
	tag: {
		type: ControlType.Enum,
		defaultValue: "p",
		displaySegmentedControl: true,
		options: ["h1", "h2", "h3", "p"],
		optionTitles: ["H1", "H2", "H3", "P"],
	},
	monospace: {
		type: ControlType.Boolean,
		defaultValue: false,
		description:
			"More components at [Framer University](https://frameruni.link/cc).",
	},
});

// /:https://framerusercontent.com/modules/b1e5WTfxrz8SUeFsT9PY/ttANeVsX7TcVctxMx5Xx/Q6a0915ST.js
var AnimatedNumberCounterFonts = getFonts(AnimatedNumberCounter);
var serializationHash = "framer-7vPRj";
var variantClassNames = {
	buj5cP0Uo: "framer-v-19dghzp",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion2.create(React.Fragment);
var getProps = ({
	endNumber,
	height,
	id,
	prefix,
	startNumber,
	suffix,
	title,
	width,
	...props
}) => {
	return {
		...props,
		Hh8VMSdXH: endNumber ?? props.Hh8VMSdXH ?? 1500,
		jiFtBNGrU: prefix ?? props.jiFtBNGrU,
		TocVrJHlG: startNumber ?? props.TocVrJHlG,
		VhZFysNo0: suffix ?? props.VhZFysNo0 ?? "+",
		XPtJLY_4J: title ?? props.XPtJLY_4J ?? "Students trained worldwide",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		TocVrJHlG: TocVrJHlG2,
		Hh8VMSdXH: Hh8VMSdXH2,
		jiFtBNGrU: jiFtBNGrU2,
		VhZFysNo0: VhZFysNo02,
		XPtJLY_4J: XPtJLY_4J2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "buj5cP0Uo",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-19dghzp",
							className2,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"buj5cP0Uo"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<ComponentViewportProvider>
							<SmartComponentScopedContainer
								className={"framer-aw5spm-container"}
								isAuthoredByUser={true}
								isModuleExternal={true}
								layoutDependency={layoutDependency}
								layoutId={"lNiGAriyk-container"}
								nodeId={"lNiGAriyk"}
								rendersWithMotion={true}
								scopeId={"Q6a0915ST"}
							>
								<AnimatedNumberCounter
									animation={{
										replay: true,
										transition: {
											bounce: 0,
											delay: 0,
											duration: 1,
											type: "spring",
										},
										trigger: "layerInView",
									}}
									balance={false}
									color={{
										angle: 180,
										color:
											"var(--token-9d9c37d5-31f4-4564-b2ab-c0d257f64cbd, rgb(255, 255, 255))",
										endColor: "rgb(255, 255, 255)",
										mode: "solid",
										startColor: "rgb(0, 0, 0)",
									}}
									commas={true}
									decimals={0}
									decoration={"none"}
									end={Hh8VMSdXH2}
									font={{
										fontFamily: '"Inter", "Inter Placeholder", sans-serif',
										fontSize: "50px",
										fontStyle: "normal",
										fontWeight: 400,
										letterSpacing: "0em",
										lineHeight: "1em",
									}}
									height={"100%"}
									id={"lNiGAriyk"}
									layoutId={"lNiGAriyk"}
									mode={"default"}
									monospace={false}
									prefix={jiFtBNGrU2}
									start={TocVrJHlG2}
									suffix={VhZFysNo02}
									tag={"p"}
									transition={{
										bounce: 0,
										delay: 0,
										duration: 1,
										type: "spring",
									}}
									userSelect={true}
									value={0}
									width={"100%"}
								/>
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<motion2.div
							className={"framer-14xl942"}
							data-framer-name={"line"}
							layoutDependency={layoutDependency}
							layoutId={"cCzH5Ljo5"}
							style={{
								backgroundColor:
									"var(--token-cb2206d2-93ba-4bbf-8a99-2fb6eb742230, rgba(255, 255, 255, 0.1))",
								borderBottomLeftRadius: 3,
								borderBottomRightRadius: 3,
								borderTopLeftRadius: 3,
								borderTopRightRadius: 3,
							}}
						/>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-xmukem"}
							data-framer-name={"students trained worldwide"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"vJAdWNPRO"}
							style={{
								"--framer-paragraph-spacing": "0px",
							}}
							text={XPtJLY_4J2}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion2.p
									className={"framer-styles-preset-1ozhwx8"}
									data-styles-preset={"BsEnbfNw3"}
								>
									{"Students trained worldwide"}
								</motion2.p>
							</React.Fragment>
						</RichText>
					</motion2.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-7vPRj.framer-1vpwoev, .framer-7vPRj .framer-1vpwoev { display: block; }",
	".framer-7vPRj.framer-19dghzp { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-end; overflow: visible; padding: 0px; position: relative; width: 191px; }",
	".framer-7vPRj .framer-aw5spm-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-7vPRj .framer-14xl942 { flex: none; height: 1px; overflow: visible; position: relative; width: 100%; }",
	".framer-7vPRj .framer-xmukem { flex: none; height: auto; max-width: 200px; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	...css,
];
var FramerQ6a0915ST = withCSS(Component, css2, "framer-7vPRj");
var stdin_default = FramerQ6a0915ST;
FramerQ6a0915ST.displayName = "Statistics";
FramerQ6a0915ST.defaultProps = {
	height: 128,
	width: 191,
};
addPropertyControls2(FramerQ6a0915ST, {
	TocVrJHlG: {
		defaultValue: 0,
		title: "Start Number",
		type: ControlType2.Number,
	},
	Hh8VMSdXH: {
		defaultValue: 1500,
		title: "End Number",
		type: ControlType2.Number,
	},
	jiFtBNGrU: {
		defaultValue: "",
		placeholder: "Prefix",
		title: "Prefix",
		type: ControlType2.String,
	},
	VhZFysNo0: {
		defaultValue: "+",
		placeholder: "Suffix",
		title: "Suffix",
		type: ControlType2.String,
	},
	XPtJLY_4J: {
		defaultValue: "Students trained worldwide",
		displayTextArea: false,
		title: "Title",
		type: ControlType2.String,
	},
});
addFonts(
	FramerQ6a0915ST,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...AnimatedNumberCounterFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:statistics
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5af1700726b89e1359bd903da3e469ba956b8fc7e56af575f49bcf468e7d9c62"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders StatisticsFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5af1700726b89e1359bd903da3e469ba956b8fc7e56af575f49bcf468e7d9c62"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var statistics_default = ComponentWithRoot;
export { statistics_default as default };
