// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5af1700726b89e13 "Cliplab Studio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Large' | 'M/S' // Variant
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-ZOSDNJUM.js";
import { routes } from "./chunks/chunk-2NVZ5JSA.js";

// virtual:tag-l
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/app21JWPXUUVE7MVia4h/lvAUpI1DWBpGBDthAUN4/sxWtEW7F1.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx as cx2,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/TSHkOmZ7wJVFXoUBI8FS/kMUbU4g5zAxjdFD02Q7Z/TPNcOVgXV.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	CycleVariantState,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useOnVariantChange,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["RdhBPZ1br", "hR7mTTiVF"];
var serializationHash = "framer-Wvij9";
var variantClassNames = {
	hR7mTTiVF: "framer-v-1nl0mri",
	RdhBPZ1br: "framer-v-byrenq",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 2,
	ease: [0, 0, 1, 1],
	type: "tween",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Variant 1": "RdhBPZ1br",
	"Variant 2": "hR7mTTiVF",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "RdhBPZ1br",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "RdhBPZ1br",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onAppear1exxk5q = activeVariantCallback(async (...args) => {
		await delay(() => setVariant(CycleVariantState, true), 2e3);
	});
	useOnVariantChange(baseVariant, {
		default: onAppear1exxk5q,
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-byrenq",
							className2,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"RdhBPZ1br"}
						ref={refBinding}
						style={{
							opacity: 1,
							...style,
						}}
						variants={{
							hR7mTTiVF: {
								opacity: 0.29,
							},
						}}
						{...addPropertyOverrides(
							{
								hR7mTTiVF: {
									"data-framer-name": "Variant 2",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-15c53ft"}
							data-framer-name={"Indicator"}
							layoutDependency={layoutDependency}
							layoutId={"fZCkHQmuX"}
							style={{
								backgroundColor:
									"var(--token-d4c36658-1f4b-41b3-aa0d-cf9b918d88bf, rgb(0, 122, 187))",
								borderBottomLeftRadius: 141,
								borderBottomRightRadius: 141,
								borderTopLeftRadius: 141,
								borderTopRightRadius: 141,
								boxShadow:
									"0px 0px 10px 0px rgb(0, 122, 187), 0px 0px 20px 0px var(--token-d4c36658-1f4b-41b3-aa0d-cf9b918d88bf, rgb(0, 122, 187))",
							}}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-Wvij9.framer-4ag176, .framer-Wvij9 .framer-4ag176 { display: block; }",
	".framer-Wvij9.framer-byrenq { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 12px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 12px; }",
	".framer-Wvij9 .framer-15c53ft { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 8px); overflow: var(--overflow-clip-fallback, clip); position: relative; width: 8px; will-change: var(--framer-will-change-override, transform); }",
	".framer-Wvij9.framer-v-1nl0mri .framer-15c53ft { width: 6px; }",
];
var FramerTPNcOVgXV = withCSS(Component, css2, "framer-Wvij9");
var stdin_default = FramerTPNcOVgXV;
FramerTPNcOVgXV.displayName = "Pulse";
FramerTPNcOVgXV.defaultProps = {
	height: 12,
	width: 12,
};
addPropertyControls(FramerTPNcOVgXV, {
	variant: {
		options: ["RdhBPZ1br", "hR7mTTiVF"],
		optionTitles: ["Variant 1", "Variant 2"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerTPNcOVgXV,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/app21JWPXUUVE7MVia4h/lvAUpI1DWBpGBDthAUN4/sxWtEW7F1.js
var PulseFonts = getFonts(stdin_default);
var cycleOrder2 = ["tCxHkiJbD", "PJ15Au_Oi"];
var serializationHash2 = "framer-QlVrC";
var variantClassNames2 = {
	PJ15Au_Oi: "framer-v-17wkr1n",
	tCxHkiJbD: "framer-v-5xsuui",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap2 = {
	"M/S": "PJ15Au_Oi",
	Large: "tCxHkiJbD",
};
var getProps2 = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "tCxHkiJbD",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "tCxHkiJbD",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-5xsuui",
							className2,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Large"}
						layoutDependency={layoutDependency}
						layoutId={"tCxHkiJbD"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-cb2206d2-93ba-4bbf-8a99-2fb6eb742230, rgba(255, 255, 255, 0.1))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backdropFilter: "blur(8px)",
							backgroundColor:
								"var(--token-efc840ff-64db-4d68-b4f9-ffd23b298cd4, rgba(255, 255, 255, 0.05))",
							borderBottomLeftRadius: 8,
							borderBottomRightRadius: 8,
							borderTopLeftRadius: 8,
							borderTopRightRadius: 8,
							WebkitBackdropFilter: "blur(8px)",
							...style,
						}}
						{...addPropertyOverrides2(
							{
								PJ15Au_Oi: {
									"data-framer-name": "M/S",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<ComponentViewportProvider
							height={12}
							width={"12px"}
							y={
								(componentViewport?.y || 0) +
								(8 + ((componentViewport?.height || 200) - 16 - 12) / 2)
							}
							{...addPropertyOverrides2(
								{
									PJ15Au_Oi: {
										y:
											(componentViewport?.y || 0) +
											(6 + ((componentViewport?.height || 200) - 12 - 12) / 2),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainer
								className={"framer-npqslh-container"}
								layoutDependency={layoutDependency}
								layoutId={"S6B3rSCsv-container"}
								nodeId={"S6B3rSCsv"}
								rendersWithMotion={true}
								scopeId={"sxWtEW7F1"}
							>
								{_jsx2(stdin_default, {
									height: "100%",
									id: "S6B3rSCsv",
									layoutId: "S6B3rSCsv",
									style: {
										height: "100%",
										width: "100%",
									},
									variant: "RdhBPZ1br",
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-datsa1"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"jGgQxPd5e"}
							style={{
								"--extracted-r6o4lv":
									"var(--token-9d9c37d5-31f4-4564-b2ab-c0d257f64cbd, rgb(255, 255, 255))",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React2.Fragment>
								<motion2.p
									className={"framer-styles-preset-1h481q3"}
									data-styles-preset={"uWgmT59JL"}
									style={{
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--token-9d9c37d5-31f4-4564-b2ab-c0d257f64cbd, rgb(255, 255, 255)))",
									}}
								>
									{"Limited seats only"}
								</motion2.p>
							</React2.Fragment>
						</RichText>
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-QlVrC.framer-1mz5kow, .framer-QlVrC .framer-1mz5kow { display: block; }",
	".framer-QlVrC.framer-5xsuui { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 8px 12px 8px 12px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-QlVrC .framer-npqslh-container { flex: none; height: 12px; position: relative; width: 12px; }",
	".framer-QlVrC .framer-datsa1 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-QlVrC.framer-v-17wkr1n.framer-5xsuui { gap: 6px; padding: 6px 12px 6px 12px; }",
	...css,
	'.framer-QlVrC[data-border="true"]::after, .framer-QlVrC [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramersxWtEW7F1 = withCSS2(Component2, css3, "framer-QlVrC");
var stdin_default2 = FramersxWtEW7F1;
FramersxWtEW7F1.displayName = "Tag L";
FramersxWtEW7F1.defaultProps = {
	height: 36,
	width: 163,
};
addPropertyControls2(FramersxWtEW7F1, {
	variant: {
		options: ["tCxHkiJbD", "PJ15Au_Oi"],
		optionTitles: ["Large", "M/S"],
		title: "Variant",
		type: ControlType2.Enum,
	},
});
addFonts2(
	FramersxWtEW7F1,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...PulseFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:tag-l
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "PJ15Au_Oi",
	xl: "tCxHkiJbD",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5af1700726b89e1359bd903da3e469ba956b8fc7e56af575f49bcf468e7d9c62"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders TagLFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5af1700726b89e1359bd903da3e469ba956b8fc7e56af575f49bcf468e7d9c62"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var tag_l_default = ComponentWithRoot;
export { tag_l_default as default };
