// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5af1700726b89e13 "Cliplab Studio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'L' | 'M/S' // Variant
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * review?: string // Review
 * name?: string // Name
 * rating?: number // Rating
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-7VV5MPVI.js";
import { className, css, fonts } from "./chunks/chunk-AN6VZTLK.js";
import { routes } from "./chunks/chunk-2NVZ5JSA.js";

// virtual:testimonial-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/qFbtaG4lroUpHBqarJow/Q8XtTWMoSiZxRahsftue/NgGBSYgoo.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	SmartComponentScopedContainer,
	SVG,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/ISKLd7jlitdW3GMne0R0/soNeHCOPw8ffPqnp4fy1/Rating.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { addPropertyControls, ControlType } from "unframer";
function Rating(props) {
	const { rating, color, emptyColor, size, gap } = props;
	const stars = Array.from(
		{
			length: 5,
		},
		(_, i) => {
			const fill = Math.max(0, Math.min(1, rating - i));
			return (
				<Star fill={fill} size={size} color={color} emptyColor={emptyColor} />
			);
		},
	);
	return (
		<div
			style={{
				display: "flex",
				flexDirection: "row",
				gap,
				alignItems: "center",
			}}
		>
			{stars}
		</div>
	);
}
function Star({ fill, size, color, emptyColor }) {
	return (
		<div
			style={{
				position: "relative",
				width: size,
				height: size,
				flexShrink: 0,
			}}
		>
			<StarIcon color={emptyColor} size={size} />
			<div
				style={{
					position: "absolute",
					top: 0,
					left: 0,
					height: "100%",
					width: `${fill * 100}%`,
					overflow: "hidden",
				}}
			>
				<StarIcon color={color} size={size} />
			</div>
		</div>
	);
}
function StarIcon({ color, size }) {
	return (
		<svg
			xmlns={"http://www.w3.org/2000/svg"}
			viewBox={"0 0 256 256"}
			width={size}
			height={size}
			style={{
				display: "block",
			}}
		>
			<path
				d={
					"M239.2,97.29a16,16,0,0,0-13.81-10.88l-58.11-5-22.69-54.08a16,16,0,0,0-29.18,0L92.72,81.41l-58.11,5a16,16,0,0,0-9.11,28.06l44.09,38.46-13.2,56.76a16,16,0,0,0,23.84,17.34l50.77-30,50.77,30a16,16,0,0,0,23.84-17.34l-13.2-56.76,44.09-38.46A16,16,0,0,0,239.2,97.29Z"
				}
				fill={color}
			/>
		</svg>
	);
}
addPropertyControls(Rating, {
	rating: {
		type: ControlType.Number,
		title: "Rating",
		defaultValue: 4.5,
		min: 0,
		max: 5,
		step: 0.1,
		displayStepper: true,
	},
	color: {
		type: ControlType.Color,
		title: "Fill Color",
		defaultValue: "#F59E0B",
	},
	emptyColor: {
		type: ControlType.Color,
		title: "Empty Color",
		defaultValue: "#E5E7EB",
	},
	size: {
		type: ControlType.Number,
		title: "Size",
		defaultValue: 32,
		min: 8,
		max: 200,
	},
	gap: {
		type: ControlType.Number,
		title: "Gap",
		defaultValue: 4,
		min: 0,
		max: 50,
	},
});

// /:https://framerusercontent.com/modules/qFbtaG4lroUpHBqarJow/Q8XtTWMoSiZxRahsftue/NgGBSYgoo.js
var RatingFonts = getFonts(Rating);
var cycleOrder = ["s34IBUSK7", "h8hR6AOU2"];
var serializationHash = "framer-iEr85";
var variantClassNames = {
	h8hR6AOU2: "framer-v-1einm7t",
	s34IBUSK7: "framer-v-1dq7aj6",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 80,
	delay: 0,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"M/S": "h8hR6AOU2",
	L: "s34IBUSK7",
};
var getProps = ({
	height,
	id,
	image,
	name1,
	rating,
	review,
	width,
	...props
}) => {
	return {
		...props,
		eR9ZmkLGf: name1 ?? props.eR9ZmkLGf ?? "Cooper Geidt",
		I4rBN3uqD: rating ?? props.I4rBN3uqD ?? 5,
		qtbgbKCvS: image ??
			props.qtbgbKCvS ?? {
				alt: "",
				pixelHeight: 640,
				pixelWidth: 640,
				src: "https://framerusercontent.com/images/z576pxgMO7uqozxes3YJljpu2s.webp?width=640&height=640",
				srcSet:
					"https://framerusercontent.com/images/z576pxgMO7uqozxes3YJljpu2s.webp?scale-down-to=512&width=640&height=640 512w,https://framerusercontent.com/images/z576pxgMO7uqozxes3YJljpu2s.webp?width=640&height=640 640w",
			},
		Rz8DrLSUz:
			review ??
			props.Rz8DrLSUz ??
			"\u201CI went from total beginner to editing paid wedding videos within months\u201D",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "s34IBUSK7",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		qtbgbKCvS: qtbgbKCvS2,
		Rz8DrLSUz: Rz8DrLSUz2,
		eR9ZmkLGf: eR9ZmkLGf2,
		I4rBN3uqD: I4rBN3uqD2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "s34IBUSK7",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1dq7aj6",
							className3,
							classNames,
						)}
						data-border={true}
						data-framer-name={"L"}
						layoutDependency={layoutDependency}
						layoutId={"s34IBUSK7"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-cb2206d2-93ba-4bbf-8a99-2fb6eb742230, rgba(255, 255, 255, 0.1))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							background:
								"linear-gradient(180deg, var(--token-efc840ff-64db-4d68-b4f9-ffd23b298cd4, rgba(255, 255, 255, 0.05)) 0%, var(--token-737547ea-dc46-45bd-ae2b-4977e3da045e, rgba(9, 0, 189, 0.05)) 100%)",
							borderBottomLeftRadius: 8,
							borderBottomRightRadius: 8,
							borderTopLeftRadius: 8,
							borderTopRightRadius: 8,
							...style,
						}}
						{...addPropertyOverrides(
							{
								h8hR6AOU2: {
									"data-framer-name": "M/S",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-dddibl"}
							data-border={true}
							data-framer-name={"Image"}
							layoutDependency={layoutDependency}
							layoutId={"YhUAvXcaU"}
							style={{
								"--border-bottom-width": "0.5px",
								"--border-color":
									"var(--token-cb2206d2-93ba-4bbf-8a99-2fb6eb742230, rgba(255, 255, 255, 0.1))",
								"--border-left-width": "0.5px",
								"--border-right-width": "0.5px",
								"--border-style": "solid",
								"--border-top-width": "0.5px",
								borderBottomLeftRadius: 9,
								borderBottomRightRadius: 9,
								borderTopLeftRadius: 9,
								borderTopRightRadius: 9,
							}}
						>
							<Image
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) + 24 + 0 + 2,
									),
									pixelHeight: 640,
									pixelWidth: 640,
									sizes: "72px",
									...toResponsiveImage(qtbgbKCvS2),
								}}
								className={"framer-acr8gg"}
								data-framer-name={"Image"}
								layoutDependency={layoutDependency}
								layoutId={"gsqZFH9uj"}
								style={{
									borderBottomLeftRadius: 8,
									borderBottomRightRadius: 8,
									borderTopLeftRadius: 8,
									borderTopRightRadius: 8,
									boxShadow:
										"0px 0px 10px 0px rgb(0, 0, 0), 0px 4px 4px 0px rgba(0, 0, 0, 0.25)",
								}}
							/>
						</motion.div>
						<motion.div
							className={"framer-14lfzdd"}
							data-framer-name={"Content"}
							layoutDependency={layoutDependency}
							layoutId={"dN9xLMV8H"}
						>
							<ComponentViewportProvider>
								<SmartComponentScopedContainer
									className={"framer-1jp6v4f-container"}
									data-code-component-plugin-id={"84d4c1"}
									isAuthoredByUser={true}
									layoutDependency={layoutDependency}
									layoutId={"HGzftl__3-container"}
									nodeId={"HGzftl__3"}
									rendersWithMotion={true}
									scopeId={"NgGBSYgoo"}
								>
									<Rating
										color={
											"var(--token-a0b331ef-7085-4a1e-a4b5-0195668a9610, rgb(213, 255, 0))"
										}
										emptyColor={
											"var(--token-cb2206d2-93ba-4bbf-8a99-2fb6eb742230, rgba(255, 255, 255, 0.1))"
										}
										gap={4}
										height={"100%"}
										id={"HGzftl__3"}
										layoutId={"HGzftl__3"}
										rating={I4rBN3uqD2}
										size={18}
										style={{
											height: "100%",
											width: "100%",
										}}
										width={"100%"}
									/>
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-11168pn"}
								data-framer-name={"Cooper Geidt"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"mlQUiQ5L5"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-9d9c37d5-31f4-4564-b2ab-c0d257f64cbd, rgb(250, 250, 250))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={eR9ZmkLGf2}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1ozhwx8"}
										data-styles-preset={"BsEnbfNw3"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-9d9c37d5-31f4-4564-b2ab-c0d257f64cbd, rgb(250, 250, 250)))",
										}}
									>
										{"Cooper Geidt"}
									</motion.p>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-piwzk8"}
								data-framer-name={
									"\u201CI went from total beginner to editing paid wedding videos within months\u201D"
								}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"cQN6NwTOB"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-b1f5477e-0c35-4cdc-8900-c9aed722522e, rgb(168, 168, 168))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={Rz8DrLSUz2}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1h481q3"}
										data-styles-preset={"uWgmT59JL"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-b1f5477e-0c35-4cdc-8900-c9aed722522e, rgb(168, 168, 168)))",
										}}
									>
										{
											"\u201CI went from total beginner to editing paid wedding videos within months\u201D"
										}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
						<SVG
							className={"framer-12l0qb3"}
							data-framer-name={"\u201C"}
							fill={"rgba(0,0,0,1)"}
							intrinsicHeight={67}
							intrinsicWidth={78}
							layoutDependency={layoutDependency}
							layoutId={"A2A4jPW6S"}
							svg={
								'<svg width="78" height="67" viewBox="-10 -10 78 67" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path d="M3.19094 0V9.55285H8.6343C13.1392 9.55285 15.3916 11.8455 15.3916 16.4309V22.5447H12.7637C9.13484 22.5447 6.13161 23.6911 3.75404 25.9837C1.25135 28.2764 -3.8147e-06 31.1423 -3.8147e-06 34.5813C-3.8147e-06 38.2751 1.25135 41.2683 3.75404 43.561C6.13161 45.8537 9.13484 47 12.7637 47C16.3927 47 19.3959 45.79 21.7735 43.3699C24.151 40.9499 25.3398 37.893 25.3398 34.1992V16.4309C25.3398 5.47697 19.959 0 9.19741 0H3.19094ZM35.8511 0V9.55285H41.2945C45.7994 9.55285 48.0518 11.8455 48.0518 16.4309V22.5447H45.4239C41.795 22.5447 38.7918 23.6911 36.4142 25.9837C33.9115 28.2764 32.6602 31.1423 32.6602 34.5813C32.6602 38.2751 33.9115 41.2683 36.4142 43.561C38.7918 45.8537 41.795 47 45.4239 47C49.0529 47 52.0561 45.79 54.4337 43.3699C56.8112 40.9499 58 37.893 58 34.1992V16.4309C58 5.47697 52.6192 0 41.8576 0H35.8511Z" fill="url(#paint0_linear_99_124)" fill-opacity="0.2"/>\n<defs>\n<linearGradient id="paint0_linear_99_124" x1="29" y1="0" x2="29" y2="47" gradientUnits="userSpaceOnUse">\n<stop stop-color="#D8DDEF"/>\n<stop offset="1" stop-color="#525D83"/>\n</linearGradient>\n</defs>\n</svg>\n'
							}
							withExternalLayout={true}
						/>
						<motion.div
							className={"framer-1xxolrr"}
							data-framer-name={"Ellipse 39"}
							layoutDependency={layoutDependency}
							layoutId={"BlX4FcwbQ"}
							style={{
								background:
									"linear-gradient(180deg, var(--token-d4c36658-1f4b-41b3-aa0d-cf9b918d88bf, rgb(0, 122, 187)) -79%, var(--token-efc840ff-64db-4d68-b4f9-ffd23b298cd4, rgba(255, 255, 255, 0.05)) 438%)",
								borderBottomLeftRadius: "100%",
								borderBottomRightRadius: "100%",
								borderTopLeftRadius: "100%",
								borderTopRightRadius: "100%",
								filter: "blur(51px)",
								opacity: 0,
								WebkitFilter: "blur(51px)",
							}}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-iEr85.framer-10ecqp, .framer-iEr85 .framer-10ecqp { display: block; }",
	".framer-iEr85.framer-1dq7aj6 { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 62px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 24px; position: relative; width: 269px; will-change: var(--framer-will-change-override, transform); }",
	".framer-iEr85 .framer-dddibl { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: flex-start; overflow: visible; padding: 2px; position: relative; width: min-content; }",
	".framer-iEr85 .framer-acr8gg { flex: none; height: 72px; position: relative; width: 72px; }",
	".framer-iEr85 .framer-14lfzdd { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-iEr85 .framer-1jp6v4f-container { flex: none; height: 21px; position: relative; width: 100%; }",
	".framer-iEr85 .framer-11168pn { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-iEr85 .framer-piwzk8 { flex: none; height: auto; max-width: 360px; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-iEr85 .framer-12l0qb3 { flex: none; height: 67px; position: absolute; right: 14px; top: 24px; width: 78px; z-index: 1; }",
	".framer-iEr85 .framer-1xxolrr { flex: none; height: 31px; left: calc(51.67286245353162% - 208px / 2); position: absolute; top: -17px; width: 208px; z-index: 1; }",
	...css,
	...css2,
	'.framer-iEr85[data-border="true"]::after, .framer-iEr85 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramerNgGBSYgoo = withCSS(Component, css3, "framer-iEr85");
var stdin_default = FramerNgGBSYgoo;
FramerNgGBSYgoo.displayName = "Testimonial Card";
FramerNgGBSYgoo.defaultProps = {
	height: 320,
	width: 269,
};
addPropertyControls2(FramerNgGBSYgoo, {
	variant: {
		options: ["s34IBUSK7", "h8hR6AOU2"],
		optionTitles: ["L", "M/S"],
		title: "Variant",
		type: ControlType2.Enum,
	},
	qtbgbKCvS: {
		__defaultAssetReference:
			"data:framer/asset-reference,z576pxgMO7uqozxes3YJljpu2s.webp?originalFilename=Confident+Professional+Woman+in+Office.webp&width=640&height=640",
		__vekterDefault: {
			alt: "",
			assetReference:
				"data:framer/asset-reference,z576pxgMO7uqozxes3YJljpu2s.webp?originalFilename=Confident+Professional+Woman+in+Office.webp&width=640&height=640",
		},
		title: "Image",
		type: ControlType2.ResponsiveImage,
	},
	Rz8DrLSUz: {
		defaultValue:
			"\u201CI went from total beginner to editing paid wedding videos within months\u201D",
		displayTextArea: false,
		title: "Review",
		type: ControlType2.String,
	},
	eR9ZmkLGf: {
		defaultValue: "Cooper Geidt",
		displayTextArea: false,
		title: "Name",
		type: ControlType2.String,
	},
	I4rBN3uqD: {
		defaultValue: 5,
		displayStepper: true,
		max: 5,
		min: 0,
		step: 0.1,
		title: "Rating",
		type: ControlType2.Number,
	},
});
addFonts(
	FramerNgGBSYgoo,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...RatingFonts,
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:testimonial-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "h8hR6AOU2",
	xl: "s34IBUSK7",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5af1700726b89e1359bd903da3e469ba956b8fc7e56af575f49bcf468e7d9c62"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders TestimonialCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5af1700726b89e1359bd903da3e469ba956b8fc7e56af575f49bcf468e7d9c62"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var testimonial_card_default = ComponentWithRoot;
export { testimonial_card_default as default };
