// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5af1700726b89e13 "Cliplab Studio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'L ' | 'M' | 'S' // Variant
 * source1?: 'URL' | 'Upload' // Source 1
 * video1?: string // Video 1
 * profileImage1?: {src: string, srcSet?: string, alt?: string} // Profile Image 1
 * name1?: string // Name 1
 * source2?: 'URL' | 'Upload' // Source 2
 * video2?: string // Video 2
 * profileImage2?: {src: string, srcSet?: string, alt?: string} // Profile Image 2
 * name2?: string // Name 2
 * source3?: 'URL' | 'Upload' // Source 3
 * video3?: string // Video 3
 * profileImage3?: {src: string, srcSet?: string, alt?: string} // Profile Image 3
 * name3?: string // Name 3
 * source4?: 'URL' | 'Upload' // Source 4
 * video4?: string // Video 4
 * profileImage4?: {src: string, srcSet?: string, alt?: string} // Profile Image 4
 * name4?: string // Name 4
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-6HGIPRDC.js";
import { Video } from "./chunks/chunk-3COXQQ4E.js";
import { routes } from "./chunks/chunk-2NVZ5JSA.js";

// virtual:vertical-video-frame
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/2OyDcPhETO0D9jMvJRyq/zglhi8hmnHejnm3j7NUN/x_V7626O9.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider as ComponentViewportProvider2,
	ControlType as ControlType2,
	cx as cx2,
	getFonts as getFonts2,
	getPropertyControls as getPropertyControls2,
	SmartComponentScopedContainer as SmartComponentScopedContainer2,
	TickerItem,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
	withTickerFX,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/hvtwS1yHJPysxqmym0M5/k7e6FSkhttgsrQGjj0YO/k2Vk_be5W.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	getPropertyControls,
	Image,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var VideoFonts = getFonts(Video);
var VideoControls = getPropertyControls(Video);
var cycleOrder = ["Atbby340c", "bLKpyAusL"];
var serializationHash = "framer-sbE2L";
var variantClassNames = {
	Atbby340c: "framer-v-fx477n",
	bLKpyAusL: "framer-v-1vh0xef",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var Y5AgF7GztcryRfVcK6 = void 0;
var transition1 = {
	damping: 80,
	delay: 0,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var toImageSrc = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value.src;
	}
	return typeof value === "string" ? value : void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"M/S": "bLKpyAusL",
	L: "Atbby340c",
};
var getProps = ({ file, height, id, image, source, text, width, ...props }) => {
	return {
		...props,
		EiccCQAL1: source ?? props.EiccCQAL1 ?? "Upload",
		Kb057vsP6:
			file ??
			props.Kb057vsP6 ??
			"https://framerusercontent.com/assets/3B7KU8CJ9iFihc53tVJUQzq1EuM.mp4",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "Atbby340c",
		VwdlXcOKw: text ?? props.VwdlXcOKw ?? "Jahn Jacob",
		ZiYzbP6im: image ??
			props.ZiYzbP6im ?? {
				alt: "",
				pixelHeight: 1200,
				pixelWidth: 1200,
				src: "https://framerusercontent.com/images/BVdUEHTnLtzDM3IkgeDZxn6eAt4.webp?width=1200&height=1200",
				srcSet:
					"https://framerusercontent.com/images/BVdUEHTnLtzDM3IkgeDZxn6eAt4.webp?scale-down-to=512&width=1200&height=1200 512w,https://framerusercontent.com/images/BVdUEHTnLtzDM3IkgeDZxn6eAt4.webp?scale-down-to=1024&width=1200&height=1200 1024w,https://framerusercontent.com/images/BVdUEHTnLtzDM3IkgeDZxn6eAt4.webp?width=1200&height=1200 1200w",
			},
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		Kb057vsP6: Kb057vsP62,
		EiccCQAL1: EiccCQAL12,
		ZiYzbP6im: ZiYzbP6im2,
		VwdlXcOKw: VwdlXcOKw2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "Atbby340c",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-fx477n",
							className2,
							classNames,
						)}
						data-framer-name={"L"}
						layoutDependency={layoutDependency}
						layoutId={"Atbby340c"}
						ref={refBinding}
						style={{
							borderBottomLeftRadius: 10,
							borderBottomRightRadius: 10,
							borderTopLeftRadius: 10,
							borderTopRightRadius: 10,
							...style,
						}}
						{...addPropertyOverrides(
							{
								bLKpyAusL: {
									"data-framer-name": "M/S",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1366vlc"}
							data-framer-name={"Profile"}
							layoutDependency={layoutDependency}
							layoutId={"izy1oEsKK"}
						>
							<Image
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											(componentViewport?.height || 550) -
											64 +
											0,
									),
									pixelHeight: 1200,
									pixelWidth: 1200,
									sizes: "30px",
									...toResponsiveImage(ZiYzbP6im2),
								}}
								className={"framer-1nkeizm"}
								layoutDependency={layoutDependency}
								layoutId={"WQ0vlTQy2"}
								style={{
									borderBottomLeftRadius: 243,
									borderBottomRightRadius: 243,
									borderTopLeftRadius: 243,
									borderTopRightRadius: 243,
								}}
								{...addPropertyOverrides(
									{
										bLKpyAusL: {
											background: {
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														(componentViewport?.height || 550) -
														60 +
														0,
												),
												pixelHeight: 1200,
												pixelWidth: 1200,
												sizes: "30px",
												...toResponsiveImage(ZiYzbP6im2),
											},
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-10drdft"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"FYG8mB9KO"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={VwdlXcOKw2}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-5xfrwz"}
										data-styles-preset={"ruLAtCqcd"}
									>
										{"Jahn Jacob"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
						<ComponentViewportProvider>
							<SmartComponentScopedContainer
								className={"framer-1h46hr-container"}
								isAuthoredByUser={true}
								isModuleExternal={true}
								layoutDependency={layoutDependency}
								layoutId={"Tu90YI7Xw-container"}
								nodeId={"Tu90YI7Xw"}
								rendersWithMotion={true}
								scopeId={"k2Vk_be5W"}
							>
								<Video
									backgroundColor={"rgba(0, 0, 0, 0)"}
									borderRadius={10}
									bottomLeftRadius={10}
									bottomRightRadius={10}
									controls={false}
									height={"100%"}
									id={"Tu90YI7Xw"}
									isMixedBorderRadius={false}
									layoutId={"Tu90YI7Xw"}
									loop={true}
									muted={true}
									objectFit={"cover"}
									playing={true}
									poster={toImageSrc(Y5AgF7GztcryRfVcK6)}
									posterEnabled={true}
									srcFile={Kb057vsP62}
									srcType={EiccCQAL12}
									srcUrl={
										"https://framerusercontent.com/assets/MLWPbW1dUQawJLhhun3dBwpgJak.mp4"
									}
									startTime={0}
									style={{
										height: "100%",
										width: "100%",
									}}
									topLeftRadius={10}
									topRightRadius={10}
									volume={25}
									width={"100%"}
								/>
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<motion.div
							className={"framer-dutcif"}
							data-framer-name={"Overlay"}
							layoutDependency={layoutDependency}
							layoutId={"yFkgO485z"}
							style={{
								background:
									"linear-gradient(180deg, rgba(0, 0, 0, 0) 0%, rgb(0, 0, 0) 115.00000000000001%)",
							}}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-sbE2L.framer-1e23gm0, .framer-sbE2L .framer-1e23gm0 { display: block; }",
	".framer-sbE2L.framer-fx477n { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 550px; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 366px; will-change: var(--framer-will-change-override, transform); }",
	".framer-sbE2L .framer-1366vlc { align-content: center; align-items: center; bottom: 24px; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; left: 24px; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: absolute; width: min-content; z-index: 2; }",
	".framer-sbE2L .framer-1nkeizm { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 30px); overflow: var(--overflow-clip-fallback, clip); position: relative; width: 30px; will-change: var(--framer-will-change-override, transform); }",
	".framer-sbE2L .framer-10drdft { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-sbE2L .framer-1h46hr-container { flex: 1 0 0px; height: 100%; position: relative; width: 1px; }",
	".framer-sbE2L .framer-dutcif { bottom: 0px; flex: none; height: 14%; left: calc(50.00000000000002% - 101.09289617486338% / 2); overflow: var(--overflow-clip-fallback, clip); position: absolute; width: 101%; z-index: 1; }",
	".framer-sbE2L.framer-v-1vh0xef.framer-fx477n { aspect-ratio: 0.6654545454545454 / 1; height: var(--framer-aspect-ratio-supported, 550px); }",
	".framer-sbE2L.framer-v-1vh0xef .framer-1366vlc { bottom: 20px; left: 20px; }",
	".framer-sbE2L.framer-v-1vh0xef .framer-dutcif { height: 18%; }",
	...css,
];
var Framerk2Vk_be5W = withCSS(Component, css2, "framer-sbE2L");
var stdin_default = Framerk2Vk_be5W;
Framerk2Vk_be5W.displayName = "Video Player";
Framerk2Vk_be5W.defaultProps = {
	height: 550,
	width: 366,
};
addPropertyControls(Framerk2Vk_be5W, {
	variant: {
		options: ["Atbby340c", "bLKpyAusL"],
		optionTitles: ["L", "M/S"],
		title: "Variant",
		type: ControlType.Enum,
	},
	Kb057vsP6: VideoControls?.["srcFile"] && {
		...VideoControls["srcFile"],
		__defaultAssetReference:
			"data:framer/asset-reference,3B7KU8CJ9iFihc53tVJUQzq1EuM.mp4?originalFilename=2.mp4",
		description: void 0,
		hidden: void 0,
		title: "File",
	},
	EiccCQAL1: VideoControls?.["srcType"] && {
		...VideoControls["srcType"],
		defaultValue: "Upload",
		description: void 0,
		hidden: void 0,
		title: "Source",
	},
	ZiYzbP6im: {
		__defaultAssetReference:
			"data:framer/asset-reference,BVdUEHTnLtzDM3IkgeDZxn6eAt4.webp?originalFilename=Young+Man+in+Focus.webp&width=1200&height=1200",
		__vekterDefault: {
			alt: "",
			assetReference:
				"data:framer/asset-reference,BVdUEHTnLtzDM3IkgeDZxn6eAt4.webp?originalFilename=Young+Man+in+Focus.webp&width=1200&height=1200",
		},
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	VwdlXcOKw: {
		defaultValue: "Jahn Jacob",
		displayTextArea: false,
		title: "Text",
		type: ControlType.String,
	},
});
addFonts(
	Framerk2Vk_be5W,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...VideoFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/2OyDcPhETO0D9jMvJRyq/zglhi8hmnHejnm3j7NUN/x_V7626O9.js
var VideoPlayerFonts = getFonts2(stdin_default);
var MotionDivWithTickerFX = withTickerFX(motion2.div);
var VideoPlayerControls = getPropertyControls2(stdin_default);
var cycleOrder2 = ["RjZaGThA2", "z5OlpXQZB", "dtTrZcl7Y"];
var serializationHash2 = "framer-IVPlj";
var variantClassNames2 = {
	dtTrZcl7Y: "framer-v-e8k22v",
	RjZaGThA2: "framer-v-14fm2mh",
	z5OlpXQZB: "framer-v-kaztlu",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage2 = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap2 = {
	"L ": "RjZaGThA2",
	M: "z5OlpXQZB",
	S: "dtTrZcl7Y",
};
var getProps2 = ({
	height,
	id,
	name1,
	name2,
	name3,
	name4,
	profileImage1,
	profileImage2,
	profileImage3,
	profileImage4,
	source1,
	source2,
	source3,
	source4,
	video1,
	video2,
	video3,
	video4,
	width,
	...props
}) => {
	return {
		...props,
		bR99x8twF: profileImage3 ??
			props.bR99x8twF ?? {
				pixelHeight: 1200,
				pixelWidth: 1200,
				src: "https://framerusercontent.com/images/BVdUEHTnLtzDM3IkgeDZxn6eAt4.webp?width=1200&height=1200",
				srcSet:
					"https://framerusercontent.com/images/BVdUEHTnLtzDM3IkgeDZxn6eAt4.webp?scale-down-to=512&width=1200&height=1200 512w,https://framerusercontent.com/images/BVdUEHTnLtzDM3IkgeDZxn6eAt4.webp?scale-down-to=1024&width=1200&height=1200 1024w,https://framerusercontent.com/images/BVdUEHTnLtzDM3IkgeDZxn6eAt4.webp?width=1200&height=1200 1200w",
			},
		DqYTKEyNn:
			video3 ??
			props.DqYTKEyNn ??
			"https://framerusercontent.com/assets/ICsfLTaJqfgo3a1vHdmpAhFnkM.mp4",
		e88rz9lnq: name3 ?? props.e88rz9lnq ?? "Jahn Jacob",
		EAEiSauhj: source4 ?? props.EAEiSauhj ?? "Upload",
		fF6UI6Edm: source1 ?? props.fF6UI6Edm ?? "Upload",
		jaQPopA3I: source2 ?? props.jaQPopA3I ?? "Upload",
		L89Patlbm: profileImage2 ??
			props.L89Patlbm ?? {
				pixelHeight: 1200,
				pixelWidth: 1200,
				src: "https://framerusercontent.com/images/BVdUEHTnLtzDM3IkgeDZxn6eAt4.webp?width=1200&height=1200",
				srcSet:
					"https://framerusercontent.com/images/BVdUEHTnLtzDM3IkgeDZxn6eAt4.webp?scale-down-to=512&width=1200&height=1200 512w,https://framerusercontent.com/images/BVdUEHTnLtzDM3IkgeDZxn6eAt4.webp?scale-down-to=1024&width=1200&height=1200 1024w,https://framerusercontent.com/images/BVdUEHTnLtzDM3IkgeDZxn6eAt4.webp?width=1200&height=1200 1200w",
			},
		M3g_CieSq:
			video1 ??
			props.M3g_CieSq ??
			"https://framerusercontent.com/assets/3B7KU8CJ9iFihc53tVJUQzq1EuM.mp4",
		MsvJwK1BJ: name2 ?? props.MsvJwK1BJ ?? "Jahn Jacob",
		syLpBJbdn: profileImage4 ??
			props.syLpBJbdn ?? {
				pixelHeight: 1200,
				pixelWidth: 1200,
				src: "https://framerusercontent.com/images/BVdUEHTnLtzDM3IkgeDZxn6eAt4.webp?width=1200&height=1200",
				srcSet:
					"https://framerusercontent.com/images/BVdUEHTnLtzDM3IkgeDZxn6eAt4.webp?scale-down-to=512&width=1200&height=1200 512w,https://framerusercontent.com/images/BVdUEHTnLtzDM3IkgeDZxn6eAt4.webp?scale-down-to=1024&width=1200&height=1200 1024w,https://framerusercontent.com/images/BVdUEHTnLtzDM3IkgeDZxn6eAt4.webp?width=1200&height=1200 1200w",
			},
		TLJESPcm3: name4 ?? props.TLJESPcm3 ?? "Jahn Jacob",
		trkd5ZNm9:
			video4 ??
			props.trkd5ZNm9 ??
			"https://framerusercontent.com/assets/xnWwVYtnaguMVqHHupS0p9hVsR8.mp4",
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "RjZaGThA2",
		wEEv0HboZ: profileImage1 ??
			props.wEEv0HboZ ?? {
				pixelHeight: 1200,
				pixelWidth: 1200,
				src: "https://framerusercontent.com/images/BVdUEHTnLtzDM3IkgeDZxn6eAt4.webp?width=1200&height=1200",
				srcSet:
					"https://framerusercontent.com/images/BVdUEHTnLtzDM3IkgeDZxn6eAt4.webp?scale-down-to=512&width=1200&height=1200 512w,https://framerusercontent.com/images/BVdUEHTnLtzDM3IkgeDZxn6eAt4.webp?scale-down-to=1024&width=1200&height=1200 1024w,https://framerusercontent.com/images/BVdUEHTnLtzDM3IkgeDZxn6eAt4.webp?width=1200&height=1200 1200w",
			},
		WsQwzFBaF: name1 ?? props.WsQwzFBaF ?? "Jahn Jacob",
		yeljXuNeI: source3 ?? props.yeljXuNeI ?? "Upload",
		zU0iMPdLk:
			video2 ??
			props.zU0iMPdLk ??
			"https://framerusercontent.com/assets/OxAi6ArP19fgXIcQJG5hEWv2Kgw.mp4",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		fF6UI6Edm: fF6UI6Edm2,
		M3g_CieSq: M3g_CieSq2,
		wEEv0HboZ: wEEv0HboZ2,
		WsQwzFBaF: WsQwzFBaF2,
		jaQPopA3I: jaQPopA3I2,
		zU0iMPdLk: zU0iMPdLk2,
		L89Patlbm: L89Patlbm2,
		MsvJwK1BJ: MsvJwK1BJ2,
		yeljXuNeI: yeljXuNeI2,
		DqYTKEyNn: DqYTKEyNn2,
		bR99x8twF: bR99x8twF2,
		e88rz9lnq: e88rz9lnq2,
		EAEiSauhj: EAEiSauhj2,
		trkd5ZNm9: trkd5ZNm92,
		syLpBJbdn: syLpBJbdn2,
		TLJESPcm3: TLJESPcm32,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "RjZaGThA2",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-14fm2mh",
							className2,
							classNames,
						)}
						data-framer-name={"L "}
						layoutDependency={layoutDependency}
						layoutId={"RjZaGThA2"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides2(
							{
								dtTrZcl7Y: {
									"data-framer-name": "S",
								},
								z5OlpXQZB: {
									"data-framer-name": "M",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<MotionDivWithTickerFX
							className={"framer-192s1gj"}
							layoutDependency={layoutDependency}
							layoutId={"VfT8L6ypU"}
							style={{
								borderBottomLeftRadius: 10,
								borderBottomRightRadius: 10,
								borderTopLeftRadius: 10,
								borderTopRightRadius: 10,
							}}
							tickerEffectAlign={"center"}
							tickerEffectDirectionModifier={"default"}
							tickerEffectDraggable={true}
							tickerEffectEnabled={true}
							tickerEffectGap={"20px"}
							tickerEffectHoverModifier={10}
							tickerEffectOverflow={"clip"}
							tickerEffectPosition={"relative"}
							tickerEffectStackDirection={"row"}
							tickerEffectVelocity={30}
							{...addPropertyOverrides2(
								{
									dtTrZcl7Y: {
										tickerEffectGap: 10,
										tickerEffectHoverModifier: 80,
										tickerEffectVelocity: 40,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<TickerItem>
								<ComponentViewportProvider2
									height={550}
									width={"366px"}
									y={(componentViewport?.y || 0) + 0 + 0 + 0}
									{...addPropertyOverrides2(
										{
											dtTrZcl7Y: {
												height: 410,
												width: "300px",
											},
											z5OlpXQZB: {
												height: 45,
												width: "300px",
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer2
										className={"framer-1amvyfj-container"}
										data-framer-name={"Video 1"}
										layoutDependency={layoutDependency}
										layoutId={"Z_K9nLjEk-container"}
										name={"Video 1"}
										nodeId={"Z_K9nLjEk"}
										rendersWithMotion={true}
										scopeId={"x_V7626O9"}
									>
										{_jsx2(stdin_default, {
											EiccCQAL1: fF6UI6Edm2,
											height: "100%",
											id: "Z_K9nLjEk",
											Kb057vsP6: M3g_CieSq2,
											layoutId: "Z_K9nLjEk",
											name: "Video 1",
											style: {
												height: "100%",
												width: "100%",
											},
											variant: "Atbby340c",
											VwdlXcOKw: WsQwzFBaF2,
											width: "100%",
											ZiYzbP6im: toResponsiveImage2(wEEv0HboZ2),
											...addPropertyOverrides2(
												{
													dtTrZcl7Y: {
														variant: "bLKpyAusL",
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer2>
								</ComponentViewportProvider2>
							</TickerItem>
							<TickerItem>
								<ComponentViewportProvider2
									height={550}
									width={"366px"}
									y={(componentViewport?.y || 0) + 0 + 0 + 0}
									{...addPropertyOverrides2(
										{
											dtTrZcl7Y: {
												height: 410,
												width: "300px",
											},
											z5OlpXQZB: {
												height: 45,
												width: "300px",
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer2
										className={"framer-nndpfa-container"}
										data-framer-name={"Video 2"}
										layoutDependency={layoutDependency}
										layoutId={"yak1hSfUp-container"}
										name={"Video 2"}
										nodeId={"yak1hSfUp"}
										rendersWithMotion={true}
										scopeId={"x_V7626O9"}
									>
										{_jsx2(stdin_default, {
											EiccCQAL1: jaQPopA3I2,
											height: "100%",
											id: "yak1hSfUp",
											Kb057vsP6: zU0iMPdLk2,
											layoutId: "yak1hSfUp",
											name: "Video 2",
											style: {
												height: "100%",
												width: "100%",
											},
											variant: "Atbby340c",
											VwdlXcOKw: MsvJwK1BJ2,
											width: "100%",
											ZiYzbP6im: toResponsiveImage2(L89Patlbm2),
											...addPropertyOverrides2(
												{
													dtTrZcl7Y: {
														variant: "bLKpyAusL",
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer2>
								</ComponentViewportProvider2>
							</TickerItem>
							<TickerItem>
								<ComponentViewportProvider2
									height={550}
									width={"366px"}
									y={(componentViewport?.y || 0) + 0 + 0 + 0}
									{...addPropertyOverrides2(
										{
											dtTrZcl7Y: {
												height: 410,
												width: "300px",
											},
											z5OlpXQZB: {
												height: 45,
												width: "300px",
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer2
										className={"framer-a6weak-container"}
										data-framer-name={"Video 3"}
										layoutDependency={layoutDependency}
										layoutId={"oiORb3MAG-container"}
										name={"Video 3"}
										nodeId={"oiORb3MAG"}
										rendersWithMotion={true}
										scopeId={"x_V7626O9"}
									>
										{_jsx2(stdin_default, {
											EiccCQAL1: yeljXuNeI2,
											height: "100%",
											id: "oiORb3MAG",
											Kb057vsP6: DqYTKEyNn2,
											layoutId: "oiORb3MAG",
											name: "Video 3",
											style: {
												height: "100%",
												width: "100%",
											},
											variant: "Atbby340c",
											VwdlXcOKw: e88rz9lnq2,
											width: "100%",
											ZiYzbP6im: toResponsiveImage2(bR99x8twF2),
											...addPropertyOverrides2(
												{
													dtTrZcl7Y: {
														variant: "bLKpyAusL",
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer2>
								</ComponentViewportProvider2>
							</TickerItem>
							<TickerItem>
								<ComponentViewportProvider2
									height={550}
									width={"366px"}
									y={(componentViewport?.y || 0) + 0 + 0 + 0}
									{...addPropertyOverrides2(
										{
											dtTrZcl7Y: {
												height: 410,
												width: "300px",
											},
											z5OlpXQZB: {
												height: 45,
												width: "300px",
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer2
										className={"framer-108x9xu-container"}
										data-framer-name={"Video 4"}
										layoutDependency={layoutDependency}
										layoutId={"kfk5JA5_Y-container"}
										name={"Video 4"}
										nodeId={"kfk5JA5_Y"}
										rendersWithMotion={true}
										scopeId={"x_V7626O9"}
									>
										{_jsx2(stdin_default, {
											EiccCQAL1: EAEiSauhj2,
											height: "100%",
											id: "kfk5JA5_Y",
											Kb057vsP6: trkd5ZNm92,
											layoutId: "kfk5JA5_Y",
											name: "Video 4",
											style: {
												height: "100%",
												width: "100%",
											},
											variant: "Atbby340c",
											VwdlXcOKw: TLJESPcm32,
											width: "100%",
											ZiYzbP6im: toResponsiveImage2(syLpBJbdn2),
											...addPropertyOverrides2(
												{
													dtTrZcl7Y: {
														variant: "bLKpyAusL",
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer2>
								</ComponentViewportProvider2>
							</TickerItem>
						</MotionDivWithTickerFX>
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-IVPlj.framer-1fikxlx, .framer-IVPlj .framer-1fikxlx { display: block; }",
	".framer-IVPlj.framer-14fm2mh { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1120px; }",
	".framer-IVPlj .framer-192s1gj { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-IVPlj .framer-1amvyfj-container, .framer-IVPlj .framer-nndpfa-container, .framer-IVPlj .framer-a6weak-container, .framer-IVPlj .framer-108x9xu-container { aspect-ratio: 0.6654545454545454 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 550px); position: relative; width: 366px; }",
	".framer-IVPlj.framer-v-kaztlu .framer-1amvyfj-container, .framer-IVPlj.framer-v-kaztlu .framer-nndpfa-container, .framer-IVPlj.framer-v-kaztlu .framer-a6weak-container, .framer-IVPlj.framer-v-kaztlu .framer-108x9xu-container { height: var(--framer-aspect-ratio-supported, 451px); width: 300px; }",
	".framer-IVPlj.framer-v-e8k22v.framer-14fm2mh { gap: 20px; width: 390px; }",
	".framer-IVPlj.framer-v-e8k22v .framer-192s1gj { gap: 10px; }",
	".framer-IVPlj.framer-v-e8k22v .framer-1amvyfj-container, .framer-IVPlj.framer-v-e8k22v .framer-nndpfa-container, .framer-IVPlj.framer-v-e8k22v .framer-a6weak-container, .framer-IVPlj.framer-v-e8k22v .framer-108x9xu-container { aspect-ratio: 0.7317073170731707 / 1; height: var(--framer-aspect-ratio-supported, 410px); min-width: 290px; width: 300px; }",
];
var Framerx_V7626O9 = withCSS2(Component2, css3, "framer-IVPlj");
var stdin_default2 = Framerx_V7626O9;
Framerx_V7626O9.displayName = "Vertical Video Frame";
Framerx_V7626O9.defaultProps = {
	height: 550,
	width: 1120,
};
addPropertyControls2(Framerx_V7626O9, {
	variant: {
		options: ["RjZaGThA2", "z5OlpXQZB", "dtTrZcl7Y"],
		optionTitles: ["L ", "M", "S"],
		title: "Variant",
		type: ControlType2.Enum,
	},
	fF6UI6Edm: VideoPlayerControls?.["EiccCQAL1"] && {
		...VideoPlayerControls["EiccCQAL1"],
		defaultValue: "Upload",
		description: void 0,
		hidden: void 0,
		title: "Source 1",
	},
	M3g_CieSq: VideoPlayerControls?.["Kb057vsP6"] && {
		...VideoPlayerControls["Kb057vsP6"],
		__defaultAssetReference:
			"data:framer/asset-reference,3B7KU8CJ9iFihc53tVJUQzq1EuM.mp4?originalFilename=2.mp4",
		description: void 0,
		hidden: void 0,
		title: "Video 1",
	},
	wEEv0HboZ: {
		__defaultAssetReference:
			"data:framer/asset-reference,BVdUEHTnLtzDM3IkgeDZxn6eAt4.webp?originalFilename=Young+Man+in+Focus.webp&width=1200&height=1200",
		title: "Profile Image 1",
		type: ControlType2.ResponsiveImage,
	},
	WsQwzFBaF: {
		defaultValue: "Jahn Jacob",
		displayTextArea: false,
		title: "Name 1",
		type: ControlType2.String,
	},
	jaQPopA3I: VideoPlayerControls?.["EiccCQAL1"] && {
		...VideoPlayerControls["EiccCQAL1"],
		defaultValue: "Upload",
		description: void 0,
		hidden: void 0,
		title: "Source 2",
	},
	zU0iMPdLk: VideoPlayerControls?.["Kb057vsP6"] && {
		...VideoPlayerControls["Kb057vsP6"],
		__defaultAssetReference:
			"data:framer/asset-reference,OxAi6ArP19fgXIcQJG5hEWv2Kgw.mp4?originalFilename=3vertical.mp4",
		description: void 0,
		hidden: void 0,
		title: "Video 2",
	},
	L89Patlbm: {
		__defaultAssetReference:
			"data:framer/asset-reference,BVdUEHTnLtzDM3IkgeDZxn6eAt4.webp?originalFilename=Young+Man+in+Focus.webp&width=1200&height=1200",
		title: "Profile Image 2",
		type: ControlType2.ResponsiveImage,
	},
	MsvJwK1BJ: {
		defaultValue: "Jahn Jacob",
		displayTextArea: false,
		title: "Name 2",
		type: ControlType2.String,
	},
	yeljXuNeI: VideoPlayerControls?.["EiccCQAL1"] && {
		...VideoPlayerControls["EiccCQAL1"],
		defaultValue: "Upload",
		description: void 0,
		hidden: void 0,
		title: "Source 3",
	},
	DqYTKEyNn: VideoPlayerControls?.["Kb057vsP6"] && {
		...VideoPlayerControls["Kb057vsP6"],
		__defaultAssetReference:
			"data:framer/asset-reference,ICsfLTaJqfgo3a1vHdmpAhFnkM.mp4?originalFilename=4vertical.mp4",
		description: void 0,
		hidden: void 0,
		title: "Video 3",
	},
	bR99x8twF: {
		__defaultAssetReference:
			"data:framer/asset-reference,BVdUEHTnLtzDM3IkgeDZxn6eAt4.webp?originalFilename=Young+Man+in+Focus.webp&width=1200&height=1200",
		title: "Profile Image 3",
		type: ControlType2.ResponsiveImage,
	},
	e88rz9lnq: {
		defaultValue: "Jahn Jacob",
		displayTextArea: false,
		title: "Name 3",
		type: ControlType2.String,
	},
	EAEiSauhj: VideoPlayerControls?.["EiccCQAL1"] && {
		...VideoPlayerControls["EiccCQAL1"],
		defaultValue: "Upload",
		description: void 0,
		hidden: void 0,
		title: "Source 4",
	},
	trkd5ZNm9: VideoPlayerControls?.["Kb057vsP6"] && {
		...VideoPlayerControls["Kb057vsP6"],
		__defaultAssetReference:
			"data:framer/asset-reference,xnWwVYtnaguMVqHHupS0p9hVsR8.mp4?originalFilename=5vertical.mp4",
		description: void 0,
		hidden: void 0,
		title: "Video 4",
	},
	syLpBJbdn: {
		__defaultAssetReference:
			"data:framer/asset-reference,BVdUEHTnLtzDM3IkgeDZxn6eAt4.webp?originalFilename=Young+Man+in+Focus.webp&width=1200&height=1200",
		title: "Profile Image 4",
		type: ControlType2.ResponsiveImage,
	},
	TLJESPcm3: {
		defaultValue: "Jahn Jacob",
		displayTextArea: false,
		title: "Name 4",
		type: ControlType2.String,
	},
});
addFonts2(
	Framerx_V7626O9,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...VideoPlayerFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:vertical-video-frame
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "dtTrZcl7Y",
	md: "z5OlpXQZB",
	xl: "RjZaGThA2",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5af1700726b89e1359bd903da3e469ba956b8fc7e56af575f49bcf468e7d9c62"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders VerticalVideoFrameFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5af1700726b89e1359bd903da3e469ba956b8fc7e56af575f49bcf468e7d9c62"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var vertical_video_frame_default = ComponentWithRoot;
export { vertical_video_frame_default as default };
