// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5af1700726b89e13 "Cliplab Studio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'L' | 'S' // Variant
 * videoType?: 'Youtube' | 'Video Upload' // Video Type
 * videoFile?: string // Video File
 * source?: 'URL' | 'Upload' // Source
 * youtubeURL?: string // Youtube URL
}} Props

 */
import { stdin_default } from "./chunks/chunk-3YMKYJV4.js";
import "./chunks/chunk-L2OIHFDR.js";
import {
	Video,
	borderRadiusControl,
	containerStyles,
	defaultEvents,
	emptyStateStyle,
	useIsOnCanvas,
	useRadius,
} from "./chunks/chunk-3COXQQ4E.js";
import { routes } from "./chunks/chunk-2NVZ5JSA.js";

// virtual:video-player-hero-frame
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/rqnuOtEPD7rQLPKaRwr7/1PEcSPSoJxeriXObRSqI/DGtwnUeFZ.js
import { jsx as _jsx3, jsxs as _jsxs3 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls3,
	ComponentViewportProvider as ComponentViewportProvider2,
	ControlType as ControlType3,
	cx as cx2,
	getFonts as getFonts2,
	getPropertyControls as getPropertyControls2,
	SmartComponentScopedContainer as SmartComponentScopedContainer2,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/NEd4VmDdsxM3StIUbddO/pRRgk0dcN3gDaE0WpAE7/YouTube.js
import {
	jsx as _jsx,
	jsxs as _jsxs,
	Fragment as _Fragment,
} from "react/jsx-runtime";
import { useReducer, useState } from "react";
import { ControlType, addPropertyControls } from "unframer";
var PlayOptions;
(function (PlayOptions2) {
	PlayOptions2["Normal"] = "Off";
	PlayOptions2["Auto"] = "On";
	PlayOptions2["Loop"] = "Loop";
})(PlayOptions || (PlayOptions = {}));
var ThumbnailOptions;
(function (ThumbnailOptions2) {
	ThumbnailOptions2["High"] = "High Quality";
	ThumbnailOptions2["Medium"] = "Medium Quality";
	ThumbnailOptions2["Low"] = "Low Quality";
	ThumbnailOptions2["Off"] = "Off";
})(ThumbnailOptions || (ThumbnailOptions = {}));
function Youtube({
	url,
	play,
	shouldMute,
	thumbnail,
	isRed,
	onClick,
	border,
	boxShadow,
	onMouseEnter,
	onMouseLeave,
	onMouseDown,
	onMouseUp,
	title,
	...props
}) {
	const onCanvas = useIsOnCanvas();
	const isAutoplay = play !== "Off";
	const showThumbnail = onCanvas || (thumbnail !== "Off" && !isAutoplay);
	const [isPreloading, preloadVideo] = useReducer(() => true, false);
	const [showVideo, startVideo] = useReducer(() => true, !showThumbnail);
	const [isHovered, setHovered] = useState(false);
	const borderRadius = useRadius(props);
	const hasBorderRadius =
		borderRadius !== "0px 0px 0px 0px" && borderRadius !== "0px";
	if (url === "") {
		return <Instructions />;
	}
	const parsedURL = parseVideoURL(url);
	if (parsedURL === void 0) {
		return <ErrorMessage message={"Invalid Youtube URL."} />;
	}
	const [videoId, embedURL, originalSearchParams] = parsedURL;
	const searchParams = embedURL.searchParams;
	if (originalSearchParams) {
		for (const [param, value] of originalSearchParams) {
			searchParams.set(param, value);
			if (param === "t") searchParams.set("start", value);
		}
	}
	searchParams.set("iv_load_policy", "3");
	searchParams.set("rel", "0");
	searchParams.set("modestbranding", "1");
	searchParams.set("playsinline", "1");
	if (!showVideo) {
		searchParams.set("autoplay", "0");
	} else if (
		isAutoplay ||
		// when there is no thumbnail, we don't want to autoplay, unless video is started
		(showThumbnail && showVideo)
	) {
		searchParams.set("autoplay", "1");
	}
	if (isAutoplay && shouldMute) {
		searchParams.set("mute", "1");
	}
	if (play === "Loop") {
		searchParams.set("loop", "1");
		searchParams.set("playlist", videoId);
	}
	if (!isRed) {
		searchParams.set("color", "white");
	}
	const iframeProps = {
		title: title || "Youtube Video",
		allow:
			"presentation; fullscreen; accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture",
		src: embedURL.href,
		frameBorder: "0",
		onClick,
		onMouseEnter,
		onMouseLeave,
		onMouseDown,
		onMouseUp,
	};
	return (
		<article
			onPointerEnter={() => setHovered(true)}
			onPointerLeave={() => setHovered(false)}
			onPointerOver={preloadVideo}
			onKeyDown={startVideo}
			onClick={startVideo}
			style={{
				...wrapperStyle,
				// We do NOT spread the border here anymore.
				// If we did, it would clip the video content inside.
				borderRadius,
				boxShadow,
				transform:
					// Safari sometimes struggles to render border-radius:
					// - on the canvas when changing from 0 to any other value
					// - or when rendering an iframe
					hasBorderRadius && (showVideo || onCanvas)
						? "translateZ(0.000001px)"
						: "unset",
				cursor: "pointer",
				overflow: "hidden",
			}}
			role={"presentation"}
		>
			{showThumbnail && (
				<_Fragment>
					<link rel={"preconnect"} href={"https://i.ytimg.com"} />
					<img
						decoding={"async"}
						src={getThumbnailURL(videoId, thumbnail)}
						style={{
							...videoStyle,
							objectFit: "cover",
						}}
					/>
				</_Fragment>
			)}
			{isPreloading && (
				<_Fragment>
					<link rel={"dns-prefetch"} href={"https://i.ytimg.com"} />
					<link rel={"preconnect"} href={"https://www.youtube.com"} />
					<link rel={"dns-prefetch"} href={"https://www.google.com"} />
				</_Fragment>
			)}
			{!onCanvas ? (
				<iframe
					loading={!showVideo ? "lazy" : void 0}
					style={
						!showVideo
							? {
									...videoStyle,
									display: "none",
								}
							: videoStyle
					}
					{...iframeProps}
				/>
			) : null}
			{border && (
				<div
					style={{
						position: "absolute",
						inset: 0,
						pointerEvents: "none",
						boxSizing: "border-box",
						borderRadius,
						...border,
					}}
				/>
			)}
			{showVideo ? null : (
				<PlayButton onClick={startVideo} isHovered={isHovered} isRed={isRed} />
			)}
		</article>
	);
}
Youtube.displayName = "YouTube";
addPropertyControls(Youtube, {
	url: {
		type: ControlType.String,
		title: "Video",
	},
	play: {
		type: ControlType.Enum,
		title: "Autoplay",
		options: Object.values(PlayOptions),
	},
	shouldMute: {
		title: "Mute",
		type: ControlType.Boolean,
		enabledTitle: "Yes",
		disabledTitle: "No",
		hidden(props) {
			return props.play === "Off";
		},
	},
	thumbnail: {
		title: "Thumbnail",
		description: "Showing a thumbnail improves performance.",
		type: ControlType.Enum,
		options: Object.values(ThumbnailOptions),
		hidden(props) {
			return props.play !== "Off";
		},
	},
	isRed: {
		title: "Color",
		type: ControlType.Boolean,
		enabledTitle: "Red",
		disabledTitle: "White",
	},
	...borderRadiusControl,
	border: {
		type: ControlType.Border,
		optional: true,
	},
	boxShadow: {
		type: ControlType.BoxShadow,
		optional: true,
		title: "Shadows",
	},
	...defaultEvents,
});
var defaultProps = {
	url: "https://youtu.be/8AHPXm9Y6mI",
	play: "Off",
	shouldMute: true,
	thumbnail: "Medium Quality",
	isRed: true,
	boxShadow: null,
	border: null,
};
Youtube.defaultProps = defaultProps;
function parseVideoURL(urlString) {
	let url;
	try {
		url = new URL(urlString);
	} catch {
		const embedURL = getEmbedURL(urlString);
		return [urlString, embedURL, null];
	}
	const searchParams = url.searchParams;
	if (
		url.hostname === "youtube.com" ||
		url.hostname === "www.youtube.com" ||
		url.hostname === "youtube-nocookie.com" ||
		url.hostname === "www.youtube-nocookie.com"
	) {
		const pathSegments = url.pathname.slice(1).split("/");
		const page = pathSegments[0];
		if (page === "watch") {
			const videoId = url.searchParams.get("v");
			const embedURL = getEmbedURL(videoId);
			return [videoId, embedURL, searchParams];
		}
		if (page === "embed") {
			const videoId = pathSegments[1];
			return [videoId, url, searchParams];
		}
		if (page === "shorts" || page === "live") {
			const videoId = pathSegments[1];
			const embedURL = getEmbedURL(videoId);
			return [videoId, embedURL, searchParams];
		}
	}
	if (url.hostname === "youtu.be") {
		const videoId = url.pathname.slice(1);
		const embedURL = getEmbedURL(videoId);
		return [videoId, embedURL, searchParams];
	}
}
function getEmbedURL(videoId) {
	return new URL(`https://www.youtube.com/embed/${videoId}`);
}
function getThumbnailURL(videoId, res) {
	const pre = "https://i.ytimg.com/vi_webp/";
	const ext = "webp";
	switch (res) {
		case "Low Quality":
			return `${pre}${videoId}/hqdefault.${ext}`;
		case "Medium Quality":
			return `${pre}${videoId}/sddefault.${ext}`;
		case "High Quality":
			return `${pre}${videoId}/maxresdefault.${ext}`;
		default:
			return `${pre}${videoId}/0.${ext}`;
	}
}
function Instructions() {
	return (
		<div
			style={{
				...emptyStateStyle,
				overflow: "hidden",
			}}
		>
			<div style={centerTextStyle}>
				{"To embed a Youtube video, add the URL to the properties\xA0panel."}
			</div>
		</div>
	);
}
function ErrorMessage({ message }) {
	return (
		<div
			className={"framerInternalUI-errorPlaceholder"}
			style={{
				...containerStyles,
				overflow: "hidden",
			}}
		>
			<div style={centerTextStyle}>
				{"Error: "}
				{message}
			</div>
		</div>
	);
}
function PlayButton({ onClick, isHovered, isRed }) {
	return (
		<button onClick={onClick} aria-label={"Play"} style={buttonStyle}>
			<svg height={"100%"} version={"1.1"} viewBox={"0 0 68 48"} width={"100%"}>
				<path
					d={
						"M66.52,7.74c-0.78-2.93-2.49-5.41-5.42-6.19C55.79,.13,34,0,34,0S12.21,.13,6.9,1.55 C3.97,2.33,2.27,4.81,1.48,7.74C0.06,13.05,0,24,0,24s0.06,10.95,1.48,16.26c0.78,2.93,2.49,5.41,5.42,6.19 C12.21,47.87,34,48,34,48s21.79-0.13,27.1-1.55c2.93-0.78,4.64-3.26,5.42-6.19C67.94,34.95,68,24,68,24S67.94,13.05,66.52,7.74z"
					}
					fill={isHovered ? (isRed ? "#f00" : "#000") : "#212121"}
					fillOpacity={isHovered ? (isRed ? 1 : 0.8) : 0.8}
					style={{
						transition:
							"fill .1s cubic-bezier(0.4, 0, 1, 1), fill-opacity .1s cubic-bezier(0.4, 0, 1, 1)",
					}}
				/>
				<path d={"M 45,24 27,14 27,34"} fill={"#fff"} />
			</svg>
		</button>
	);
}
var buttonStyle = {
	position: "absolute",
	top: "50%",
	left: "50%",
	transform: "translate(-50%, -50%)",
	width: 68,
	height: 48,
	padding: 0,
	border: "none",
	background: "transparent",
	cursor: "pointer",
};
var wrapperStyle = {
	position: "relative",
	width: "100%",
	height: "100%",
};
var centerTextStyle = {
	textAlign: "center",
	minWidth: 140,
};
var videoStyle = {
	position: "absolute",
	top: 0,
	left: 0,
	height: "100%",
	width: "100%",
};

// /:https://framerusercontent.com/modules/wMH6MfkKywOji5OzJx6y/hWA7rHO4DpNFQbowmbtq/cryRfVcK6.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx,
	getFonts,
	getLoadingLazyAtYPosition,
	getPropertyControls,
	Image,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var VideoFonts = getFonts(Video);
var PlayButtonFonts = getFonts(stdin_default);
var VideoControls = getPropertyControls(Video);
var cycleOrder = [
	"RbcRh4cZw",
	"n9jKDID0y",
	"sbHmDX3GB",
	"lN0JXbimn",
	"UdJzL7BYS",
];
var serializationHash = "framer-42glx";
var variantClassNames = {
	lN0JXbimn: "framer-v-16p7use",
	n9jKDID0y: "framer-v-15evtnm",
	RbcRh4cZw: "framer-v-6uofhj",
	sbHmDX3GB: "framer-v-1nern3d",
	UdJzL7BYS: "framer-v-1ozb1av",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var Y5AgF7Gzt = void 0;
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toImageSrc = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value.src;
	}
	return typeof value === "string" ? value : void 0;
};
var transformTemplate1 = (_, t) => `translate(-50%, -50%) ${t}`;
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Pause - L": "RbcRh4cZw",
	"Pause -M/S": "sbHmDX3GB",
	"Play - L - Hover": "UdJzL7BYS",
	"PLay - L": "n9jKDID0y",
	"Play - M/S": "lN0JXbimn",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ coverImage, height, id, source, video, width, ...props }) => {
	return {
		...props,
		eDDdTxFD4:
			video ??
			props.eDDdTxFD4 ??
			"https://framerusercontent.com/assets/X5paxcPsVqjawSrk1tPt3bPyJHk.mp4",
		IhxSc0t2g: coverImage ??
			props.IhxSc0t2g ?? {
				alt: "",
				pixelHeight: 4876,
				pixelWidth: 8668,
				src: "https://framerusercontent.com/images/1srWHUJqUVL8SmTzt5zFucmJWQ.jpg?width=8668&height=4876",
				srcSet:
					"https://framerusercontent.com/images/1srWHUJqUVL8SmTzt5zFucmJWQ.jpg?scale-down-to=512&width=8668&height=4876 512w,https://framerusercontent.com/images/1srWHUJqUVL8SmTzt5zFucmJWQ.jpg?scale-down-to=1024&width=8668&height=4876 1024w,https://framerusercontent.com/images/1srWHUJqUVL8SmTzt5zFucmJWQ.jpg?scale-down-to=2048&width=8668&height=4876 2048w,https://framerusercontent.com/images/1srWHUJqUVL8SmTzt5zFucmJWQ.jpg?scale-down-to=4096&width=8668&height=4876 4096w,https://framerusercontent.com/images/1srWHUJqUVL8SmTzt5zFucmJWQ.jpg?width=8668&height=4876 8668w",
			},
		tJH4RKsTi: source ?? props.tJH4RKsTi ?? "Upload",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "RbcRh4cZw",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		eDDdTxFD4: eDDdTxFD42,
		tJH4RKsTi: tJH4RKsTi2,
		IhxSc0t2g: IhxSc0t2g2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "RbcRh4cZw",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onMouseEnter1nlhoo5 = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: true,
		});
		setVariant("UdJzL7BYS");
	});
	const onMouseLeave1j7wrsu = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: false,
		});
		setVariant("n9jKDID0y");
	});
	const fMl4WdK65czy439 = activeVariantCallback(async (...args) => {
		setVariant("n9jKDID0y");
	});
	const fMl4WdK65igqcn9 = activeVariantCallback(async (...args) => {
		setVariant("RbcRh4cZw");
	});
	const fMl4WdK651mduqv5 = activeVariantCallback(async (...args) => {
		setVariant("lN0JXbimn");
	});
	const fMl4WdK65osafdn = activeVariantCallback(async (...args) => {
		setVariant("sbHmDX3GB");
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "lN0JXbimn") return false;
		return true;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-6uofhj",
							className,
							classNames,
						)}
						data-framer-name={"Pause - L"}
						layoutDependency={layoutDependency}
						layoutId={"RbcRh4cZw"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								lN0JXbimn: {
									"data-framer-name": "Play - M/S",
								},
								n9jKDID0y: {
									"data-framer-name": "PLay - L",
									"data-highlight": true,
									onMouseEnter: onMouseEnter1nlhoo5,
								},
								sbHmDX3GB: {
									"data-framer-name": "Pause -M/S",
								},
								UdJzL7BYS: {
									"data-framer-name": "Play - L - Hover",
									"data-highlight": true,
									onMouseLeave: onMouseLeave1j7wrsu,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<ComponentViewportProvider>
							<SmartComponentScopedContainer
								className={"framer-13yo7fl-container"}
								isAuthoredByUser={true}
								isModuleExternal={true}
								layoutDependency={layoutDependency}
								layoutId={"hS8kSI8pZ-container"}
								nodeId={"hS8kSI8pZ"}
								rendersWithMotion={true}
								scopeId={"cryRfVcK6"}
							>
								<Video
									backgroundColor={"rgba(0, 0, 0, 0)"}
									borderRadius={10}
									bottomLeftRadius={10}
									bottomRightRadius={10}
									controls={false}
									height={"100%"}
									id={"hS8kSI8pZ"}
									isMixedBorderRadius={false}
									layoutId={"hS8kSI8pZ"}
									loop={true}
									muted={true}
									objectFit={"cover"}
									playing={false}
									poster={toImageSrc(Y5AgF7Gzt)}
									posterEnabled={true}
									srcFile={eDDdTxFD42}
									srcType={tJH4RKsTi2}
									srcUrl={
										"https://framerusercontent.com/assets/MLWPbW1dUQawJLhhun3dBwpgJak.mp4"
									}
									startTime={0}
									style={{
										height: "100%",
										width: "100%",
									}}
									topLeftRadius={10}
									topRightRadius={10}
									volume={25}
									width={"100%"}
									{...addPropertyOverrides(
										{
											lN0JXbimn: {
												playing: true,
											},
											n9jKDID0y: {
												playing: true,
											},
											UdJzL7BYS: {
												playing: true,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={72}
							y={
								(componentViewport?.y || 0) +
								((componentViewport?.height || 550) * 0.5000000000000002 - 36)
							}
						>
							<SmartComponentScopedContainer
								className={"framer-1lwjvkn-container"}
								layoutDependency={layoutDependency}
								layoutId={"Pxp911uIY-container"}
								nodeId={"Pxp911uIY"}
								rendersWithMotion={true}
								scopeId={"cryRfVcK6"}
								style={{
									opacity: 1,
								}}
								transformTemplate={transformTemplate1}
								variants={{
									lN0JXbimn: {
										opacity: 1,
									},
									n9jKDID0y: {
										opacity: 0,
									},
									sbHmDX3GB: {
										opacity: 1,
									},
									UdJzL7BYS: {
										opacity: 1,
									},
								}}
							>
								{_jsx2(stdin_default, {
									fMl4WdK65: fMl4WdK65czy439,
									height: "100%",
									id: "Pxp911uIY",
									layoutId: "Pxp911uIY",
									variant: matchVariant("r1TCcAoDi"),
									width: "100%",
									...addPropertyOverrides(
										{
											lN0JXbimn: {
												fMl4WdK65: fMl4WdK65osafdn,
												variant: matchVariant("uIhzbfwFf"),
											},
											n9jKDID0y: {
												fMl4WdK65: fMl4WdK65igqcn9,
												variant: matchVariant("sELt6iCMD"),
											},
											sbHmDX3GB: {
												fMl4WdK65: fMl4WdK651mduqv5,
												variant: matchVariant("uIhzbfwFf"),
											},
											UdJzL7BYS: {
												fMl4WdK65: fMl4WdK65igqcn9,
												variant: matchVariant("sELt6iCMD"),
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						{isDisplayed() && (
							<Image
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											((componentViewport?.height || 550) * 0.5000000000000002 -
												((componentViewport?.height || 550) * 1.01) / 2),
									),
									pixelHeight: 4876,
									pixelWidth: 8668,
									sizes: `calc(${componentViewport?.width || "100vw"} * 1.01)`,
									...toResponsiveImage(IhxSc0t2g2),
								}}
								className={"framer-1qiz9in"}
								data-framer-name={"Cover Image"}
								layoutDependency={layoutDependency}
								layoutId={"MadWAxwBo"}
								style={{
									opacity: 1,
								}}
								variants={{
									n9jKDID0y: {
										opacity: 0,
									},
									sbHmDX3GB: {
										opacity: 1,
									},
									UdJzL7BYS: {
										opacity: 0,
									},
								}}
							/>
						)}
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-42glx.framer-14abvvo, .framer-42glx .framer-14abvvo { display: block; }",
	".framer-42glx.framer-6uofhj { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 550px; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1000px; }",
	".framer-42glx .framer-13yo7fl-container { flex: 1 0 0px; height: 100%; position: relative; width: 1px; }",
	".framer-42glx .framer-1lwjvkn-container { flex: none; height: auto; left: 50%; position: absolute; top: 50%; width: auto; z-index: 1; }",
	".framer-42glx .framer-1qiz9in { flex: none; height: 101%; left: calc(50.00000000000002% - 101% / 2); overflow: visible; position: absolute; top: calc(50.00000000000002% - 101% / 2); width: 101%; }",
];
var FramercryRfVcK6 = withCSS(Component, css, "framer-42glx");
var stdin_default2 = FramercryRfVcK6;
FramercryRfVcK6.displayName = "Hero Video Player Frame";
FramercryRfVcK6.defaultProps = {
	height: 550,
	width: 1e3,
};
addPropertyControls2(FramercryRfVcK6, {
	variant: {
		options: ["RbcRh4cZw", "n9jKDID0y", "sbHmDX3GB", "lN0JXbimn", "UdJzL7BYS"],
		optionTitles: [
			"Pause - L",
			"PLay - L",
			"Pause -M/S",
			"Play - M/S",
			"Play - L - Hover",
		],
		title: "Variant",
		type: ControlType2.Enum,
	},
	eDDdTxFD4: VideoControls?.["srcFile"] && {
		...VideoControls["srcFile"],
		__defaultAssetReference:
			"data:framer/asset-reference,X5paxcPsVqjawSrk1tPt3bPyJHk.mp4?originalFilename=7.mp4",
		description: "",
		hidden: void 0,
		title: "Video",
	},
	tJH4RKsTi: VideoControls?.["srcType"] && {
		...VideoControls["srcType"],
		defaultValue: "Upload",
		description: void 0,
		hidden: void 0,
		title: "Source",
	},
	IhxSc0t2g: {
		__defaultAssetReference:
			"data:framer/asset-reference,1srWHUJqUVL8SmTzt5zFucmJWQ.jpg?originalFilename=Video+cover.jpg&width=8668&height=4876",
		__vekterDefault: {
			alt: "",
			assetReference:
				"data:framer/asset-reference,1srWHUJqUVL8SmTzt5zFucmJWQ.jpg?originalFilename=Video+cover.jpg&width=8668&height=4876",
		},
		title: "Cover Image",
		type: ControlType2.ResponsiveImage,
	},
});
addFonts(
	FramercryRfVcK6,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...VideoFonts,
		...PlayButtonFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/rqnuOtEPD7rQLPKaRwr7/1PEcSPSoJxeriXObRSqI/DGtwnUeFZ.js
var HeroVideoPlayerFrameFonts = getFonts2(stdin_default2);
var YouTubeFonts = getFonts2(Youtube);
var HeroVideoPlayerFrameControls = getPropertyControls2(stdin_default2);
var cycleOrder2 = ["RJPiXthhh", "FcY2VfQJa"];
var serializationHash2 = "framer-Usdwr";
var variantClassNames2 = {
	FcY2VfQJa: "framer-v-12334p0",
	RJPiXthhh: "framer-v-wj00ba",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var equals = (a, b) => {
	return typeof a === "string" && typeof b === "string"
		? a.toLowerCase() === b.toLowerCase()
		: a === b;
};
var addImageAlt = (image, alt) => {
	if (!image || typeof image !== "object") {
		return;
	}
	return {
		...image,
		alt,
	};
};
var matchVariant2 = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var humanReadableVariantMap2 = {
	L: "RJPiXthhh",
	S: "FcY2VfQJa",
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableEnumMap = {
	"Video Upload": "hvlWPyP3i",
	Youtube: "x6K91dNaF",
};
var getProps2 = ({
	height,
	id,
	source,
	videoFile,
	videoType,
	width,
	youtubeURL,
	...props
}) => {
	return {
		...props,
		enyecMhXi: youtubeURL ?? props.enyecMhXi ?? "https://youtu.be/8AHPXm9Y6mI",
		gqRz5THmT:
			humanReadableEnumMap[videoType] ??
			videoType ??
			props.gqRz5THmT ??
			"x6K91dNaF",
		GuFy_7Tbr:
			videoFile ??
			props.GuFy_7Tbr ??
			"https://framerusercontent.com/assets/9AMNA1EeVoxk8Nx2kdxOS4UmXUs.mp4",
		sKRpUCW6c: source ?? props.sKRpUCW6c ?? "Upload",
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "RJPiXthhh",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className,
		layoutId,
		variant,
		gqRz5THmT: gqRz5THmT2,
		GuFy_7Tbr: GuFy_7Tbr2,
		sKRpUCW6c: sKRpUCW6c2,
		enyecMhXi: enyecMhXi2,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "RJPiXthhh",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	const visible = equals(gqRz5THmT2, "hvlWPyP3i");
	const visible1 = equals(gqRz5THmT2, "x6K91dNaF");
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-wj00ba",
							className,
							classNames,
						)}
						data-border={true}
						data-framer-name={"L"}
						layoutDependency={layoutDependency}
						layoutId={"RJPiXthhh"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "3px",
							"--border-color":
								"var(--token-29e06a2f-472e-4017-9c97-e1188645fe0f, rgba(0, 122, 187, 0.2))",
							"--border-left-width": "3px",
							"--border-right-width": "3px",
							"--border-style": "solid",
							"--border-top-width": "3px",
							borderBottomLeftRadius: 15,
							borderBottomRightRadius: 15,
							borderTopLeftRadius: 15,
							borderTopRightRadius: 15,
							...style,
						}}
						variants={{
							FcY2VfQJa: {
								borderBottomLeftRadius: 11,
								borderBottomRightRadius: 11,
								borderTopLeftRadius: 11,
								borderTopRightRadius: 11,
							},
						}}
						{...addPropertyOverrides2(
							{
								FcY2VfQJa: {
									"data-framer-name": "S",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						{visible !== false && (
							<motion2.div
								className={"framer-2ov4eu"}
								data-framer-name={"Video "}
								layoutDependency={layoutDependency}
								layoutId={"qGMVDzjjy"}
								style={{
									borderBottomLeftRadius: 12,
									borderBottomRightRadius: 12,
									borderTopLeftRadius: 12,
									borderTopRightRadius: 12,
								}}
								variants={{
									FcY2VfQJa: {
										borderBottomLeftRadius: 8,
										borderBottomRightRadius: 8,
										borderTopLeftRadius: 8,
										borderTopRightRadius: 8,
									},
								}}
							>
								<ComponentViewportProvider2
									height={600}
									width={`max((${componentViewport?.width || "100vw"} + 2px) / 0, 1px)`}
									y={
										(componentViewport?.y || 0) +
										(4 + ((componentViewport?.height || 603) - 8 - 600) / 2) +
										0
									}
									{...addPropertyOverrides2(
										{
											FcY2VfQJa: {
												height: 250,
												y:
													(componentViewport?.y || 0) +
													(4 +
														((componentViewport?.height || 200) - 8 - 250) /
															2) +
													0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer2
										className={"framer-1id3qfv-container"}
										data-framer-name={"Video"}
										layoutDependency={layoutDependency}
										layoutId={"MoPVuuz01-container"}
										name={"Video"}
										nodeId={"MoPVuuz01"}
										rendersWithMotion={true}
										scopeId={"DGtwnUeFZ"}
									>
										{_jsx3(stdin_default2, {
											eDDdTxFD4: GuFy_7Tbr2,
											height: "100%",
											id: "MoPVuuz01",
											IhxSc0t2g: addImageAlt(
												{
													pixelHeight: 1080,
													pixelWidth: 1920,
													positionX: "52.2%",
													positionY: "31.1%",
													src: "https://framerusercontent.com/images/wjGvEbGpgzFHMNhyPrusCjmlg.webp?width=1920&height=1080",
													srcSet:
														"https://framerusercontent.com/images/wjGvEbGpgzFHMNhyPrusCjmlg.webp?scale-down-to=512&width=1920&height=1080 512w,https://framerusercontent.com/images/wjGvEbGpgzFHMNhyPrusCjmlg.webp?scale-down-to=1024&width=1920&height=1080 1024w,https://framerusercontent.com/images/wjGvEbGpgzFHMNhyPrusCjmlg.webp?width=1920&height=1080 1920w",
												},
												"Asian man with glasses in a creative workspace, surrounded by colorful abstract art and stationery on a cluttered desk.",
											),
											layoutId: "MoPVuuz01",
											name: "Video",
											style: {
												height: "100%",
												width: "100%",
											},
											tJH4RKsTi: sKRpUCW6c2,
											variant: matchVariant2("RbcRh4cZw"),
											width: "100%",
											...addPropertyOverrides2(
												{
													FcY2VfQJa: {
														variant: matchVariant2("sbHmDX3GB"),
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer2>
								</ComponentViewportProvider2>
							</motion2.div>
						)}
						{visible1 !== false && (
							<motion2.div
								className={"framer-1xiwv66"}
								data-framer-name={"Youtube"}
								layoutDependency={layoutDependency}
								layoutId={"I2rzrlmZ2"}
								style={{
									borderBottomLeftRadius: 12,
									borderBottomRightRadius: 12,
									borderTopLeftRadius: 12,
									borderTopRightRadius: 12,
								}}
								variants={{
									FcY2VfQJa: {
										borderBottomLeftRadius: 8,
										borderBottomRightRadius: 8,
										borderTopLeftRadius: 8,
										borderTopRightRadius: 8,
									},
								}}
							>
								<ComponentViewportProvider2>
									<SmartComponentScopedContainer2
										className={"framer-16oq8ae-container"}
										isAuthoredByUser={true}
										isModuleExternal={true}
										layoutDependency={layoutDependency}
										layoutId={"xASvFlA7k-container"}
										nodeId={"xASvFlA7k"}
										rendersWithMotion={true}
										scopeId={"DGtwnUeFZ"}
									>
										<Youtube
											borderRadius={0}
											bottomLeftRadius={0}
											bottomRightRadius={0}
											boxShadow={""}
											height={"100%"}
											id={"xASvFlA7k"}
											isMixedBorderRadius={false}
											isRed={false}
											layoutId={"xASvFlA7k"}
											play={"Off"}
											shouldMute={true}
											style={{
												height: "100%",
												width: "100%",
											}}
											thumbnail={"High Quality"}
											topLeftRadius={0}
											topRightRadius={0}
											url={enyecMhXi2}
											width={"100%"}
										/>
									</SmartComponentScopedContainer2>
								</ComponentViewportProvider2>
							</motion2.div>
						)}
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-Usdwr.framer-un00sx, .framer-Usdwr .framer-un00sx { display: block; }",
	".framer-Usdwr.framer-wj00ba { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; max-width: 1000px; overflow: var(--overflow-clip-fallback, clip); padding: 4px; position: relative; width: 1000px; will-change: var(--framer-will-change-override, transform); }",
	".framer-Usdwr .framer-2ov4eu { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }",
	".framer-Usdwr .framer-1id3qfv-container { aspect-ratio: 1.6533333333333333 / 1; flex: 1 0 0px; height: var(--framer-aspect-ratio-supported, 121px); position: relative; width: 1px; }",
	".framer-Usdwr .framer-1xiwv66 { align-content: center; align-items: center; aspect-ratio: 1.6666666666666667 / 1; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 595px); justify-content: center; max-width: 1000px; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }",
	".framer-Usdwr .framer-16oq8ae-container { flex: none; height: 100%; position: relative; width: 100%; }",
	".framer-Usdwr.framer-v-12334p0.framer-wj00ba { width: 390px; }",
	".framer-Usdwr.framer-v-12334p0 .framer-1xiwv66 { height: var(--framer-aspect-ratio-supported, 120px); }",
	'.framer-Usdwr[data-border="true"]::after, .framer-Usdwr [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramerDGtwnUeFZ = withCSS2(Component2, css2, "framer-Usdwr");
var stdin_default3 = FramerDGtwnUeFZ;
FramerDGtwnUeFZ.displayName = "Video Player Hero Frame";
FramerDGtwnUeFZ.defaultProps = {
	height: 603,
	width: 1e3,
};
addPropertyControls3(FramerDGtwnUeFZ, {
	variant: {
		options: ["RJPiXthhh", "FcY2VfQJa"],
		optionTitles: ["L", "S"],
		title: "Variant",
		type: ControlType3.Enum,
	},
	gqRz5THmT: {
		defaultValue: "x6K91dNaF",
		options: ["x6K91dNaF", "hvlWPyP3i"],
		optionTitles: ["Youtube", "Video Upload"],
		title: "Video Type",
		type: ControlType3.Enum,
	},
	GuFy_7Tbr: HeroVideoPlayerFrameControls?.["eDDdTxFD4"] && {
		...HeroVideoPlayerFrameControls["eDDdTxFD4"],
		__defaultAssetReference:
			"data:framer/asset-reference,9AMNA1EeVoxk8Nx2kdxOS4UmXUs.mp4?originalFilename=130648-747868373_small.mp4",
		description: void 0,
		hidden: void 0,
		title: "Video File",
	},
	sKRpUCW6c: HeroVideoPlayerFrameControls?.["tJH4RKsTi"] && {
		...HeroVideoPlayerFrameControls["tJH4RKsTi"],
		defaultValue: "Upload",
		description: void 0,
		hidden: void 0,
		title: "Source",
	},
	enyecMhXi: {
		defaultValue: "https://youtu.be/8AHPXm9Y6mI",
		title: "Youtube URL",
		type: ControlType3.String,
	},
});
addFonts2(
	FramerDGtwnUeFZ,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...HeroVideoPlayerFrameFonts,
		...YouTubeFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:video-player-hero-frame
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "FcY2VfQJa",
	xl: "RJPiXthhh",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5af1700726b89e1359bd903da3e469ba956b8fc7e56af575f49bcf468e7d9c62"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders VideoPlayerHeroFrameFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5af1700726b89e1359bd903da3e469ba956b8fc7e56af575f49bcf468e7d9c62"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var video_player_hero_frame_default = ComponentWithRoot;
export { video_player_hero_frame_default as default };
