// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5af1700726b89e13 "Cliplab Studio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'L' | 'M/S' // Variant
 * file?: string // File
 * source?: 'URL' | 'Upload' // Source
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * text?: string // Text
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-6HGIPRDC.js";
import { Video } from "./chunks/chunk-3COXQQ4E.js";
import { routes } from "./chunks/chunk-2NVZ5JSA.js";

// virtual:video-player
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/uLdTlsM52vCzc5qKpqaz/5KIEfCecjnEYM38ogcmr/k2Vk_be5W.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	getPropertyControls,
	Image,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var VideoFonts = getFonts(Video);
var VideoControls = getPropertyControls(Video);
var cycleOrder = ["Atbby340c", "bLKpyAusL"];
var serializationHash = "framer-sbE2L";
var variantClassNames = {
	Atbby340c: "framer-v-fx477n",
	bLKpyAusL: "framer-v-1vh0xef",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var Y5AgF7GztcryRfVcK6 = void 0;
var transition1 = {
	damping: 80,
	delay: 0,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var toImageSrc = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value.src;
	}
	return typeof value === "string" ? value : void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"M/S": "bLKpyAusL",
	L: "Atbby340c",
};
var getProps = ({ file, height, id, image, source, text, width, ...props }) => {
	return {
		...props,
		EiccCQAL1: source ?? props.EiccCQAL1 ?? "Upload",
		Kb057vsP6:
			file ??
			props.Kb057vsP6 ??
			"https://framerusercontent.com/assets/3B7KU8CJ9iFihc53tVJUQzq1EuM.mp4",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "Atbby340c",
		VwdlXcOKw: text ?? props.VwdlXcOKw ?? "Jahn Jacob",
		ZiYzbP6im: image ??
			props.ZiYzbP6im ?? {
				alt: "",
				pixelHeight: 1200,
				pixelWidth: 1200,
				src: "https://framerusercontent.com/images/BVdUEHTnLtzDM3IkgeDZxn6eAt4.webp?width=1200&height=1200",
				srcSet:
					"https://framerusercontent.com/images/BVdUEHTnLtzDM3IkgeDZxn6eAt4.webp?scale-down-to=512&width=1200&height=1200 512w,https://framerusercontent.com/images/BVdUEHTnLtzDM3IkgeDZxn6eAt4.webp?scale-down-to=1024&width=1200&height=1200 1024w,https://framerusercontent.com/images/BVdUEHTnLtzDM3IkgeDZxn6eAt4.webp?width=1200&height=1200 1200w",
			},
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		Kb057vsP6: Kb057vsP62,
		EiccCQAL1: EiccCQAL12,
		ZiYzbP6im: ZiYzbP6im2,
		VwdlXcOKw: VwdlXcOKw2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "Atbby340c",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-fx477n",
							className2,
							classNames,
						)}
						data-framer-name={"L"}
						layoutDependency={layoutDependency}
						layoutId={"Atbby340c"}
						ref={refBinding}
						style={{
							borderBottomLeftRadius: 10,
							borderBottomRightRadius: 10,
							borderTopLeftRadius: 10,
							borderTopRightRadius: 10,
							...style,
						}}
						{...addPropertyOverrides(
							{
								bLKpyAusL: {
									"data-framer-name": "M/S",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1366vlc"}
							data-framer-name={"Profile"}
							layoutDependency={layoutDependency}
							layoutId={"izy1oEsKK"}
						>
							<Image
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											(componentViewport?.height || 550) -
											64 +
											0,
									),
									pixelHeight: 1200,
									pixelWidth: 1200,
									sizes: "30px",
									...toResponsiveImage(ZiYzbP6im2),
								}}
								className={"framer-1nkeizm"}
								layoutDependency={layoutDependency}
								layoutId={"WQ0vlTQy2"}
								style={{
									borderBottomLeftRadius: 243,
									borderBottomRightRadius: 243,
									borderTopLeftRadius: 243,
									borderTopRightRadius: 243,
								}}
								{...addPropertyOverrides(
									{
										bLKpyAusL: {
											background: {
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														(componentViewport?.height || 550) -
														60 +
														0,
												),
												pixelHeight: 1200,
												pixelWidth: 1200,
												sizes: "30px",
												...toResponsiveImage(ZiYzbP6im2),
											},
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-10drdft"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"FYG8mB9KO"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={VwdlXcOKw2}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-5xfrwz"}
										data-styles-preset={"ruLAtCqcd"}
									>
										{"Jahn Jacob"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
						<ComponentViewportProvider>
							<SmartComponentScopedContainer
								className={"framer-1h46hr-container"}
								isAuthoredByUser={true}
								isModuleExternal={true}
								layoutDependency={layoutDependency}
								layoutId={"Tu90YI7Xw-container"}
								nodeId={"Tu90YI7Xw"}
								rendersWithMotion={true}
								scopeId={"k2Vk_be5W"}
							>
								<Video
									backgroundColor={"rgba(0, 0, 0, 0)"}
									borderRadius={10}
									bottomLeftRadius={10}
									bottomRightRadius={10}
									controls={false}
									height={"100%"}
									id={"Tu90YI7Xw"}
									isMixedBorderRadius={false}
									layoutId={"Tu90YI7Xw"}
									loop={true}
									muted={true}
									objectFit={"cover"}
									playing={true}
									poster={toImageSrc(Y5AgF7GztcryRfVcK6)}
									posterEnabled={true}
									srcFile={Kb057vsP62}
									srcType={EiccCQAL12}
									srcUrl={
										"https://framerusercontent.com/assets/MLWPbW1dUQawJLhhun3dBwpgJak.mp4"
									}
									startTime={0}
									style={{
										height: "100%",
										width: "100%",
									}}
									topLeftRadius={10}
									topRightRadius={10}
									volume={25}
									width={"100%"}
								/>
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<motion.div
							className={"framer-dutcif"}
							data-framer-name={"Overlay"}
							layoutDependency={layoutDependency}
							layoutId={"yFkgO485z"}
							style={{
								background:
									"linear-gradient(180deg, rgba(0, 0, 0, 0) 0%, rgb(0, 0, 0) 115.00000000000001%)",
							}}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-sbE2L.framer-1e23gm0, .framer-sbE2L .framer-1e23gm0 { display: block; }",
	".framer-sbE2L.framer-fx477n { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 550px; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 366px; will-change: var(--framer-will-change-override, transform); }",
	".framer-sbE2L .framer-1366vlc { align-content: center; align-items: center; bottom: 24px; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; left: 24px; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: absolute; width: min-content; z-index: 2; }",
	".framer-sbE2L .framer-1nkeizm { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 30px); overflow: var(--overflow-clip-fallback, clip); position: relative; width: 30px; will-change: var(--framer-will-change-override, transform); }",
	".framer-sbE2L .framer-10drdft { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-sbE2L .framer-1h46hr-container { flex: 1 0 0px; height: 100%; position: relative; width: 1px; }",
	".framer-sbE2L .framer-dutcif { bottom: 0px; flex: none; height: 14%; left: calc(50.00000000000002% - 101.09289617486338% / 2); overflow: var(--overflow-clip-fallback, clip); position: absolute; width: 101%; z-index: 1; }",
	".framer-sbE2L.framer-v-1vh0xef.framer-fx477n { aspect-ratio: 0.6654545454545454 / 1; height: var(--framer-aspect-ratio-supported, 550px); }",
	".framer-sbE2L.framer-v-1vh0xef .framer-1366vlc { bottom: 20px; left: 20px; }",
	".framer-sbE2L.framer-v-1vh0xef .framer-dutcif { height: 18%; }",
	...css,
];
var Framerk2Vk_be5W = withCSS(Component, css2, "framer-sbE2L");
var stdin_default = Framerk2Vk_be5W;
Framerk2Vk_be5W.displayName = "Video Player";
Framerk2Vk_be5W.defaultProps = {
	height: 550,
	width: 366,
};
addPropertyControls(Framerk2Vk_be5W, {
	variant: {
		options: ["Atbby340c", "bLKpyAusL"],
		optionTitles: ["L", "M/S"],
		title: "Variant",
		type: ControlType.Enum,
	},
	Kb057vsP6: VideoControls?.["srcFile"] && {
		...VideoControls["srcFile"],
		__defaultAssetReference:
			"data:framer/asset-reference,3B7KU8CJ9iFihc53tVJUQzq1EuM.mp4?originalFilename=2.mp4",
		description: void 0,
		hidden: void 0,
		title: "File",
	},
	EiccCQAL1: VideoControls?.["srcType"] && {
		...VideoControls["srcType"],
		defaultValue: "Upload",
		description: void 0,
		hidden: void 0,
		title: "Source",
	},
	ZiYzbP6im: {
		__defaultAssetReference:
			"data:framer/asset-reference,BVdUEHTnLtzDM3IkgeDZxn6eAt4.webp?originalFilename=Young+Man+in+Focus.webp&width=1200&height=1200",
		__vekterDefault: {
			alt: "",
			assetReference:
				"data:framer/asset-reference,BVdUEHTnLtzDM3IkgeDZxn6eAt4.webp?originalFilename=Young+Man+in+Focus.webp&width=1200&height=1200",
		},
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	VwdlXcOKw: {
		defaultValue: "Jahn Jacob",
		displayTextArea: false,
		title: "Text",
		type: ControlType.String,
	},
});
addFonts(
	Framerk2Vk_be5W,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...VideoFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:video-player
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "bLKpyAusL",
	lg: "Atbby340c",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5af1700726b89e1359bd903da3e469ba956b8fc7e56af575f49bcf468e7d9c62"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders VideoPlayerFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5af1700726b89e1359bd903da3e469ba956b8fc7e56af575f49bcf468e7d9c62"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var video_player_default = ComponentWithRoot;
export { video_player_default as default };
